#!/usr/bin/env bash
# Build a claw-remote distribution tarball for a given target.
#
# Produces: out/claw-remote-<os>-<arch>-<version>.tar.gz
#
# Usage:
#   scripts/build-tarball.sh                                # host target
#   scripts/build-tarball.sh --target linux-x64             # cross-target
#   scripts/build-tarball.sh --target darwin-arm64 --version 0.2.0
#   scripts/build-tarball.sh --target linux-arm64 --out ./build
#
# Targets supported: darwin-arm64, darwin-x64, linux-x64, linux-arm64, windows-x64
#
# The tarball contains:
#   bin/claw-remote       wrapper script that execs the entrypoint
#   lib/start.js             bundled daemon (everything except native addons)
#   lib/start.js.map         sourcemap if produced
#   node_modules/better-sqlite3
#   package.json             pinned runtime deps
#   LICENSE                  (best-effort, see repo)
#   INSTALL.txt              install instructions for end users
set -euo pipefail

bridge_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
repo_root="$(cd "$bridge_root/.." && pwd)"
out_dir="$bridge_root/out"
version=""
target=""

while [ "$#" -gt 0 ]; do
  case "$1" in
    --target) target="$2"; shift 2;;
    --version) version="$2"; shift 2;;
    --out) out_dir="$2"; shift 2;;
    -h|--help)
      grep -E "^# " "$0" | sed -e 's/^# //'
      exit 0;;
    *) echo "unknown arg: $1" >&2; exit 1;;
  esac
done

normalize_arch() {
  case "$1" in
    x86_64|amd64) echo "x64";;
    aarch64|arm64) echo "arm64";;
    *) echo "$1";;
  esac
}

normalize_os() {
  case "$1" in
    Linux|linux) echo "linux";;
    Darwin|darwin) echo "darwin";;
    MINGW*|MSYS*|CYGWIN*|Windows_NT|windows|win32) echo "windows";;
    *) echo "$1";;
  esac
}

if [ -z "$target" ]; then
  target_os="$(normalize_os "$(uname -s)")"
  target_arch="$(normalize_arch "$(uname -m)")"
else
  target_os="${target%%-*}"
  target_arch="${target##*-}"
fi

case "$target_os-$target_arch" in
  darwin-arm64|darwin-x64|linux-x64|linux-arm64|windows-x64) ;;
  *) echo "unsupported target: $target_os-$target_arch" >&2; exit 1;;
esac

if [ -z "$version" ]; then
  version="$(node -p "require('$bridge_root/package.json').version")"
fi

npm_platform="$target_os"
[ "$npm_platform" = "windows" ] && npm_platform="win32"
npm_arch="$target_arch"

echo "[build-tarball] target=$target_os-$target_arch version=$version"

# 1. Build the bundled daemon. Only native addons stay external.
echo "[build-tarball] building dist with tsup (externals: better-sqlite3, ssh2)"
cd "$bridge_root"
/opt/homebrew/bin/npx tsup --config tsup.dist.config.ts >/dev/null

# 2. Stage the contents of the tarball.
staging="$(mktemp -d -t claw-remote-stage-XXXX)"
trap 'rm -rf "$staging"' EXIT
mkdir -p "$staging/bin" "$staging/lib"
cp "$bridge_root/dist/start.cjs" "$staging/lib/start.cjs"
if [ -f "$bridge_root/dist/start.cjs.map" ]; then
  cp "$bridge_root/dist/start.cjs.map" "$staging/lib/start.cjs.map"
fi

# 3. Generate the wrapper script. POSIX sh so it works on Alpine/BusyBox.
cat > "$staging/bin/claw-remote" <<'WRAPPER'
#!/bin/sh
HERE="$(cd "$(dirname "$0")/.." && pwd)"
if [ -z "${NODE:-}" ]; then
  if command -v node >/dev/null 2>&1; then
    NODE="$(command -v node)"
  else
    echo "claw-remote: node not found in PATH; install Node.js >= 20" >&2
    exit 1
  fi
fi
exec "$NODE" "$HERE/lib/start.cjs" "$@"
WRAPPER
chmod +x "$staging/bin/claw-remote"

# 4. Pinned runtime package.json so the user's npm install fetches the right
#    prebuilt better-sqlite3 binary for the target.
cat > "$staging/package.json" <<EOF
{
  "name": "claw-remote-runtime",
  "version": "$version",
  "private": true,
  "type": "module",
  "engines": { "node": ">=20" },
  "dependencies": {
    "better-sqlite3": "^12.4.1",
    "ssh2": "^1.16.0"
  }
}
EOF

# 5. Resolve the native deps for the target. better-sqlite3 ships prebuilts via
#    prebuild-install; the target_platform / target_arch env vars steer the
#    download even when the host differs.
echo "[build-tarball] installing runtime deps for $npm_platform-$npm_arch"
(
  cd "$staging"
  npm_config_target_platform="$npm_platform" \
  npm_config_target_arch="$npm_arch" \
  npm_config_runtime="napi" \
  npm_config_build_from_source="false" \
  /opt/homebrew/bin/npm install --omit=dev --no-fund --no-audit --silent
)

# 6. Documentation in the tarball itself.
cat > "$staging/INSTALL.txt" <<EOF
claw-remote $version ($target_os-$target_arch)

To install:

  tar xzf $(basename "$0")  # if you started from the tarball, you already did this
  cd claw-remote-*
  ./bin/claw-remote --help

System service (systemd --user, Linux):

  mkdir -p \$HOME/.config/systemd/user
  cp deploy/claw-remote.service \$HOME/.config/systemd/user/ 2>/dev/null || \
    echo "deploy/claw-remote.service is generated by scripts/install.sh"
  systemctl --user daemon-reload
  systemctl --user enable --now claw-remote

Or use the canonical installer from the source tree:

  ./scripts/install.sh --tarball ./claw-remote-$target_os-$target_arch-$version.tar.gz

Configuration via env vars (see bridge/src/config.ts):
  CLAW_REMOTE_PORT (default 7778)
  CLAW_REMOTE_HTTP_PORT (default 7779)
  CLAW_REMOTE_BIND (default 127.0.0.1)
  CLAW_REMOTE_DB
  CLAW_REMOTE_STATUS
  CLAW_REMOTE_NAME
EOF

if [ -f "$repo_root/LICENSE" ]; then
  cp "$repo_root/LICENSE" "$staging/LICENSE"
fi

# 7. Tar it up. Rename the staging dir so the archive expands into a stable
#    `claw-remote-<version>/` directory regardless of the temp path.
mkdir -p "$out_dir"
tarball="$out_dir/claw-remote-$target_os-$target_arch-$version.tar.gz"
release_dir="$(dirname "$staging")/claw-remote-$version"
rm -rf "$release_dir"
mv "$staging" "$release_dir"
staging="$release_dir"

( cd "$(dirname "$release_dir")" && \
  tar -czf "$tarball" \
    --exclude='*.DS_Store' \
    --exclude='node_modules/.cache' \
    "$(basename "$release_dir")" )

echo "[build-tarball] wrote $tarball"
