import { fileURLToPath } from "url";

export const RUNTIME_ADAPTER_IDS = new Set([
  "demo",
  "claw",
  "openclaw",
  "codex",
  "zeroclaw",
  "picoclaw",
  "nanobot",
  "nanoclaw",
  "nullclaw",
  "ironclaw",
  "nemoclaw",
  "hermes",
]);

export const CORE_PRODUCTIVITY_DB_COLLECTIONS: Record<string, string> = {
  task: "tasks",
  tasks: "tasks",
  list: "lists",
  lists: "lists",
  section: "sections",
  sections: "sections",
  project: "projects",
  projects: "projects",
  goal: "goals",
  goals: "goals",
  comment: "comments",
  comments: "comments",
  attachment: "attachments",
  attachments: "attachments",
  view: "saved_views",
  views: "saved_views",
  saved_view: "saved_views",
  saved_views: "saved_views",
  recurrence: "recurrences",
  recurrences: "recurrences",
  cycle: "cycles",
  cycles: "cycles",
  sprint: "cycles",
  sprints: "cycles",
  epic: "epics",
  epics: "epics",
  initiative: "epics",
  initiatives: "epics",
  custom_field: "custom_fields",
  custom_fields: "custom_fields",
  field_value: "field_values",
  field_values: "field_values",
  template: "templates",
  templates: "templates",
  reminder: "reminders",
  reminders: "reminders",
  deadline: "deadlines",
  deadlines: "deadlines",
  note: "notes",
  notes: "notes",
  person: "people",
  people: "people",
  event: "events",
  events: "events",
};

export const LOCAL_FIRST_PRODUCTIVITY_GROUPS = new Set([
  "areas",
  "lists",
  "sections",
  "tasks",
  "goals",
  "projects",
  "comments",
  "attachments",
  "saved-views",
  "recurrences",
  "cycles",
  "sprints",
  "epics",
  "initiatives",
  "custom-fields",
  "field-values",
  "templates",
  "milestones",
  "activity",
  "blockers",
  "artifacts",
  "decisions",
  "work-sessions",
  "assignments",
  "handoffs",
  "approvals",
  "capacity",
  "reminders",
  "deadlines",
  "notes",
  "people",
  "inbox",
  "events",
  "my-work",
  "team-work",
  "timeline",
]);

export const CLI_TEMPLATE_ROOT = fileURLToPath(new URL("../templates", import.meta.url));
