import type { BuiltinRelationKind } from "./builtins/_types.ts";
import type {
  CatalogAuditStructuralChange,
  CatalogAuditedFieldMapping,
  CatalogAuditedNeed,
  CatalogAuditedRelationMapping,
  CatalogCoverageStatus,
} from "./catalog-coverage.ts";

type AuditedNeedTemplateOverride = Partial<{
  fields: string[];
  requiredEntities: string[];
  relationKind: BuiltinRelationKind;
  fieldMappings: CatalogAuditedFieldMapping[];
  relationMappings: CatalogAuditedRelationMapping[];
  jsonAudit: CatalogAuditedNeed["jsonAudit"];
  structuralChange: CatalogAuditStructuralChange;
  coverageStatus: CatalogCoverageStatus;
  notes: string;
}>;

export const AUDITED_NEED_TEMPLATE_OVERRIDES: Record<string, Record<string, AuditedNeedTemplateOverride>> = {
  learning_assessment: {
    record_lifecycle: {
      fields: ["title", "status", "startedAt", "completedAt"],
      requiredEntities: ["learner", "course", "lesson"],
      fieldMappings: [
        { collectionName: "courses", fieldName: "title", aliasesReviewed: ["courseTitle"] },
        { collectionName: "courses", fieldName: "status" },
        { collectionName: "courses", fieldName: "startedAt" },
        { collectionName: "courses", fieldName: "completedAt" },
      ],
      relationMappings: [{ collectionName: "lessons", fieldName: "courseId", targetCollectionName: "courses", kind: "ownership" }],
      jsonAudit: { status: "typed_fields_available", notes: "Course lifecycle state is represented with typed dates and status fields." },
      notes: "Learning lifecycle maps to courses and lessons, not commerce order lifecycle.",
    },
    actor_account: {
      fields: ["personId", "issuer", "provider"],
      requiredEntities: ["learner", "issuer", "courseProvider"],
      fieldMappings: [
        { collectionName: "survey_responses", fieldName: "personId" },
        { collectionName: "certifications_personal", fieldName: "issuer", aliasesReviewed: ["credentialIssuer"] },
        { collectionName: "courses", fieldName: "provider", aliasesReviewed: ["courseProvider"] },
      ],
      relationMappings: [{ collectionName: "survey_responses", fieldName: "personId", targetCollectionName: "analytics_persons", kind: "participant" }],
      jsonAudit: { status: "typed_fields_available", notes: "Learner participation and credential issuer names are typed." },
      notes: "Learning actors use learner/person and issuer/provider concepts rather than buyer/customer names.",
    },
    itemized_breakdown: {
      fields: ["position", "durationMinutes", "front", "back"],
      requiredEntities: ["course", "lesson", "card", "deck"],
      fieldMappings: [
        { collectionName: "lessons", fieldName: "position", aliasesReviewed: ["lessonOrder"] },
        { collectionName: "lessons", fieldName: "durationMinutes" },
        { collectionName: "flashcards", fieldName: "front", aliasesReviewed: ["prompt"] },
        { collectionName: "flashcards", fieldName: "back", aliasesReviewed: ["answer"] },
      ],
      relationMappings: [{ collectionName: "flashcards", fieldName: "deckId", targetCollectionName: "flashcard_decks", kind: "ownership" }],
      jsonAudit: { status: "typed_fields_available", notes: "Lesson order, duration, and flashcard prompt/answer are typed fields." },
      notes: "Learning child rows are ordered content items and cards rather than commercial line items.",
    },
    payment_settlement: {
      fields: ["verificationUrl", "credentialId", "document"],
      requiredEntities: ["credential", "document", "verification"],
      fieldMappings: [
        { collectionName: "certifications_personal", fieldName: "credentialId", aliasesReviewed: ["certificateNumber"] },
        { collectionName: "certifications_personal", fieldName: "verificationUrl" },
        { collectionName: "certifications_personal", fieldName: "document" },
      ],
      relationMappings: [{ collectionName: "lessons", fieldName: "courseId", targetCollectionName: "courses", kind: "ownership" }],
      jsonAudit: { status: "typed_fields_available", notes: "Learning credentials use typed verification fields; payment remains reusable billing catalog when needed." },
      notes: "Credential verification is the durable financial-adjacent entitlement shape for learning; billing remains a reusable cross-domain catalog.",
    },
    source_sync: {
      fields: ["provider", "url", "source"],
      requiredEntities: ["course", "source", "canonicalRecord"],
      fieldMappings: [
        { collectionName: "courses", fieldName: "provider" },
        { collectionName: "courses", fieldName: "url" },
        { collectionName: "survey_responses", fieldName: "source" },
      ],
      relationMappings: [{ collectionName: "survey_responses", fieldName: "surveyId", targetCollectionName: "surveys", kind: "observation_sample" }],
      jsonAudit: { status: "justified_extension", notes: "Survey response source metadata stays JSON while course provider and URL are typed." },
      notes: "Learning imports preserve course provider/url and survey provenance without provider-specific claims.",
    },
    supporting_document: {
      fields: ["document", "notes", "verificationUrl"],
      requiredEntities: ["credential", "document", "lesson"],
      fieldMappings: [
        { collectionName: "certifications_personal", fieldName: "document" },
        { collectionName: "certifications_personal", fieldName: "verificationUrl" },
        { collectionName: "lessons", fieldName: "notes" },
      ],
      relationMappings: [{ collectionName: "lessons", fieldName: "courseId", targetCollectionName: "courses", kind: "ownership" }],
      jsonAudit: { status: "typed_fields_available", notes: "Credential files and lesson notes are typed/file fields." },
      notes: "Learning evidence maps to credential files, verification URLs, and lesson notes.",
    },
    location_fulfillment: {
      fields: ["scheduledAt", "durationMinutes", "url"],
      requiredEntities: ["exam", "course", "session"],
      fieldMappings: [
        { collectionName: "exams", fieldName: "scheduledAt", aliasesReviewed: ["examScheduledAt"] },
        { collectionName: "exams", fieldName: "durationMinutes" },
        { collectionName: "courses", fieldName: "url" },
      ],
      relationMappings: [{ collectionName: "exams", fieldName: "subjectId", targetCollectionName: "subjects", kind: "ownership" }],
      jsonAudit: { status: "typed_fields_available", notes: "Learning location/fulfillment is usually a scheduled or URL-backed learning event." },
      notes: "Learning fulfillment maps to exam scheduling and course URLs rather than shipping addresses.",
    },
    scheduled_commitment: {
      fields: ["startedAt", "completedAt", "nextReviewAt", "reviewedAt"],
      requiredEntities: ["review", "course", "session"],
      fieldMappings: [
        { collectionName: "courses", fieldName: "startedAt" },
        { collectionName: "courses", fieldName: "completedAt" },
        { collectionName: "flashcards", fieldName: "nextReviewAt" },
        { collectionName: "flashcard_reviews", fieldName: "reviewedAt" },
      ],
      relationMappings: [{ collectionName: "flashcard_reviews", fieldName: "flashcardId", targetCollectionName: "flashcards", kind: "ownership" }],
      jsonAudit: { status: "typed_fields_available", notes: "Reviews and course dates use typed scheduling fields." },
      notes: "Learning commitments are study and review schedules.",
    },
    exception_resolution: {
      fields: ["status", "notes", "score", "maxScore"],
      requiredEntities: ["assessment", "result", "review"],
      fieldMappings: [
        { collectionName: "exams", fieldName: "status" },
        { collectionName: "exams", fieldName: "score" },
        { collectionName: "exams", fieldName: "maxScore" },
        { collectionName: "exams", fieldName: "notes" },
      ],
      relationMappings: [{ collectionName: "exams", fieldName: "subjectId", targetCollectionName: "subjects", kind: "ownership" }],
      jsonAudit: { status: "typed_fields_available", notes: "Assessment resolution uses typed score/status fields." },
      notes: "Learning exception/resolution is represented by assessment status, score, and notes.",
    },
    observation_metric: {
      fields: ["reviewedAt", "rating", "intervalDays", "masteryLevel"],
      requiredEntities: ["review", "skill", "sample"],
      fieldMappings: [
        { collectionName: "flashcard_reviews", fieldName: "reviewedAt" },
        { collectionName: "flashcard_reviews", fieldName: "rating" },
        { collectionName: "flashcard_reviews", fieldName: "intervalDays" },
        { collectionName: "vocabulary_items", fieldName: "masteryLevel" },
      ],
      relationMappings: [{ collectionName: "flashcard_reviews", fieldName: "flashcardId", targetCollectionName: "flashcards", kind: "ownership" }],
      jsonAudit: { status: "typed_fields_available", notes: "Review ratings, intervals, and mastery levels are typed." },
      notes: "Learning observations are review samples and progress metrics.",
    },
    dependency_approval: {
      fields: ["courseId", "position", "status"],
      requiredEntities: ["course", "lesson", "prerequisite"],
      fieldMappings: [
        { collectionName: "lessons", fieldName: "courseId" },
        { collectionName: "lessons", fieldName: "position" },
        { collectionName: "lessons", fieldName: "status" },
      ],
      relationMappings: [{ collectionName: "lessons", fieldName: "courseId", targetCollectionName: "courses", kind: "ownership" }],
      jsonAudit: { status: "typed_fields_available", notes: "Lesson sequence dependencies are represented by course relation and position." },
      structuralChange: "existing",
      notes: "Learning dependencies currently map to ordered course content; richer prerequisites remain a future additive candidate.",
    },
    custom_extension_boundary: {
      fields: ["tags", "answers", "notes"],
      requiredEntities: ["customLearningAttribute", "surveyAnswer", "canonicalRecord"],
      fieldMappings: [
        { collectionName: "flashcards", fieldName: "tags" },
        { collectionName: "survey_responses", fieldName: "answers" },
        { collectionName: "courses", fieldName: "notes" },
      ],
      relationMappings: [{ collectionName: "survey_responses", fieldName: "surveyId", targetCollectionName: "surveys", kind: "observation_sample" }],
      jsonAudit: { status: "justified_extension", notes: "Flashcard tags and survey answers vary by deck/survey schema and remain bounded JSON extensions." },
      structuralChange: "custom_database",
      coverageStatus: "custom_database",
      notes: "Learning-specific private attributes stay in bounded tags/answers or custom databases until generalized.",
    },
  },
  sports_booking_venues: {
    record_lifecycle: {
      fields: ["status", "startsAt", "endsAt", "notes"],
      requiredEntities: ["booking", "slot", "venue"],
      fieldMappings: [
        { collectionName: "bookings", fieldName: "status" },
        { collectionName: "bookings", fieldName: "startsAt", aliasesReviewed: ["bookingStartsAt"] },
        { collectionName: "bookings", fieldName: "endsAt", aliasesReviewed: ["bookingEndsAt"] },
        { collectionName: "bookings", fieldName: "notes" },
      ],
      relationMappings: [{ collectionName: "bookings", fieldName: "serviceListingId", targetCollectionName: "service_listings", kind: "membership" }],
      jsonAudit: { status: "typed_fields_available", notes: "Booking lifecycle is typed through status and time bounds." },
      notes: "Sports lifecycle maps to booking records and availability state, not commerce orders.",
    },
    actor_account: {
      fields: ["bookedByContactId", "bookedByEmail", "bookedByName", "guestName"],
      requiredEntities: ["participant", "coach", "guest"],
      fieldMappings: [
        { collectionName: "booking_slots", fieldName: "bookedByContactId" },
        { collectionName: "booking_slots", fieldName: "bookedByEmail", aliasesReviewed: ["participantEmail"] },
        { collectionName: "booking_slots", fieldName: "bookedByName", aliasesReviewed: ["participantName"] },
        { collectionName: "bookings", fieldName: "guestName" },
      ],
      relationMappings: [{ collectionName: "booking_slots", fieldName: "bookedByContactId", targetCollectionName: "contacts", kind: "participant" }],
      jsonAudit: { status: "typed_fields_available", notes: "Booked participant identity has typed contact, email, and name fields." },
      notes: "Sports actors are participants, coaches, guests, and members.",
    },
    itemized_breakdown: {
      fields: ["position", "sets", "reps", "weightKg", "durationSeconds"],
      requiredEntities: ["workout", "exercise", "set"],
      fieldMappings: [
        { collectionName: "workout_exercises", fieldName: "position", aliasesReviewed: ["exerciseOrder"] },
        { collectionName: "workout_exercises", fieldName: "sets" },
        { collectionName: "workout_exercises", fieldName: "reps" },
        { collectionName: "workout_exercises", fieldName: "weightKg" },
        { collectionName: "workout_exercises", fieldName: "durationSeconds" },
      ],
      relationMappings: [{ collectionName: "workout_exercises", fieldName: "workoutId", targetCollectionName: "workouts", kind: "ownership" }],
      jsonAudit: { status: "typed_fields_available", notes: "Exercise rows are typed child records instead of JSON exercise arrays." },
      notes: "Sports itemization maps to workout exercise rows and booking slots.",
    },
    payment_settlement: {
      fields: ["totalCents", "currency", "paid", "paymentIntentId"],
      requiredEntities: ["booking", "payment", "settlement"],
      fieldMappings: [
        { collectionName: "bookings", fieldName: "totalCents", aliasesReviewed: ["bookingTotalCents"] },
        { collectionName: "bookings", fieldName: "currency" },
        { collectionName: "booking_slots", fieldName: "paid" },
        { collectionName: "booking_slots", fieldName: "paymentIntentId" },
      ],
      relationMappings: [{ collectionName: "booking_slots", fieldName: "paymentIntentId", targetCollectionName: "payment_intents", kind: "financial_transaction" }],
      jsonAudit: { status: "typed_fields_available", notes: "Booking payment state and amount are typed; payment processing reuses the billing catalog." },
      notes: "Sports settlement uses booking amounts and canonical payment intent relations.",
    },
    source_sync: {
      fields: ["source", "links", "metadata"],
      requiredEntities: ["importedBooking", "canonicalBooking", "source"],
      fieldMappings: [
        { collectionName: "booking_slots", fieldName: "source" },
        { collectionName: "booking_slots", fieldName: "links" },
        { collectionName: "booking_slots", fieldName: "metadata" },
      ],
      relationMappings: [{ collectionName: "booking_slots", fieldName: "meetingTypeId", targetCollectionName: "booking_meeting_types", kind: "temporal_event" }],
      jsonAudit: { status: "justified_extension", notes: "Imported booking source metadata is bounded extension data while canonical slot fields stay typed." },
      coverageStatus: "custom_database",
      structuralChange: "custom_database",
      notes: "Provider-specific sports import ids remain custom database data until they generalize across booking domains.",
    },
    supporting_document: {
      fields: ["photoFinish", "notes", "meetingUrl"],
      requiredEntities: ["result", "asset", "booking"],
      fieldMappings: [
        { collectionName: "race_results", fieldName: "photoFinish" },
        { collectionName: "race_results", fieldName: "notes" },
        { collectionName: "booking_slots", fieldName: "meetingUrl" },
      ],
      relationMappings: [{ collectionName: "race_results", fieldName: "raceId", targetCollectionName: "races_registered", kind: "temporal_event" }],
      jsonAudit: { status: "typed_fields_available", notes: "Race result media and booking links use URL/text fields." },
      notes: "Sports evidence is represented by result media URLs, notes, and booking links.",
    },
    location_fulfillment: {
      fields: ["startsAt", "endsAt", "city", "country"],
      requiredEntities: ["venue", "slot", "place"],
      fieldMappings: [
        { collectionName: "availability_slots", fieldName: "startsAt" },
        { collectionName: "availability_slots", fieldName: "endsAt" },
        { collectionName: "places_visited", fieldName: "city" },
        { collectionName: "places_visited", fieldName: "country" },
      ],
      relationMappings: [{ collectionName: "availability_slots", fieldName: "serviceListingId", targetCollectionName: "service_listings", kind: "membership" }],
      jsonAudit: { status: "typed_fields_available", notes: "Venue and slot availability use typed place and time fields." },
      notes: "Sports fulfillment is place-and-slot availability.",
    },
    scheduled_commitment: {
      fields: ["startTime", "endTime", "status", "meetingTypeId"],
      requiredEntities: ["slot", "meetingType", "participant"],
      fieldMappings: [
        { collectionName: "booking_slots", fieldName: "startTime" },
        { collectionName: "booking_slots", fieldName: "endTime" },
        { collectionName: "booking_slots", fieldName: "status" },
        { collectionName: "booking_slots", fieldName: "meetingTypeId" },
      ],
      relationMappings: [{ collectionName: "booking_slots", fieldName: "meetingTypeId", targetCollectionName: "booking_meeting_types", kind: "temporal_event" }],
      jsonAudit: { status: "typed_fields_available", notes: "Booking commitments use typed calendar slot fields." },
      notes: "Sports commitments are schedule-first records.",
    },
    exception_resolution: {
      fields: ["blocked", "notes", "status"],
      requiredEntities: ["availability", "booking", "resolution"],
      fieldMappings: [
        { collectionName: "availability_slots", fieldName: "blocked" },
        { collectionName: "availability_slots", fieldName: "notes" },
        { collectionName: "bookings", fieldName: "status" },
      ],
      relationMappings: [{ collectionName: "bookings", fieldName: "serviceListingId", targetCollectionName: "service_listings", kind: "membership" }],
      jsonAudit: { status: "typed_fields_available", notes: "Booking exceptions use typed blocked/status fields and notes." },
      notes: "Sports exception workflows include blocked slots, cancellations, and booking status.",
    },
    observation_metric: {
      fields: ["value", "unit", "achievedAt", "timeSeconds", "positionOverall"],
      requiredEntities: ["result", "record", "measurement"],
      fieldMappings: [
        { collectionName: "personal_records", fieldName: "value", aliasesReviewed: ["recordValue"] },
        { collectionName: "personal_records", fieldName: "unit" },
        { collectionName: "personal_records", fieldName: "achievedAt" },
        { collectionName: "race_results", fieldName: "timeSeconds" },
        { collectionName: "race_results", fieldName: "positionOverall" },
      ],
      relationMappings: [{ collectionName: "race_results", fieldName: "raceId", targetCollectionName: "races_registered", kind: "temporal_event" }],
      jsonAudit: { status: "typed_fields_available", notes: "Sports outcomes use typed measurement and result fields." },
      notes: "Sports observations are performance records and race results.",
    },
    dependency_approval: {
      fields: ["teamId", "actorId", "role", "joinedAt"],
      requiredEntities: ["member", "team", "eligibility"],
      fieldMappings: [
        { collectionName: "team_memberships", fieldName: "teamId" },
        { collectionName: "team_memberships", fieldName: "actorId" },
        { collectionName: "team_memberships", fieldName: "role" },
        { collectionName: "team_memberships", fieldName: "joinedAt" },
      ],
      relationMappings: [{ collectionName: "team_memberships", fieldName: "teamId", targetCollectionName: "teams", kind: "membership" }],
      jsonAudit: { status: "typed_fields_available", notes: "Roster eligibility and membership are typed relation records." },
      notes: "Sports dependencies commonly flow through memberships, rosters, and access eligibility.",
    },
    custom_extension_boundary: {
      fields: ["source", "links", "metadata", "notes"],
      requiredEntities: ["customSportRule", "canonicalRecord"],
      fieldMappings: [
        { collectionName: "booking_slots", fieldName: "source" },
        { collectionName: "booking_slots", fieldName: "links" },
        { collectionName: "booking_slots", fieldName: "metadata" },
        { collectionName: "workouts", fieldName: "notes" },
      ],
      relationMappings: [{ collectionName: "booking_slots", fieldName: "meetingTypeId", targetCollectionName: "booking_meeting_types", kind: "temporal_event" }],
      jsonAudit: { status: "justified_extension", notes: "Sport-specific rules and imported metadata remain bounded extensions unless they recur across domains." },
      structuralChange: "custom_database",
      coverageStatus: "custom_database",
      notes: "Custom databases remain valid for league-specific rules, waiver payloads, and venue-specific metadata.",
    },
  },
  health_fitness_care: {
    record_lifecycle: {
      fields: ["name", "status", "diagnosedAt", "notes"],
      requiredEntities: ["patient", "condition", "careRecord"],
      fieldMappings: [
        { collectionName: "health_conditions", fieldName: "name", aliasesReviewed: ["conditionName"] },
        { collectionName: "health_conditions", fieldName: "status" },
        { collectionName: "health_conditions", fieldName: "diagnosedAt" },
        { collectionName: "health_conditions", fieldName: "notes" },
      ],
      relationMappings: [{ collectionName: "diagnoses", fieldName: "doctorId", targetCollectionName: "doctors", kind: "participant" }],
      jsonAudit: { status: "typed_fields_available", notes: "Condition lifecycle and diagnosis context are typed." },
      notes: "Health lifecycle maps to condition and diagnosis records.",
    },
    actor_account: {
      fields: ["doctorId", "clinicId", "name", "email"],
      requiredEntities: ["patient", "clinician", "clinic"],
      fieldMappings: [
        { collectionName: "medical_appointments", fieldName: "doctorId" },
        { collectionName: "medical_appointments", fieldName: "clinicId" },
        { collectionName: "doctors", fieldName: "name", aliasesReviewed: ["clinicianName"] },
        { collectionName: "doctors", fieldName: "email" },
      ],
      relationMappings: [{ collectionName: "medical_appointments", fieldName: "doctorId", targetCollectionName: "doctors", kind: "participant" }],
      jsonAudit: { status: "typed_fields_available", notes: "Care actors are represented with clinician and clinic relations." },
      notes: "Health actors are clinicians, caregivers, and care locations rather than commercial accounts.",
    },
    itemized_breakdown: {
      fields: ["takenAt", "amount", "unit", "skipped"],
      requiredEntities: ["medication", "dose", "doseSchedule"],
      fieldMappings: [
        { collectionName: "medication_doses", fieldName: "takenAt" },
        { collectionName: "medication_doses", fieldName: "amount", aliasesReviewed: ["doseAmount"] },
        { collectionName: "medication_doses", fieldName: "unit", aliasesReviewed: ["doseUnit"] },
        { collectionName: "medication_doses", fieldName: "skipped" },
      ],
      relationMappings: [{ collectionName: "medication_doses", fieldName: "medicationId", targetCollectionName: "medications", kind: "ownership" }],
      jsonAudit: { status: "typed_fields_available", notes: "Medication dose rows use typed amount/unit/taken fields." },
      notes: "Health itemization maps to dose administrations and care tasks.",
    },
    payment_settlement: {
      fields: ["cost", "scheduledAt", "modality"],
      requiredEntities: ["session", "provider", "cost"],
      fieldMappings: [
        { collectionName: "therapy_sessions", fieldName: "cost", aliasesReviewed: ["sessionCost"] },
        { collectionName: "therapy_sessions", fieldName: "scheduledAt" },
        { collectionName: "therapy_sessions", fieldName: "modality" },
      ],
      relationMappings: [{ collectionName: "therapy_sessions", fieldName: "therapistId", targetCollectionName: "therapists", kind: "participant" }],
      jsonAudit: { status: "typed_fields_available", notes: "Care session cost is typed as money; settlement can reuse billing when needed." },
      notes: "Health payment-like needs map to care session cost and provider participation.",
    },
    source_sync: {
      fields: ["values", "document", "reportedAt"],
      requiredEntities: ["labResult", "sourceDocument", "canonicalRecord"],
      fieldMappings: [
        { collectionName: "lab_results", fieldName: "values" },
        { collectionName: "lab_results", fieldName: "document" },
        { collectionName: "lab_results", fieldName: "reportedAt" },
      ],
      relationMappings: [{ collectionName: "lab_results", fieldName: "doctorId", targetCollectionName: "doctors", kind: "participant" }],
      jsonAudit: { status: "justified_extension", notes: "Lab values remain JSON because individual panels vary by test definition; document and report dates are typed." },
      coverageStatus: "custom_database",
      structuralChange: "custom_database",
      notes: "Provider-specific lab import payloads remain custom database data while canonical lab result fields stay portable.",
    },
    supporting_document: {
      fields: ["title", "kind", "documentDate", "file"],
      requiredEntities: ["medicalDocument", "clinician", "file"],
      fieldMappings: [
        { collectionName: "medical_documents", fieldName: "title" },
        { collectionName: "medical_documents", fieldName: "kind" },
        { collectionName: "medical_documents", fieldName: "documentDate" },
        { collectionName: "medical_documents", fieldName: "file" },
      ],
      relationMappings: [{ collectionName: "medical_documents", fieldName: "doctorId", targetCollectionName: "doctors", kind: "participant" }],
      jsonAudit: { status: "typed_fields_available", notes: "Medical documents use typed kind/date/file fields." },
      notes: "Health evidence is file-backed and related to clinicians where appropriate.",
    },
    location_fulfillment: {
      fields: ["clinicId", "scheduledAt", "address", "city"],
      requiredEntities: ["appointment", "clinic", "place"],
      fieldMappings: [
        { collectionName: "medical_appointments", fieldName: "clinicId" },
        { collectionName: "medical_appointments", fieldName: "scheduledAt" },
        { collectionName: "clinics", fieldName: "address" },
        { collectionName: "clinics", fieldName: "city" },
      ],
      relationMappings: [{ collectionName: "medical_appointments", fieldName: "clinicId", targetCollectionName: "clinics", kind: "location" }],
      jsonAudit: { status: "typed_fields_available", notes: "Care locations use clinic relations and typed address fields." },
      notes: "Health fulfillment happens at clinics, appointments, and care locations.",
    },
    scheduled_commitment: {
      fields: ["scheduledAt", "status", "reason"],
      requiredEntities: ["appointment", "clinician", "patient"],
      fieldMappings: [
        { collectionName: "medical_appointments", fieldName: "scheduledAt", aliasesReviewed: ["appointmentScheduledAt"] },
        { collectionName: "medical_appointments", fieldName: "status" },
        { collectionName: "medical_appointments", fieldName: "reason" },
      ],
      relationMappings: [{ collectionName: "medical_appointments", fieldName: "doctorId", targetCollectionName: "doctors", kind: "participant" }],
      jsonAudit: { status: "typed_fields_available", notes: "Appointments use typed scheduled/status/reason fields." },
      notes: "Health commitments are appointments, doses, and therapy sessions.",
    },
    exception_resolution: {
      fields: ["title", "status", "description", "notes"],
      requiredEntities: ["diagnosis", "careException", "resolution"],
      fieldMappings: [
        { collectionName: "diagnoses", fieldName: "title" },
        { collectionName: "diagnoses", fieldName: "status" },
        { collectionName: "diagnoses", fieldName: "description" },
        { collectionName: "diagnoses", fieldName: "notes" },
      ],
      relationMappings: [{ collectionName: "diagnoses", fieldName: "doctorId", targetCollectionName: "doctors", kind: "participant" }],
      jsonAudit: { status: "typed_fields_available", notes: "Care exception state is represented by diagnosis status and notes." },
      notes: "Health resolution maps to diagnosis state and clinician context.",
    },
    observation_metric: {
      fields: ["loggedAt", "symptom", "severity", "values", "reportedAt"],
      requiredEntities: ["sample", "symptom", "labResult"],
      fieldMappings: [
        { collectionName: "symptom_logs", fieldName: "loggedAt" },
        { collectionName: "symptom_logs", fieldName: "symptom" },
        { collectionName: "symptom_logs", fieldName: "severity" },
        { collectionName: "lab_results", fieldName: "values" },
        { collectionName: "lab_results", fieldName: "reportedAt" },
      ],
      relationMappings: [{ collectionName: "lab_results", fieldName: "doctorId", targetCollectionName: "doctors", kind: "participant" }],
      jsonAudit: { status: "justified_extension", notes: "Symptom fields are typed; lab panel values remain JSON because panels differ by test." },
      notes: "Health observations are symptom logs, mood logs, measurements, and lab results.",
    },
    dependency_approval: {
      fields: ["doctorId", "clinicId", "status", "notes"],
      requiredEntities: ["careDependency", "clinician", "appointment"],
      fieldMappings: [
        { collectionName: "medical_appointments", fieldName: "doctorId" },
        { collectionName: "medical_appointments", fieldName: "clinicId" },
        { collectionName: "medical_appointments", fieldName: "status" },
        { collectionName: "medical_appointments", fieldName: "notes" },
      ],
      relationMappings: [{ collectionName: "medical_appointments", fieldName: "clinicId", targetCollectionName: "clinics", kind: "location" }],
      jsonAudit: { status: "typed_fields_available", notes: "Care dependencies are represented by appointment state and clinician/location relations." },
      notes: "Health dependencies commonly flow through appointments, clinician availability, and care location.",
    },
    custom_extension_boundary: {
      fields: ["tags", "values", "notesBody", "notes"],
      requiredEntities: ["customHealthAttribute", "panelValue", "canonicalRecord"],
      fieldMappings: [
        { collectionName: "symptom_logs", fieldName: "tags" },
        { collectionName: "lab_results", fieldName: "values" },
        { collectionName: "therapy_sessions", fieldName: "notesBody" },
        { collectionName: "health_conditions", fieldName: "notes" },
      ],
      relationMappings: [{ collectionName: "therapy_sessions", fieldName: "therapistId", targetCollectionName: "therapists", kind: "participant" }],
      jsonAudit: { status: "justified_extension", notes: "Health tags, lab values, and therapy notes remain bounded extensions where schemas are inherently variable." },
      structuralChange: "custom_database",
      coverageStatus: "custom_database",
      notes: "Custom databases remain valid for device-specific samples, institution-specific forms, and private care plan fields.",
    },
  },
};
