import type { BuiltinRelationKind } from "./builtins/_types.ts";
import type {
  CatalogAuditStructuralChange,
  CatalogAuditedFieldMapping,
  CatalogAuditedNeed,
  CatalogAuditedRelationMapping,
  CatalogCoverageStatus,
} from "./catalog-coverage.ts";

type AuditedNeedTemplateOverride = Partial<{
  fields: string[];
  requiredEntities: string[];
  relationKind: BuiltinRelationKind;
  fieldMappings: CatalogAuditedFieldMapping[];
  relationMappings: CatalogAuditedRelationMapping[];
  jsonAudit: CatalogAuditedNeed["jsonAudit"];
  structuralChange: CatalogAuditStructuralChange;
  coverageStatus: CatalogCoverageStatus;
  notes: string;
}>;

export const AUDITED_NEED_TEMPLATE_OVERRIDES: Record<string, Record<string, AuditedNeedTemplateOverride>> = {
  learning_assessment: {
    record_lifecycle: {
      fields: ["title", "status", "startedAt", "completedAt"],
      requiredEntities: ["learner", "course", "lesson"],
      fieldMappings: [
        { collectionName: "courses", fieldName: "title", aliasesReviewed: ["courseTitle"] },
        { collectionName: "courses", fieldName: "status" },
        { collectionName: "courses", fieldName: "startedAt" },
        { collectionName: "courses", fieldName: "completedAt" },
      ],
      relationMappings: [{ collectionName: "lessons", fieldName: "courseId", targetCollectionName: "courses", kind: "ownership" }],
      jsonAudit: { status: "typed_fields_available", notes: "Course lifecycle state is represented with typed dates and status fields." },
      notes: "Learning lifecycle maps to courses and lessons, not commerce order lifecycle.",
    },
    actor_account: {
      fields: ["personId", "issuer", "provider"],
      requiredEntities: ["learner", "issuer", "courseProvider"],
      fieldMappings: [
        { collectionName: "survey_responses", fieldName: "personId" },
        { collectionName: "certifications_personal", fieldName: "issuer", aliasesReviewed: ["credentialIssuer"] },
        { collectionName: "courses", fieldName: "provider", aliasesReviewed: ["courseProvider"] },
      ],
      relationMappings: [{ collectionName: "survey_responses", fieldName: "personId", targetCollectionName: "analytics_persons", kind: "participant" }],
      jsonAudit: { status: "typed_fields_available", notes: "Learner participation and credential issuer names are typed." },
      notes: "Learning actors use learner/person and issuer/provider concepts rather than buyer/customer names.",
    },
    itemized_breakdown: {
      fields: ["position", "durationMinutes", "front", "back"],
      requiredEntities: ["course", "lesson", "card", "deck"],
      fieldMappings: [
        { collectionName: "lessons", fieldName: "position", aliasesReviewed: ["lessonOrder"] },
        { collectionName: "lessons", fieldName: "durationMinutes" },
        { collectionName: "flashcards", fieldName: "front", aliasesReviewed: ["prompt"] },
        { collectionName: "flashcards", fieldName: "back", aliasesReviewed: ["answer"] },
      ],
      relationMappings: [{ collectionName: "flashcards", fieldName: "deckId", targetCollectionName: "flashcard_decks", kind: "ownership" }],
      jsonAudit: { status: "typed_fields_available", notes: "Lesson order, duration, and flashcard prompt/answer are typed fields." },
      notes: "Learning child rows are ordered content items and cards rather than commercial line items.",
    },
    payment_settlement: {
      fields: ["verificationUrl", "credentialId", "document"],
      requiredEntities: ["credential", "document", "verification"],
      fieldMappings: [
        { collectionName: "certifications_personal", fieldName: "credentialId", aliasesReviewed: ["certificateNumber"] },
        { collectionName: "certifications_personal", fieldName: "verificationUrl" },
        { collectionName: "certifications_personal", fieldName: "document" },
      ],
      relationMappings: [{ collectionName: "lessons", fieldName: "courseId", targetCollectionName: "courses", kind: "ownership" }],
      jsonAudit: { status: "typed_fields_available", notes: "Learning credentials use typed verification fields; payment remains reusable billing catalog when needed." },
      notes: "Credential verification is the durable financial-adjacent entitlement shape for learning; billing remains a reusable cross-domain catalog.",
    },
    source_sync: {
      fields: ["provider", "url", "source"],
      requiredEntities: ["course", "source", "canonicalRecord"],
      fieldMappings: [
        { collectionName: "courses", fieldName: "provider" },
        { collectionName: "courses", fieldName: "url" },
        { collectionName: "survey_responses", fieldName: "source" },
      ],
      relationMappings: [{ collectionName: "survey_responses", fieldName: "surveyId", targetCollectionName: "surveys", kind: "observation_sample" }],
      jsonAudit: { status: "justified_extension", notes: "Survey response source metadata stays JSON while course provider and URL are typed." },
      notes: "Learning imports preserve course provider/url and survey provenance without provider-specific claims.",
    },
    supporting_document: {
      fields: ["document", "notes", "verificationUrl"],
      requiredEntities: ["credential", "document", "lesson"],
      fieldMappings: [
        { collectionName: "certifications_personal", fieldName: "document" },
        { collectionName: "certifications_personal", fieldName: "verificationUrl" },
        { collectionName: "lessons", fieldName: "notes" },
      ],
      relationMappings: [{ collectionName: "lessons", fieldName: "courseId", targetCollectionName: "courses", kind: "ownership" }],
      jsonAudit: { status: "typed_fields_available", notes: "Credential files and lesson notes are typed/file fields." },
      notes: "Learning evidence maps to credential files, verification URLs, and lesson notes.",
    },
    location_fulfillment: {
      fields: ["scheduledAt", "durationMinutes", "url"],
      requiredEntities: ["exam", "course", "session"],
      fieldMappings: [
        { collectionName: "exams", fieldName: "scheduledAt", aliasesReviewed: ["examScheduledAt"] },
        { collectionName: "exams", fieldName: "durationMinutes" },
        { collectionName: "courses", fieldName: "url" },
      ],
      relationMappings: [{ collectionName: "exams", fieldName: "subjectId", targetCollectionName: "subjects", kind: "ownership" }],
      jsonAudit: { status: "typed_fields_available", notes: "Learning location/fulfillment is usually a scheduled or URL-backed learning event." },
      notes: "Learning fulfillment maps to exam scheduling and course URLs rather than shipping addresses.",
    },
    scheduled_commitment: {
      fields: ["startedAt", "completedAt", "nextReviewAt", "reviewedAt"],
      requiredEntities: ["review", "course", "session"],
      fieldMappings: [
        { collectionName: "courses", fieldName: "startedAt" },
        { collectionName: "courses", fieldName: "completedAt" },
        { collectionName: "flashcards", fieldName: "nextReviewAt" },
        { collectionName: "flashcard_reviews", fieldName: "reviewedAt" },
      ],
      relationMappings: [{ collectionName: "flashcard_reviews", fieldName: "flashcardId", targetCollectionName: "flashcards", kind: "ownership" }],
      jsonAudit: { status: "typed_fields_available", notes: "Reviews and course dates use typed scheduling fields." },
      notes: "Learning commitments are study and review schedules.",
    },
    exception_resolution: {
      fields: ["status", "notes", "score", "maxScore"],
      requiredEntities: ["assessment", "result", "review"],
      fieldMappings: [
        { collectionName: "exams", fieldName: "status" },
        { collectionName: "exams", fieldName: "score" },
        { collectionName: "exams", fieldName: "maxScore" },
        { collectionName: "exams", fieldName: "notes" },
      ],
      relationMappings: [{ collectionName: "exams", fieldName: "subjectId", targetCollectionName: "subjects", kind: "ownership" }],
      jsonAudit: { status: "typed_fields_available", notes: "Assessment resolution uses typed score/status fields." },
      notes: "Learning exception/resolution is represented by assessment status, score, and notes.",
    },
    observation_metric: {
      fields: ["reviewedAt", "rating", "intervalDays", "masteryLevel"],
      requiredEntities: ["review", "skill", "sample"],
      fieldMappings: [
        { collectionName: "flashcard_reviews", fieldName: "reviewedAt" },
        { collectionName: "flashcard_reviews", fieldName: "rating" },
        { collectionName: "flashcard_reviews", fieldName: "intervalDays" },
        { collectionName: "vocabulary_items", fieldName: "masteryLevel" },
      ],
      relationMappings: [{ collectionName: "flashcard_reviews", fieldName: "flashcardId", targetCollectionName: "flashcards", kind: "ownership" }],
      jsonAudit: { status: "typed_fields_available", notes: "Review ratings, intervals, and mastery levels are typed." },
      notes: "Learning observations are review samples and progress metrics.",
    },
    dependency_approval: {
      fields: ["courseId", "position", "status"],
      requiredEntities: ["course", "lesson", "prerequisite"],
      fieldMappings: [
        { collectionName: "lessons", fieldName: "courseId" },
        { collectionName: "lessons", fieldName: "position" },
        { collectionName: "lessons", fieldName: "status" },
      ],
      relationMappings: [{ collectionName: "lessons", fieldName: "courseId", targetCollectionName: "courses", kind: "ownership" }],
      jsonAudit: { status: "typed_fields_available", notes: "Lesson sequence dependencies are represented by course relation and position." },
      structuralChange: "existing",
      notes: "Learning dependencies currently map to ordered course content; richer prerequisites remain a future additive candidate.",
    },
    custom_extension_boundary: {
      fields: ["tags", "answers", "notes"],
      requiredEntities: ["customLearningAttribute", "surveyAnswer", "canonicalRecord"],
      fieldMappings: [
        { collectionName: "flashcards", fieldName: "tags" },
        { collectionName: "survey_responses", fieldName: "answers" },
        { collectionName: "courses", fieldName: "notes" },
      ],
      relationMappings: [{ collectionName: "survey_responses", fieldName: "surveyId", targetCollectionName: "surveys", kind: "observation_sample" }],
      jsonAudit: { status: "justified_extension", notes: "Flashcard tags and survey answers vary by deck/survey schema and remain bounded JSON extensions." },
      structuralChange: "custom_database",
      coverageStatus: "custom_database",
      notes: "Learning-specific private attributes stay in bounded tags/answers or custom databases until generalized.",
    },
  },
  sports_booking_venues: {
    record_lifecycle: {
      fields: ["status", "startsAt", "endsAt", "notes"],
      requiredEntities: ["booking", "slot", "venue"],
      fieldMappings: [
        { collectionName: "bookings", fieldName: "status" },
        { collectionName: "bookings", fieldName: "startsAt", aliasesReviewed: ["bookingStartsAt"] },
        { collectionName: "bookings", fieldName: "endsAt", aliasesReviewed: ["bookingEndsAt"] },
        { collectionName: "bookings", fieldName: "notes" },
      ],
      relationMappings: [{ collectionName: "bookings", fieldName: "serviceListingId", targetCollectionName: "service_listings", kind: "membership" }],
      jsonAudit: { status: "typed_fields_available", notes: "Booking lifecycle is typed through status and time bounds." },
      notes: "Sports lifecycle maps to booking records and availability state, not commerce orders.",
    },
    actor_account: {
      fields: ["bookedByContactId", "bookedByEmail", "bookedByName", "guestName"],
      requiredEntities: ["participant", "coach", "guest"],
      fieldMappings: [
        { collectionName: "booking_slots", fieldName: "bookedByContactId" },
        { collectionName: "booking_slots", fieldName: "bookedByEmail", aliasesReviewed: ["participantEmail"] },
        { collectionName: "booking_slots", fieldName: "bookedByName", aliasesReviewed: ["participantName"] },
        { collectionName: "bookings", fieldName: "guestName" },
      ],
      relationMappings: [{ collectionName: "booking_slots", fieldName: "bookedByContactId", targetCollectionName: "contacts", kind: "participant" }],
      jsonAudit: { status: "typed_fields_available", notes: "Booked participant identity has typed contact, email, and name fields." },
      notes: "Sports actors are participants, coaches, guests, and members.",
    },
    itemized_breakdown: {
      fields: ["position", "sets", "reps", "weightKg", "durationSeconds"],
      requiredEntities: ["workout", "exercise", "set"],
      fieldMappings: [
        { collectionName: "workout_exercises", fieldName: "position", aliasesReviewed: ["exerciseOrder"] },
        { collectionName: "workout_exercises", fieldName: "sets" },
        { collectionName: "workout_exercises", fieldName: "reps" },
        { collectionName: "workout_exercises", fieldName: "weightKg" },
        { collectionName: "workout_exercises", fieldName: "durationSeconds" },
      ],
      relationMappings: [{ collectionName: "workout_exercises", fieldName: "workoutId", targetCollectionName: "workouts", kind: "ownership" }],
      jsonAudit: { status: "typed_fields_available", notes: "Exercise rows are typed child records instead of JSON exercise arrays." },
      notes: "Sports itemization maps to workout exercise rows and booking slots.",
    },
    payment_settlement: {
      fields: ["totalCents", "currency", "paid", "paymentIntentId"],
      requiredEntities: ["booking", "payment", "settlement"],
      fieldMappings: [
        { collectionName: "bookings", fieldName: "totalCents", aliasesReviewed: ["bookingTotalCents"] },
        { collectionName: "bookings", fieldName: "currency" },
        { collectionName: "booking_slots", fieldName: "paid" },
        { collectionName: "booking_slots", fieldName: "paymentIntentId" },
      ],
      relationMappings: [{ collectionName: "booking_slots", fieldName: "paymentIntentId", targetCollectionName: "payment_intents", kind: "financial_transaction" }],
      jsonAudit: { status: "typed_fields_available", notes: "Booking payment state and amount are typed; payment processing reuses the billing catalog." },
      notes: "Sports settlement uses booking amounts and canonical payment intent relations.",
    },
    source_sync: {
      fields: ["source", "links", "metadata"],
      requiredEntities: ["importedBooking", "canonicalBooking", "source"],
      fieldMappings: [
        { collectionName: "booking_slots", fieldName: "source" },
        { collectionName: "booking_slots", fieldName: "links" },
        { collectionName: "booking_slots", fieldName: "metadata" },
      ],
      relationMappings: [{ collectionName: "booking_slots", fieldName: "meetingTypeId", targetCollectionName: "booking_meeting_types", kind: "temporal_event" }],
      jsonAudit: { status: "justified_extension", notes: "Imported booking source metadata is bounded extension data while canonical slot fields stay typed." },
      coverageStatus: "custom_database",
      structuralChange: "custom_database",
      notes: "Provider-specific sports import ids remain custom database data until they generalize across booking domains.",
    },
    supporting_document: {
      fields: ["photoFinish", "notes", "meetingUrl"],
      requiredEntities: ["result", "asset", "booking"],
      fieldMappings: [
        { collectionName: "race_results", fieldName: "photoFinish" },
        { collectionName: "race_results", fieldName: "notes" },
        { collectionName: "booking_slots", fieldName: "meetingUrl" },
      ],
      relationMappings: [{ collectionName: "race_results", fieldName: "raceId", targetCollectionName: "races_registered", kind: "temporal_event" }],
      jsonAudit: { status: "typed_fields_available", notes: "Race result media and booking links use URL/text fields." },
      notes: "Sports evidence is represented by result media URLs, notes, and booking links.",
    },
    location_fulfillment: {
      fields: ["startsAt", "endsAt", "city", "country"],
      requiredEntities: ["venue", "slot", "place"],
      fieldMappings: [
        { collectionName: "availability_slots", fieldName: "startsAt" },
        { collectionName: "availability_slots", fieldName: "endsAt" },
        { collectionName: "places_visited", fieldName: "city" },
        { collectionName: "places_visited", fieldName: "country" },
      ],
      relationMappings: [{ collectionName: "availability_slots", fieldName: "serviceListingId", targetCollectionName: "service_listings", kind: "membership" }],
      jsonAudit: { status: "typed_fields_available", notes: "Venue and slot availability use typed place and time fields." },
      notes: "Sports fulfillment is place-and-slot availability.",
    },
    scheduled_commitment: {
      fields: ["startTime", "endTime", "status", "meetingTypeId"],
      requiredEntities: ["slot", "meetingType", "participant"],
      fieldMappings: [
        { collectionName: "booking_slots", fieldName: "startTime" },
        { collectionName: "booking_slots", fieldName: "endTime" },
        { collectionName: "booking_slots", fieldName: "status" },
        { collectionName: "booking_slots", fieldName: "meetingTypeId" },
      ],
      relationMappings: [{ collectionName: "booking_slots", fieldName: "meetingTypeId", targetCollectionName: "booking_meeting_types", kind: "temporal_event" }],
      jsonAudit: { status: "typed_fields_available", notes: "Booking commitments use typed calendar slot fields." },
      notes: "Sports commitments are schedule-first records.",
    },
    exception_resolution: {
      fields: ["blocked", "notes", "status"],
      requiredEntities: ["availability", "booking", "resolution"],
      fieldMappings: [
        { collectionName: "availability_slots", fieldName: "blocked" },
        { collectionName: "availability_slots", fieldName: "notes" },
        { collectionName: "bookings", fieldName: "status" },
      ],
      relationMappings: [{ collectionName: "bookings", fieldName: "serviceListingId", targetCollectionName: "service_listings", kind: "membership" }],
      jsonAudit: { status: "typed_fields_available", notes: "Booking exceptions use typed blocked/status fields and notes." },
      notes: "Sports exception workflows include blocked slots, cancellations, and booking status.",
    },
    observation_metric: {
      fields: ["value", "unit", "achievedAt", "timeSeconds", "positionOverall"],
      requiredEntities: ["result", "record", "measurement"],
      fieldMappings: [
        { collectionName: "personal_records", fieldName: "value", aliasesReviewed: ["recordValue"] },
        { collectionName: "personal_records", fieldName: "unit" },
        { collectionName: "personal_records", fieldName: "achievedAt" },
        { collectionName: "race_results", fieldName: "timeSeconds" },
        { collectionName: "race_results", fieldName: "positionOverall" },
      ],
      relationMappings: [{ collectionName: "race_results", fieldName: "raceId", targetCollectionName: "races_registered", kind: "temporal_event" }],
      jsonAudit: { status: "typed_fields_available", notes: "Sports outcomes use typed measurement and result fields." },
      notes: "Sports observations are performance records and race results.",
    },
    dependency_approval: {
      fields: ["teamId", "actorId", "role", "joinedAt"],
      requiredEntities: ["member", "team", "eligibility"],
      fieldMappings: [
        { collectionName: "team_memberships", fieldName: "teamId" },
        { collectionName: "team_memberships", fieldName: "actorId" },
        { collectionName: "team_memberships", fieldName: "role" },
        { collectionName: "team_memberships", fieldName: "joinedAt" },
      ],
      relationMappings: [{ collectionName: "team_memberships", fieldName: "teamId", targetCollectionName: "teams", kind: "membership" }],
      jsonAudit: { status: "typed_fields_available", notes: "Roster eligibility and membership are typed relation records." },
      notes: "Sports dependencies commonly flow through memberships, rosters, and access eligibility.",
    },
    custom_extension_boundary: {
      fields: ["source", "links", "metadata", "notes"],
      requiredEntities: ["customSportRule", "canonicalRecord"],
      fieldMappings: [
        { collectionName: "booking_slots", fieldName: "source" },
        { collectionName: "booking_slots", fieldName: "links" },
        { collectionName: "booking_slots", fieldName: "metadata" },
        { collectionName: "workouts", fieldName: "notes" },
      ],
      relationMappings: [{ collectionName: "booking_slots", fieldName: "meetingTypeId", targetCollectionName: "booking_meeting_types", kind: "temporal_event" }],
      jsonAudit: { status: "justified_extension", notes: "Sport-specific rules and imported metadata remain bounded extensions unless they recur across domains." },
      structuralChange: "custom_database",
      coverageStatus: "custom_database",
      notes: "Custom databases remain valid for league-specific rules, waiver payloads, and venue-specific metadata.",
    },
  },
  health_fitness_care: {
    record_lifecycle: {
      fields: ["name", "status", "diagnosedAt", "notes"],
      requiredEntities: ["patient", "condition", "careRecord"],
      fieldMappings: [
        { collectionName: "health_conditions", fieldName: "name", aliasesReviewed: ["conditionName"] },
        { collectionName: "health_conditions", fieldName: "status" },
        { collectionName: "health_conditions", fieldName: "diagnosedAt" },
        { collectionName: "health_conditions", fieldName: "notes" },
      ],
      relationMappings: [{ collectionName: "diagnoses", fieldName: "doctorId", targetCollectionName: "doctors", kind: "participant" }],
      jsonAudit: { status: "typed_fields_available", notes: "Condition lifecycle and diagnosis context are typed." },
      notes: "Health lifecycle maps to condition and diagnosis records.",
    },
    actor_account: {
      fields: ["doctorId", "clinicId", "name", "email"],
      requiredEntities: ["patient", "clinician", "clinic"],
      fieldMappings: [
        { collectionName: "medical_appointments", fieldName: "doctorId" },
        { collectionName: "medical_appointments", fieldName: "clinicId" },
        { collectionName: "doctors", fieldName: "name", aliasesReviewed: ["clinicianName"] },
        { collectionName: "doctors", fieldName: "email" },
      ],
      relationMappings: [{ collectionName: "medical_appointments", fieldName: "doctorId", targetCollectionName: "doctors", kind: "participant" }],
      jsonAudit: { status: "typed_fields_available", notes: "Care actors are represented with clinician and clinic relations." },
      notes: "Health actors are clinicians, caregivers, and care locations rather than commercial accounts.",
    },
    itemized_breakdown: {
      fields: ["takenAt", "amount", "unit", "skipped"],
      requiredEntities: ["medication", "dose", "doseSchedule"],
      fieldMappings: [
        { collectionName: "medication_doses", fieldName: "takenAt" },
        { collectionName: "medication_doses", fieldName: "amount", aliasesReviewed: ["doseAmount"] },
        { collectionName: "medication_doses", fieldName: "unit", aliasesReviewed: ["doseUnit"] },
        { collectionName: "medication_doses", fieldName: "skipped" },
      ],
      relationMappings: [{ collectionName: "medication_doses", fieldName: "medicationId", targetCollectionName: "medications", kind: "ownership" }],
      jsonAudit: { status: "typed_fields_available", notes: "Medication dose rows use typed amount/unit/taken fields." },
      notes: "Health itemization maps to dose administrations and care tasks.",
    },
    payment_settlement: {
      fields: ["cost", "scheduledAt", "modality"],
      requiredEntities: ["session", "provider", "cost"],
      fieldMappings: [
        { collectionName: "therapy_sessions", fieldName: "cost", aliasesReviewed: ["sessionCost"] },
        { collectionName: "therapy_sessions", fieldName: "scheduledAt" },
        { collectionName: "therapy_sessions", fieldName: "modality" },
      ],
      relationMappings: [{ collectionName: "therapy_sessions", fieldName: "therapistId", targetCollectionName: "therapists", kind: "participant" }],
      jsonAudit: { status: "typed_fields_available", notes: "Care session cost is typed as money; settlement can reuse billing when needed." },
      notes: "Health payment-like needs map to care session cost and provider participation.",
    },
    source_sync: {
      fields: ["values", "document", "reportedAt"],
      requiredEntities: ["labResult", "sourceDocument", "canonicalRecord"],
      fieldMappings: [
        { collectionName: "lab_results", fieldName: "values" },
        { collectionName: "lab_results", fieldName: "document" },
        { collectionName: "lab_results", fieldName: "reportedAt" },
      ],
      relationMappings: [{ collectionName: "lab_results", fieldName: "doctorId", targetCollectionName: "doctors", kind: "participant" }],
      jsonAudit: { status: "justified_extension", notes: "Lab values remain JSON because individual panels vary by test definition; document and report dates are typed." },
      coverageStatus: "custom_database",
      structuralChange: "custom_database",
      notes: "Provider-specific lab import payloads remain custom database data while canonical lab result fields stay portable.",
    },
    supporting_document: {
      fields: ["title", "kind", "documentDate", "file"],
      requiredEntities: ["medicalDocument", "clinician", "file"],
      fieldMappings: [
        { collectionName: "medical_documents", fieldName: "title" },
        { collectionName: "medical_documents", fieldName: "kind" },
        { collectionName: "medical_documents", fieldName: "documentDate" },
        { collectionName: "medical_documents", fieldName: "file" },
      ],
      relationMappings: [{ collectionName: "medical_documents", fieldName: "doctorId", targetCollectionName: "doctors", kind: "participant" }],
      jsonAudit: { status: "typed_fields_available", notes: "Medical documents use typed kind/date/file fields." },
      notes: "Health evidence is file-backed and related to clinicians where appropriate.",
    },
    location_fulfillment: {
      fields: ["clinicId", "scheduledAt", "address", "city"],
      requiredEntities: ["appointment", "clinic", "place"],
      fieldMappings: [
        { collectionName: "medical_appointments", fieldName: "clinicId" },
        { collectionName: "medical_appointments", fieldName: "scheduledAt" },
        { collectionName: "clinics", fieldName: "address" },
        { collectionName: "clinics", fieldName: "city" },
      ],
      relationMappings: [{ collectionName: "medical_appointments", fieldName: "clinicId", targetCollectionName: "clinics", kind: "location" }],
      jsonAudit: { status: "typed_fields_available", notes: "Care locations use clinic relations and typed address fields." },
      notes: "Health fulfillment happens at clinics, appointments, and care locations.",
    },
    scheduled_commitment: {
      fields: ["scheduledAt", "status", "reason"],
      requiredEntities: ["appointment", "clinician", "patient"],
      fieldMappings: [
        { collectionName: "medical_appointments", fieldName: "scheduledAt", aliasesReviewed: ["appointmentScheduledAt"] },
        { collectionName: "medical_appointments", fieldName: "status" },
        { collectionName: "medical_appointments", fieldName: "reason" },
      ],
      relationMappings: [{ collectionName: "medical_appointments", fieldName: "doctorId", targetCollectionName: "doctors", kind: "participant" }],
      jsonAudit: { status: "typed_fields_available", notes: "Appointments use typed scheduled/status/reason fields." },
      notes: "Health commitments are appointments, doses, and therapy sessions.",
    },
    exception_resolution: {
      fields: ["title", "status", "description", "notes"],
      requiredEntities: ["diagnosis", "careException", "resolution"],
      fieldMappings: [
        { collectionName: "diagnoses", fieldName: "title" },
        { collectionName: "diagnoses", fieldName: "status" },
        { collectionName: "diagnoses", fieldName: "description" },
        { collectionName: "diagnoses", fieldName: "notes" },
      ],
      relationMappings: [{ collectionName: "diagnoses", fieldName: "doctorId", targetCollectionName: "doctors", kind: "participant" }],
      jsonAudit: { status: "typed_fields_available", notes: "Care exception state is represented by diagnosis status and notes." },
      notes: "Health resolution maps to diagnosis state and clinician context.",
    },
    observation_metric: {
      fields: ["loggedAt", "symptom", "severity", "values", "reportedAt"],
      requiredEntities: ["sample", "symptom", "labResult"],
      fieldMappings: [
        { collectionName: "symptom_logs", fieldName: "loggedAt" },
        { collectionName: "symptom_logs", fieldName: "symptom" },
        { collectionName: "symptom_logs", fieldName: "severity" },
        { collectionName: "lab_results", fieldName: "values" },
        { collectionName: "lab_results", fieldName: "reportedAt" },
      ],
      relationMappings: [{ collectionName: "lab_results", fieldName: "doctorId", targetCollectionName: "doctors", kind: "participant" }],
      jsonAudit: { status: "justified_extension", notes: "Symptom fields are typed; lab panel values remain JSON because panels differ by test." },
      notes: "Health observations are symptom logs, mood logs, measurements, and lab results.",
    },
    dependency_approval: {
      fields: ["doctorId", "clinicId", "status", "notes"],
      requiredEntities: ["careDependency", "clinician", "appointment"],
      fieldMappings: [
        { collectionName: "medical_appointments", fieldName: "doctorId" },
        { collectionName: "medical_appointments", fieldName: "clinicId" },
        { collectionName: "medical_appointments", fieldName: "status" },
        { collectionName: "medical_appointments", fieldName: "notes" },
      ],
      relationMappings: [{ collectionName: "medical_appointments", fieldName: "clinicId", targetCollectionName: "clinics", kind: "location" }],
      jsonAudit: { status: "typed_fields_available", notes: "Care dependencies are represented by appointment state and clinician/location relations." },
      notes: "Health dependencies commonly flow through appointments, clinician availability, and care location.",
    },
    custom_extension_boundary: {
      fields: ["tags", "values", "notesBody", "notes"],
      requiredEntities: ["customHealthAttribute", "panelValue", "canonicalRecord"],
      fieldMappings: [
        { collectionName: "symptom_logs", fieldName: "tags" },
        { collectionName: "lab_results", fieldName: "values" },
        { collectionName: "therapy_sessions", fieldName: "notesBody" },
        { collectionName: "health_conditions", fieldName: "notes" },
      ],
      relationMappings: [{ collectionName: "therapy_sessions", fieldName: "therapistId", targetCollectionName: "therapists", kind: "participant" }],
      jsonAudit: { status: "justified_extension", notes: "Health tags, lab values, and therapy notes remain bounded extensions where schemas are inherently variable." },
      structuralChange: "custom_database",
      coverageStatus: "custom_database",
      notes: "Custom databases remain valid for device-specific samples, institution-specific forms, and private care plan fields.",
    },
  },
  home_property_possessions: {
    record_lifecycle: {
      fields: ["name", "address", "city", "notes"],
      requiredEntities: ["household", "property", "inventoryItem"],
      fieldMappings: [
        { collectionName: "households", fieldName: "name", aliasesReviewed: ["householdName"] },
        { collectionName: "households", fieldName: "address" },
        { collectionName: "households", fieldName: "city" },
        { collectionName: "home_inventory_items", fieldName: "name", aliasesReviewed: ["itemName"] },
      ],
      relationMappings: [{ collectionName: "household_members", fieldName: "householdId", targetCollectionName: "households", kind: "membership" }],
      jsonAudit: { status: "typed_fields_available", notes: "Household and item lifecycle identity uses typed name/address fields." },
      notes: "Home workflows center on households, properties, inventory items, and maintenance records.",
    },
    actor_account: {
      fields: ["name", "email", "phone", "primaryContact"],
      requiredEntities: ["householdMember", "serviceProvider", "owner"],
      fieldMappings: [
        { collectionName: "household_members", fieldName: "name" },
        { collectionName: "household_members", fieldName: "email" },
        { collectionName: "household_members", fieldName: "phone" },
        { collectionName: "household_members", fieldName: "primaryContact" },
      ],
      relationMappings: [{ collectionName: "household_members", fieldName: "householdId", targetCollectionName: "households", kind: "membership" }],
      jsonAudit: { status: "typed_fields_available", notes: "Household participation is typed through member contact fields and membership relation." },
      notes: "Home actors are household members, contacts, service providers, inspectors, and visitors.",
    },
    itemized_breakdown: {
      fields: ["quantity", "room", "category", "serialNumber"],
      requiredEntities: ["inventoryItem", "room", "asset"],
      fieldMappings: [
        { collectionName: "home_inventory_items", fieldName: "quantity" },
        { collectionName: "home_inventory_items", fieldName: "room" },
        { collectionName: "home_inventory_items", fieldName: "category" },
        { collectionName: "home_inventory_items", fieldName: "serialNumber" },
      ],
      relationMappings: [{ collectionName: "manuals", fieldName: "applianceId", targetCollectionName: "appliances", kind: "ownership" }],
      jsonAudit: { status: "typed_fields_available", notes: "Inventory breakdown uses typed room/category/quantity/serial fields." },
      notes: "Home itemization maps to inventory items, appliance records, and documents.",
    },
    payment_settlement: {
      fields: ["purchasePriceCents", "costCents", "estimatedRepairCostCents"],
      requiredEntities: ["cost", "maintenanceTask", "inspection"],
      fieldMappings: [
        { collectionName: "home_inventory_items", fieldName: "purchasePriceCents", aliasesReviewed: ["itemPurchasePriceCents"] },
        { collectionName: "appliance_maintenance", fieldName: "costCents", aliasesReviewed: ["maintenanceCostCents"] },
        { collectionName: "property_inspections", fieldName: "estimatedRepairCostCents", aliasesReviewed: ["repairEstimateCents"] },
      ],
      relationMappings: [{ collectionName: "financial_documents", fieldName: "accountId", targetCollectionName: "financial_accounts", kind: "financial_transaction" }],
      jsonAudit: { status: "typed_fields_available", notes: "Home costs use typed money/cent fields and financial document relation." },
      notes: "Home settlement covers purchase price, service cost, inspection estimates, and financial documents.",
    },
    source_sync: {
      fields: ["sourceUrl", "file", "document"],
      requiredEntities: ["manual", "warranty", "sourceDocument"],
      fieldMappings: [
        { collectionName: "manuals", fieldName: "sourceUrl" },
        { collectionName: "manuals", fieldName: "file" },
        { collectionName: "warranties", fieldName: "document" },
      ],
      relationMappings: [{ collectionName: "manuals", fieldName: "applianceId", targetCollectionName: "appliances", kind: "ownership" }],
      jsonAudit: { status: "typed_fields_available", notes: "Manual and warranty provenance is file/url backed." },
      notes: "Home source/import workflows preserve manuals, warranties, and inspection reports as documents.",
    },
    supporting_document: {
      fields: ["document", "file", "report"],
      requiredEntities: ["warranty", "manual", "inspectionReport"],
      fieldMappings: [
        { collectionName: "warranties", fieldName: "document" },
        { collectionName: "manuals", fieldName: "file" },
        { collectionName: "property_inspections", fieldName: "report" },
      ],
      relationMappings: [{ collectionName: "property_inspections", fieldName: "propertyListingId", targetCollectionName: "property_listings", kind: "location" }],
      jsonAudit: { status: "typed_fields_available", notes: "Supporting home documents use file fields and property relations." },
      notes: "Home evidence includes warranties, manuals, inspection reports, receipts, and images.",
    },
    location_fulfillment: {
      fields: ["address", "city", "room", "propertyListingId"],
      requiredEntities: ["property", "room", "inspection"],
      fieldMappings: [
        { collectionName: "households", fieldName: "address" },
        { collectionName: "households", fieldName: "city" },
        { collectionName: "home_inventory_items", fieldName: "room" },
        { collectionName: "property_inspections", fieldName: "propertyListingId" },
      ],
      relationMappings: [{ collectionName: "property_inspections", fieldName: "propertyListingId", targetCollectionName: "property_listings", kind: "location" }],
      jsonAudit: { status: "typed_fields_available", notes: "Location context is represented by address/city/room and property listing relation." },
      notes: "Home fulfillment links assets and work to household location, room, and property.",
    },
    scheduled_commitment: {
      fields: ["nextDueAt", "completedAt", "performedAt", "visitedAt"],
      requiredEntities: ["chore", "maintenanceEvent", "visit"],
      fieldMappings: [
        { collectionName: "chores", fieldName: "nextDueAt" },
        { collectionName: "chore_logs", fieldName: "completedAt" },
        { collectionName: "appliance_maintenance", fieldName: "performedAt" },
        { collectionName: "property_visits", fieldName: "visitedAt" },
      ],
      relationMappings: [{ collectionName: "chore_logs", fieldName: "choreId", targetCollectionName: "chores", kind: "ownership" }],
      jsonAudit: { status: "typed_fields_available", notes: "Home schedules use typed due/completed/performed/visited dates." },
      notes: "Home commitments include chores, service visits, inspections, and warranty dates.",
    },
    exception_resolution: {
      fields: ["findings", "estimatedRepairCostCents", "notes", "active"],
      requiredEntities: ["inspectionFinding", "repair", "resolution"],
      fieldMappings: [
        { collectionName: "property_inspections", fieldName: "findings" },
        { collectionName: "property_inspections", fieldName: "estimatedRepairCostCents" },
        { collectionName: "property_inspections", fieldName: "notes" },
        { collectionName: "chores", fieldName: "active" },
      ],
      relationMappings: [{ collectionName: "property_inspections", fieldName: "propertyListingId", targetCollectionName: "property_listings", kind: "location" }],
      jsonAudit: { status: "justified_extension", notes: "Inspection findings remain JSON because reports vary; repair estimates and report files are typed." },
      coverageStatus: "custom_database",
      structuralChange: "custom_database",
      notes: "Home-specific inspection finding payloads remain bounded extensions until common structures stabilize.",
    },
    observation_metric: {
      fields: ["rating", "findings", "currentValue", "favorited"],
      requiredEntities: ["inspection", "valuation", "preference"],
      fieldMappings: [
        { collectionName: "property_visits", fieldName: "rating" },
        { collectionName: "property_inspections", fieldName: "findings" },
        { collectionName: "real_estate_owned", fieldName: "currentValue" },
        { collectionName: "home_inventory_items", fieldName: "favorited" },
      ],
      relationMappings: [{ collectionName: "property_visits", fieldName: "propertyListingId", targetCollectionName: "property_listings", kind: "location" }],
      jsonAudit: { status: "justified_extension", notes: "Property inspection findings are variable, while rating/current value/favorite state are typed." },
      notes: "Home observations include inspection findings, visit ratings, values, and asset preferences.",
    },
    dependency_approval: {
      fields: ["assignedTo", "completedBy", "active", "relation"],
      requiredEntities: ["responsibility", "householdMember", "task"],
      fieldMappings: [
        { collectionName: "chores", fieldName: "assignedTo" },
        { collectionName: "chore_logs", fieldName: "completedBy" },
        { collectionName: "chores", fieldName: "active" },
        { collectionName: "household_members", fieldName: "relation" },
      ],
      relationMappings: [{ collectionName: "chores", fieldName: "assignedTo", targetCollectionName: "household_members", kind: "membership" }],
      jsonAudit: { status: "typed_fields_available", notes: "Household responsibilities use typed membership relations and active state." },
      notes: "Home dependencies flow through household membership, assignments, chores, and maintenance ownership.",
    },
    custom_extension_boundary: {
      fields: ["findings", "notes", "description"],
      requiredEntities: ["customHomeAttribute", "inspectionPayload", "canonicalRecord"],
      fieldMappings: [
        { collectionName: "property_inspections", fieldName: "findings" },
        { collectionName: "home_inventory_items", fieldName: "notes" },
        { collectionName: "households", fieldName: "description" },
      ],
      relationMappings: [{ collectionName: "manuals", fieldName: "applianceId", targetCollectionName: "appliances", kind: "ownership" }],
      jsonAudit: { status: "justified_extension", notes: "Vendor-specific inspection payloads and private household attributes remain extension data." },
      structuralChange: "custom_database",
      coverageStatus: "custom_database",
      notes: "Custom databases remain valid for niche appliance telemetry, local service forms, and insurance-specific fields.",
    },
  },
  work_hr_legal_ops: {
    record_lifecycle: {
      fields: ["employeeNumber", "status", "hireDate", "terminationDate"],
      requiredEntities: ["employee", "department", "contract"],
      fieldMappings: [
        { collectionName: "employees", fieldName: "employeeNumber", aliasesReviewed: ["workerNumber"] },
        { collectionName: "employees", fieldName: "status" },
        { collectionName: "employees", fieldName: "hireDate" },
        { collectionName: "employees", fieldName: "terminationDate" },
      ],
      relationMappings: [{ collectionName: "employees", fieldName: "companyId", targetCollectionName: "companies", kind: "ownership" }],
      jsonAudit: { status: "typed_fields_available", notes: "Work lifecycle records use typed employee status and dates." },
      notes: "Work lifecycle maps to employee, contractor, contract, and payroll records.",
    },
    actor_account: {
      fields: ["actorId", "email", "firstName", "lastName"],
      requiredEntities: ["employee", "contractor", "manager"],
      fieldMappings: [
        { collectionName: "employees", fieldName: "actorId" },
        { collectionName: "employees", fieldName: "email", aliasesReviewed: ["workEmail"] },
        { collectionName: "employees", fieldName: "firstName" },
        { collectionName: "employees", fieldName: "lastName" },
      ],
      relationMappings: [{ collectionName: "employees", fieldName: "actorId", targetCollectionName: "actors", kind: "participant" }],
      jsonAudit: { status: "typed_fields_available", notes: "Worker identity uses typed names/email and actor relation." },
      notes: "Work actors are employees, contractors, managers, reviewers, and approvers.",
    },
    itemized_breakdown: {
      fields: ["grossCents", "netCents", "deductions", "taxes"],
      requiredEntities: ["payStub", "payrollRun", "employee"],
      fieldMappings: [
        { collectionName: "pay_stubs", fieldName: "grossCents" },
        { collectionName: "pay_stubs", fieldName: "netCents" },
        { collectionName: "pay_stubs", fieldName: "deductions" },
        { collectionName: "pay_stubs", fieldName: "taxes" },
      ],
      relationMappings: [{ collectionName: "pay_stubs", fieldName: "employeeId", targetCollectionName: "employees", kind: "participant" }],
      jsonAudit: { status: "justified_extension", notes: "Gross/net are typed; deductions/taxes remain JSON because payroll line categories vary by jurisdiction and employer." },
      notes: "Work itemization maps to pay stubs, payroll lines, review goals, and contract terms.",
    },
    payment_settlement: {
      fields: ["totalAmountCents", "currency", "paidAt", "processedByActorId"],
      requiredEntities: ["payrollRun", "employee", "processor"],
      fieldMappings: [
        { collectionName: "payroll_runs", fieldName: "totalAmountCents", aliasesReviewed: ["payrollTotalCents"] },
        { collectionName: "payroll_runs", fieldName: "currency" },
        { collectionName: "payroll_runs", fieldName: "paidAt" },
        { collectionName: "payroll_runs", fieldName: "processedByActorId" },
      ],
      relationMappings: [{ collectionName: "payroll_runs", fieldName: "processedByActorId", targetCollectionName: "actors", kind: "participant" }],
      jsonAudit: { status: "typed_fields_available", notes: "Payroll settlement uses typed amount, currency, paid date, and processor relation." },
      notes: "Work settlement covers payroll, contractor rates, and contract economics.",
    },
    source_sync: {
      fields: ["source", "links", "metadata"],
      requiredEntities: ["sourceSystem", "employee", "canonicalRecord"],
      fieldMappings: [
        { collectionName: "employees", fieldName: "source" },
        { collectionName: "employees", fieldName: "links" },
        { collectionName: "employees", fieldName: "metadata" },
      ],
      relationMappings: [{ collectionName: "employees", fieldName: "companyId", targetCollectionName: "companies", kind: "ownership" }],
      jsonAudit: { status: "justified_extension", notes: "Imported HR metadata remains bounded extension data while canonical worker fields stay typed." },
      coverageStatus: "custom_database",
      structuralChange: "custom_database",
      notes: "Provider-specific HRIS payloads remain custom database data until common across domains.",
    },
    supporting_document: {
      fields: ["pdfUrl", "source", "links"],
      requiredEntities: ["contract", "payStub", "document"],
      fieldMappings: [
        { collectionName: "contracts", fieldName: "pdfUrl", aliasesReviewed: ["contractPdfUrl"] },
        { collectionName: "pay_stubs", fieldName: "pdfUrl", aliasesReviewed: ["payStubPdfUrl"] },
        { collectionName: "contracts", fieldName: "links" },
      ],
      relationMappings: [{ collectionName: "contracts", fieldName: "companyId", targetCollectionName: "companies", kind: "ownership" }],
      jsonAudit: { status: "justified_extension", notes: "Document links are bounded metadata; core PDF URLs are typed." },
      notes: "Work evidence includes contracts, pay stubs, policy attestations, and review documents.",
    },
    location_fulfillment: {
      fields: ["country", "departmentId", "jobTitle"],
      requiredEntities: ["employee", "department", "jurisdiction"],
      fieldMappings: [
        { collectionName: "employees", fieldName: "country" },
        { collectionName: "employees", fieldName: "departmentId" },
        { collectionName: "employees", fieldName: "jobTitle" },
      ],
      relationMappings: [{ collectionName: "employees", fieldName: "departmentId", targetCollectionName: "departments", kind: "membership" }],
      jsonAudit: { status: "typed_fields_available", notes: "Work location and org placement use country and department relation fields." },
      notes: "Work fulfillment is organization, department, jurisdiction, and role context.",
    },
    scheduled_commitment: {
      fields: ["startDate", "endDate", "decidedAt", "scheduledAt"],
      requiredEntities: ["timeOffRequest", "oneOnOne", "review"],
      fieldMappings: [
        { collectionName: "time_off_requests", fieldName: "startDate" },
        { collectionName: "time_off_requests", fieldName: "endDate" },
        { collectionName: "time_off_requests", fieldName: "decidedAt" },
        { collectionName: "one_on_ones", fieldName: "scheduledAt" },
      ],
      relationMappings: [{ collectionName: "time_off_requests", fieldName: "employeeId", targetCollectionName: "employees", kind: "participant" }],
      jsonAudit: { status: "typed_fields_available", notes: "Work commitments use typed request and meeting dates." },
      notes: "Work commitments include time off, reviews, one-on-ones, payroll periods, and contract dates.",
    },
    exception_resolution: {
      fields: ["status", "feedback", "rating", "completedAt"],
      requiredEntities: ["review", "request", "resolution"],
      fieldMappings: [
        { collectionName: "performance_reviews", fieldName: "status" },
        { collectionName: "performance_reviews", fieldName: "feedback" },
        { collectionName: "performance_reviews", fieldName: "rating" },
        { collectionName: "performance_reviews", fieldName: "completedAt" },
      ],
      relationMappings: [{ collectionName: "performance_reviews", fieldName: "reviewerEmployeeId", targetCollectionName: "employees", kind: "participant" }],
      jsonAudit: { status: "typed_fields_available", notes: "Review resolution uses typed status/rating/feedback/completion fields." },
      notes: "Work exception handling maps to reviews, requests, approvals, and contract status.",
    },
    observation_metric: {
      fields: ["questions", "audienceFilter", "rating", "goalsReviewed"],
      requiredEntities: ["survey", "review", "metric"],
      fieldMappings: [
        { collectionName: "engagement_surveys", fieldName: "questions" },
        { collectionName: "engagement_surveys", fieldName: "audienceFilter" },
        { collectionName: "performance_reviews", fieldName: "rating" },
        { collectionName: "performance_reviews", fieldName: "goalsReviewed" },
      ],
      relationMappings: [{ collectionName: "performance_reviews", fieldName: "employeeId", targetCollectionName: "employees", kind: "participant" }],
      jsonAudit: { status: "justified_extension", notes: "Survey questions, audience filters, and goals reviewed are bounded JSON because their schema varies by process." },
      notes: "Work observations include engagement survey questions, review goals, ratings, and payroll totals.",
    },
    dependency_approval: {
      fields: ["approverEmployeeId", "status", "managerEmployeeId", "parentDepartmentId"],
      requiredEntities: ["approval", "manager", "department"],
      fieldMappings: [
        { collectionName: "time_off_requests", fieldName: "approverEmployeeId" },
        { collectionName: "time_off_requests", fieldName: "status" },
        { collectionName: "employees", fieldName: "managerEmployeeId" },
        { collectionName: "departments", fieldName: "parentDepartmentId" },
      ],
      relationMappings: [{ collectionName: "time_off_requests", fieldName: "approverEmployeeId", targetCollectionName: "employees", kind: "participant" }],
      jsonAudit: { status: "typed_fields_available", notes: "Work approvals and dependencies are graph-addressable employee/department relations." },
      notes: "Work dependencies include manager approval, department hierarchy, contract status, and policy gates.",
    },
    custom_extension_boundary: {
      fields: ["deductions", "taxes", "goalsReviewed", "actionItems"],
      requiredEntities: ["customHrAttribute", "reviewSchema", "payrollLine"],
      fieldMappings: [
        { collectionName: "pay_stubs", fieldName: "deductions" },
        { collectionName: "pay_stubs", fieldName: "taxes" },
        { collectionName: "performance_reviews", fieldName: "goalsReviewed" },
        { collectionName: "one_on_ones", fieldName: "actionItems" },
      ],
      relationMappings: [{ collectionName: "one_on_ones", fieldName: "managerEmployeeId", targetCollectionName: "employees", kind: "participant" }],
      jsonAudit: { status: "justified_extension", notes: "Process-specific HR review, action item, and payroll line schemas stay bounded JSON." },
      structuralChange: "custom_database",
      coverageStatus: "custom_database",
      notes: "Custom databases remain valid for organization-specific HRIS, payroll, and legal process fields.",
    },
  },
  crm_support_growth: {
    record_lifecycle: {
      fields: ["name", "lifecycleStage", "status", "lastActivityAt"],
      requiredEntities: ["account", "contact", "ticket"],
      fieldMappings: [
        { collectionName: "accounts", fieldName: "name", aliasesReviewed: ["accountName"] },
        { collectionName: "contacts", fieldName: "lifecycleStage" },
        { collectionName: "support_tickets", fieldName: "status" },
        { collectionName: "contacts", fieldName: "lastActivityAt" },
      ],
      relationMappings: [{ collectionName: "contacts", fieldName: "accountId", targetCollectionName: "accounts", kind: "financial_transaction" }],
      jsonAudit: { status: "typed_fields_available", notes: "CRM lifecycle uses typed account/contact/ticket state fields." },
      notes: "CRM lifecycle maps to account, contact, lead, deal, campaign, and ticket records.",
    },
    actor_account: {
      fields: ["email", "firstName", "lastName", "ownerActorId"],
      requiredEntities: ["contact", "lead", "owner"],
      fieldMappings: [
        { collectionName: "contacts", fieldName: "email" },
        { collectionName: "contacts", fieldName: "firstName" },
        { collectionName: "contacts", fieldName: "lastName" },
        { collectionName: "contacts", fieldName: "ownerActorId" },
      ],
      relationMappings: [{ collectionName: "contacts", fieldName: "ownerActorId", targetCollectionName: "actors", kind: "participant" }],
      jsonAudit: { status: "typed_fields_available", notes: "CRM actors use contact fields and owner actor relations." },
      notes: "CRM actors are contacts, leads, customers, owners, assignees, and requesters.",
    },
    itemized_breakdown: {
      fields: ["quantity", "discountPercent", "amountCents", "description"],
      requiredEntities: ["deal", "lineItem", "product"],
      fieldMappings: [
        { collectionName: "deal_line_items", fieldName: "quantity" },
        { collectionName: "deal_line_items", fieldName: "discountPercent" },
        { collectionName: "deal_line_items", fieldName: "amountCents", aliasesReviewed: ["dealLineAmountCents"] },
        { collectionName: "deal_line_items", fieldName: "description" },
      ],
      relationMappings: [{ collectionName: "deal_line_items", fieldName: "priceId", targetCollectionName: "prices", kind: "line_item" }],
      jsonAudit: { status: "typed_fields_available", notes: "Deal line items use typed quantity, discount, amount, and catalog relations." },
      notes: "CRM itemization maps to deal and campaign membership rows.",
    },
    payment_settlement: {
      fields: ["valueCents", "currency", "closeDate", "probability"],
      requiredEntities: ["deal", "account", "forecast"],
      fieldMappings: [
        { collectionName: "deals", fieldName: "valueCents", aliasesReviewed: ["dealValueCents"] },
        { collectionName: "deals", fieldName: "currency" },
        { collectionName: "deals", fieldName: "closeDate" },
        { collectionName: "deals", fieldName: "probability" },
      ],
      relationMappings: [{ collectionName: "deals", fieldName: "accountId", targetCollectionName: "accounts", kind: "financial_transaction" }],
      jsonAudit: { status: "typed_fields_available", notes: "Revenue and forecast dimensions are typed on deals." },
      notes: "CRM settlement maps to deal value, probability, close date, and account relation.",
    },
    source_sync: {
      fields: ["source", "properties", "eventName", "timestamp"],
      requiredEntities: ["sourceEvent", "canonicalRecord", "event"],
      fieldMappings: [
        { collectionName: "analytics_events", fieldName: "source" },
        { collectionName: "analytics_events", fieldName: "properties" },
        { collectionName: "analytics_events", fieldName: "eventName" },
        { collectionName: "analytics_events", fieldName: "timestamp" },
      ],
      relationMappings: [{ collectionName: "analytics_events", fieldName: "personId", targetCollectionName: "analytics_persons", kind: "participant" }],
      jsonAudit: { status: "justified_extension", notes: "Event properties remain JSON because analytics schemas vary by event name." },
      coverageStatus: "custom_database",
      structuralChange: "custom_database",
      notes: "Provider-specific CRM/source payloads remain custom database data while canonical events keep typed identity and time.",
    },
    supporting_document: {
      fields: ["body", "bodyHtml", "attachments"],
      requiredEntities: ["message", "attachment", "conversation"],
      fieldMappings: [
        { collectionName: "support_messages", fieldName: "body" },
        { collectionName: "support_messages", fieldName: "bodyHtml" },
        { collectionName: "support_messages", fieldName: "attachments" },
      ],
      relationMappings: [{ collectionName: "support_messages", fieldName: "conversationId", targetCollectionName: "support_conversations", kind: "ownership" }],
      jsonAudit: { status: "justified_extension", notes: "Support message attachments remain JSON because each message may carry heterogeneous files." },
      notes: "CRM/support evidence includes messages, attachments, survey comments, and campaign links.",
    },
    location_fulfillment: {
      fields: ["address", "domain", "industry", "phone"],
      requiredEntities: ["account", "company", "address"],
      fieldMappings: [
        { collectionName: "accounts", fieldName: "address" },
        { collectionName: "accounts", fieldName: "domain" },
        { collectionName: "accounts", fieldName: "industry" },
        { collectionName: "accounts", fieldName: "phone" },
      ],
      relationMappings: [{ collectionName: "accounts", fieldName: "ownerActorId", targetCollectionName: "actors", kind: "participant" }],
      jsonAudit: { status: "justified_extension", notes: "Account address remains JSON because postal formats vary; account domain/industry/phone are typed." },
      notes: "CRM location context is account address, domain, market segment, and owner coverage.",
    },
    scheduled_commitment: {
      fields: ["startDate", "endDate", "surveySentAt", "respondedAt"],
      requiredEntities: ["campaign", "survey", "response"],
      fieldMappings: [
        { collectionName: "campaigns", fieldName: "startDate" },
        { collectionName: "campaigns", fieldName: "endDate" },
        { collectionName: "satisfaction_ratings", fieldName: "surveySentAt" },
        { collectionName: "satisfaction_ratings", fieldName: "respondedAt" },
      ],
      relationMappings: [{ collectionName: "satisfaction_ratings", fieldName: "ticketId", targetCollectionName: "support_tickets", kind: "ownership" }],
      jsonAudit: { status: "typed_fields_available", notes: "Campaign and survey timing use typed date fields." },
      notes: "CRM commitments include campaigns, SLA events, survey sends, and follow-ups.",
    },
    exception_resolution: {
      fields: ["priority", "status", "linkedIssueId", "lostReason"],
      requiredEntities: ["ticket", "issue", "dealException"],
      fieldMappings: [
        { collectionName: "support_tickets", fieldName: "priority" },
        { collectionName: "support_tickets", fieldName: "status" },
        { collectionName: "support_tickets", fieldName: "linkedIssueId" },
        { collectionName: "deals", fieldName: "lostReason" },
      ],
      relationMappings: [{ collectionName: "support_tickets", fieldName: "linkedIssueId", targetCollectionName: "issues", kind: "dependency" }],
      jsonAudit: { status: "typed_fields_available", notes: "Support and deal exceptions use typed priority/status/link/lost reason fields." },
      notes: "CRM exception resolution covers tickets, linked issues, lost deals, and campaign failures.",
    },
    observation_metric: {
      fields: ["score", "comment", "eventName", "usersCount"],
      requiredEntities: ["rating", "event", "segment"],
      fieldMappings: [
        { collectionName: "satisfaction_ratings", fieldName: "score" },
        { collectionName: "satisfaction_ratings", fieldName: "comment" },
        { collectionName: "analytics_events", fieldName: "eventName" },
        { collectionName: "segments", fieldName: "usersCount" },
      ],
      relationMappings: [{ collectionName: "satisfaction_ratings", fieldName: "contactId", targetCollectionName: "contacts", kind: "participant" }],
      jsonAudit: { status: "typed_fields_available", notes: "Ratings, comments, event names, and segment counts are typed." },
      notes: "CRM observations include satisfaction, analytics events, survey responses, and segment counts.",
    },
    dependency_approval: {
      fields: ["campaignId", "contactId", "leadId", "status"],
      requiredEntities: ["campaignMember", "contact", "lead"],
      fieldMappings: [
        { collectionName: "campaign_members", fieldName: "campaignId" },
        { collectionName: "campaign_members", fieldName: "contactId" },
        { collectionName: "campaign_members", fieldName: "leadId" },
        { collectionName: "campaign_members", fieldName: "status" },
      ],
      relationMappings: [{ collectionName: "campaign_members", fieldName: "contactId", targetCollectionName: "contacts", kind: "participant" }],
      jsonAudit: { status: "typed_fields_available", notes: "Campaign membership dependencies use typed participant relations and status." },
      notes: "CRM dependencies flow through campaign membership, owner assignment, ticket links, and pipeline stages.",
    },
    custom_extension_boundary: {
      fields: ["properties", "rules", "questions", "targeting"],
      requiredEntities: ["customCrmProperty", "segmentRule", "surveySchema"],
      fieldMappings: [
        { collectionName: "contacts", fieldName: "properties" },
        { collectionName: "segments", fieldName: "rules" },
        { collectionName: "surveys", fieldName: "questions" },
        { collectionName: "surveys", fieldName: "targeting" },
      ],
      relationMappings: [{ collectionName: "survey_responses", fieldName: "surveyId", targetCollectionName: "surveys", kind: "observation_sample" }],
      jsonAudit: { status: "justified_extension", notes: "CRM properties, segment rules, and survey schemas are deliberately bounded JSON extension points." },
      structuralChange: "custom_database",
      coverageStatus: "custom_database",
      notes: "Custom databases remain valid for tenant-specific CRM fields, scoring rules, and survey schemas.",
    },
  },
  personal_memory_documents: {
    record_lifecycle: {
      fields: ["title", "entryDate", "happenedAt", "status"],
      requiredEntities: ["note", "journalEntry", "memory", "goal"],
      fieldMappings: [
        { collectionName: "journal_entries", fieldName: "title", aliasesReviewed: ["journalTitle"] },
        { collectionName: "journal_entries", fieldName: "entryDate" },
        { collectionName: "memories", fieldName: "happenedAt" },
        { collectionName: "goals", fieldName: "status" },
      ],
      relationMappings: [{ collectionName: "habit_logs", fieldName: "habitId", targetCollectionName: "habits", kind: "observation_sample" }],
      jsonAudit: { status: "typed_fields_available", notes: "Personal lifecycle state uses typed dates, titles, and goal status." },
      notes: "Personal memory lifecycle maps to notes, journal entries, memories, goals, and routines.",
    },
    actor_account: {
      fields: ["ownerPersonId", "ownerAgentId", "companyId"],
      requiredEntities: ["person", "agent", "profile"],
      fieldMappings: [
        { collectionName: "goals", fieldName: "ownerPersonId" },
        { collectionName: "goals", fieldName: "ownerAgentId" },
        { collectionName: "memory_blocks", fieldName: "agentId" },
        { collectionName: "memory_blocks", fieldName: "companyId" },
      ],
      relationMappings: [{ collectionName: "memory_blocks", fieldName: "agentId", targetCollectionName: "company_agents", kind: "ownership" }],
      jsonAudit: { status: "typed_fields_available", notes: "Personal ownership maps to goal owner fields and agent memory ownership relations." },
      notes: "Personal actors are the person, profile, agent, and optional household/workspace context.",
    },
    itemized_breakdown: {
      fields: ["targetValue", "currentValue", "unit", "value"],
      requiredEntities: ["goalMetric", "habitLog", "routine"],
      fieldMappings: [
        { collectionName: "goals", fieldName: "targetValue" },
        { collectionName: "goals", fieldName: "currentValue" },
        { collectionName: "goals", fieldName: "unit" },
        { collectionName: "habit_logs", fieldName: "value" },
      ],
      relationMappings: [{ collectionName: "habit_logs", fieldName: "habitId", targetCollectionName: "habits", kind: "observation_sample" }],
      jsonAudit: { status: "typed_fields_available", notes: "Goal metrics and habit log values are typed." },
      notes: "Personal itemization maps to goal metrics, habit values, and routine structure.",
    },
    payment_settlement: {
      fields: ["metricKey", "metricDirection", "targetValue", "currentValue"],
      requiredEntities: ["commitment", "metric", "outcome"],
      fieldMappings: [
        { collectionName: "goals", fieldName: "metricKey" },
        { collectionName: "goals", fieldName: "metricDirection" },
        { collectionName: "goals", fieldName: "targetValue" },
        { collectionName: "goals", fieldName: "currentValue" },
      ],
      relationMappings: [{ collectionName: "knowledge_graphs", fieldName: "companyId", targetCollectionName: "companies", kind: "ownership" }],
      jsonAudit: { status: "typed_fields_available", notes: "Personal commitment settlement is represented by typed goal metric fields." },
      notes: "Personal settlement is usually outcome/commitment progress rather than monetary flow.",
    },
    source_sync: {
      fields: ["source", "links", "metadata", "sourceRunIds"],
      requiredEntities: ["sourceRecord", "memoryBlock", "knowledgeGraph"],
      fieldMappings: [
        { collectionName: "memory_blocks", fieldName: "source" },
        { collectionName: "memory_blocks", fieldName: "links" },
        { collectionName: "memory_blocks", fieldName: "metadata" },
        { collectionName: "knowledge_graphs", fieldName: "sourceRunIds" },
      ],
      relationMappings: [{ collectionName: "memory_blocks", fieldName: "memoryIndexId", targetCollectionName: "memory_indices", kind: "attachment" }],
      jsonAudit: { status: "justified_extension", notes: "Personal memory source metadata and source run lists remain bounded extension data." },
      coverageStatus: "custom_database",
      structuralChange: "custom_database",
      notes: "Private import/source payloads remain custom database data unless they generalize into canonical memory fields.",
    },
    supporting_document: {
      fields: ["file", "number", "country", "expiresAt"],
      requiredEntities: ["document", "identityRecord", "file"],
      fieldMappings: [
        { collectionName: "identity_documents", fieldName: "file" },
        { collectionName: "identity_documents", fieldName: "number" },
        { collectionName: "identity_documents", fieldName: "country" },
        { collectionName: "identity_documents", fieldName: "expiresAt" },
      ],
      relationMappings: [{ collectionName: "memory_blocks", fieldName: "memoryIndexId", targetCollectionName: "memory_indices", kind: "attachment" }],
      jsonAudit: { status: "typed_fields_available", notes: "Personal document identity, expiry, and files are typed." },
      notes: "Personal evidence includes identity documents, files, memory attachments, and knowledge references.",
    },
    location_fulfillment: {
      fields: ["location", "startsAt", "endsAt", "country"],
      requiredEntities: ["personalEvent", "place", "document"],
      fieldMappings: [
        { collectionName: "personal_events", fieldName: "location" },
        { collectionName: "personal_events", fieldName: "startsAt" },
        { collectionName: "personal_events", fieldName: "endsAt" },
        { collectionName: "identity_documents", fieldName: "country" },
      ],
      relationMappings: [{ collectionName: "memory_blocks", fieldName: "memoryIndexId", targetCollectionName: "memory_indices", kind: "attachment" }],
      jsonAudit: { status: "typed_fields_available", notes: "Personal events and documents use typed location/date/country fields." },
      notes: "Personal location context lives on personal events and documents.",
    },
    scheduled_commitment: {
      fields: ["forDate", "timeframeStart", "timeframeEnd", "reviewCadence"],
      requiredEntities: ["intention", "goal", "routine"],
      fieldMappings: [
        { collectionName: "intentions", fieldName: "forDate" },
        { collectionName: "goals", fieldName: "timeframeStart" },
        { collectionName: "goals", fieldName: "timeframeEnd" },
        { collectionName: "goals", fieldName: "reviewCadence" },
      ],
      relationMappings: [{ collectionName: "habit_logs", fieldName: "habitId", targetCollectionName: "habits", kind: "observation_sample" }],
      jsonAudit: { status: "typed_fields_available", notes: "Personal commitments use typed intention dates and goal review windows." },
      notes: "Personal scheduled commitments include intentions, routines, habit logs, and goal reviews.",
    },
    exception_resolution: {
      fields: ["healthStatus", "archivedAt", "archived", "notes"],
      requiredEntities: ["goal", "note", "resolution"],
      fieldMappings: [
        { collectionName: "goals", fieldName: "healthStatus" },
        { collectionName: "goals", fieldName: "archivedAt" },
        { collectionName: "personal_notes", fieldName: "archived" },
        { collectionName: "reflections", fieldName: "notes" },
      ],
      relationMappings: [{ collectionName: "habit_logs", fieldName: "habitId", targetCollectionName: "habits", kind: "observation_sample" }],
      jsonAudit: { status: "typed_fields_available", notes: "Personal exceptions use typed goal health/archive and note archive state." },
      notes: "Personal exception resolution maps to goal health, archived notes, and reflections.",
    },
    observation_metric: {
      fields: ["loggedAt", "completed", "value", "confidence"],
      requiredEntities: ["habitLog", "knowledgeSignal", "sample"],
      fieldMappings: [
        { collectionName: "habit_logs", fieldName: "loggedAt" },
        { collectionName: "habit_logs", fieldName: "completed" },
        { collectionName: "habit_logs", fieldName: "value" },
        { collectionName: "knowledge_graphs", fieldName: "confidence" },
      ],
      relationMappings: [{ collectionName: "habit_logs", fieldName: "habitId", targetCollectionName: "habits", kind: "observation_sample" }],
      jsonAudit: { status: "typed_fields_available", notes: "Habit observations and knowledge confidence are typed." },
      notes: "Personal observations include habit samples, memory confidence, ratings, and reflections.",
    },
    dependency_approval: {
      fields: ["parentGoalId", "projectId", "areaId", "parentId"],
      requiredEntities: ["goal", "parentGoal", "area", "project"],
      fieldMappings: [
        { collectionName: "goals", fieldName: "parentGoalId" },
        { collectionName: "goals", fieldName: "projectId" },
        { collectionName: "goals", fieldName: "areaId" },
        { collectionName: "goals", fieldName: "parentId" },
      ],
      relationMappings: [{ collectionName: "memory_blocks", fieldName: "companyId", targetCollectionName: "companies", kind: "ownership" }],
      jsonAudit: { status: "typed_fields_available", notes: "Goal hierarchy fields are typed, while productivity relation semantics remain a separate catalog improvement area." },
      notes: "Personal dependencies include goal hierarchy, project/area linkage, and memory graph ownership.",
    },
    custom_extension_boundary: {
      fields: ["tags", "images", "properties", "embeddingVector"],
      requiredEntities: ["customMemoryAttribute", "privateTag", "embedding"],
      fieldMappings: [
        { collectionName: "journal_entries", fieldName: "tags" },
        { collectionName: "memories", fieldName: "images" },
        { collectionName: "knowledge_graphs", fieldName: "properties" },
        { collectionName: "memory_blocks", fieldName: "embeddingVector" },
      ],
      relationMappings: [{ collectionName: "memory_blocks", fieldName: "memoryIndexId", targetCollectionName: "memory_indices", kind: "attachment" }],
      jsonAudit: { status: "justified_extension", notes: "Personal tags, image lists, knowledge properties, and embeddings remain bounded JSON/private extension data." },
      structuralChange: "custom_database",
      coverageStatus: "custom_database",
      notes: "Custom databases remain valid for private memory dimensions, embeddings, and personal-only classification systems.",
    },
  },
};
