export interface ClawDenseDataFixtureRecord {
  id: string;
  collectionName: string;
  label: string;
  covers: string[];
  data: Record<string, unknown>;
}

export interface ClawDenseDataAcceptanceFixture {
  schemaVersion: 1;
  sourceConversationId: string;
  fixtureSetId: string;
  records: ClawDenseDataFixtureRecord[];
}

export const clawDenseDataAcceptanceFixture: ClawDenseDataAcceptanceFixture = {
  schemaVersion: 1,
  sourceConversationId: "019e35a1-06bb-77f2-a712-92ed2646bd15",
  fixtureSetId: "dense-data-acceptance-v1",
  records: [
    {
      id: "fixture_company_acme",
      collectionName: "companies",
      label: "Acme Research Manufacturing",
      covers: ["company", "erp", "crm", "invoice_company", "company_timeline"],
      data: { name: "Acme Research Manufacturing", domain: "example.test", evidence: ["fixture_evidence_intake_note"] },
    },
    {
      id: "fixture_patient_ada",
      collectionName: "patients",
      label: "Ada Patient",
      covers: ["patient", "health", "identity_profile", "partial_data"],
      data: { displayName: "Ada Patient", status: "active", qualityGaps: ["fixture_gap_missing_dob"], evidence: ["fixture_evidence_intake_note"] },
    },
    {
      id: "fixture_study_trial_a",
      collectionName: "studies",
      label: "Trial A",
      covers: ["study", "research", "ctms"],
      data: { title: "Trial A", status: "planned", evidence: ["fixture_evidence_intake_note"] },
    },
    {
      id: "fixture_participant_subject_001",
      collectionName: "participants",
      label: "Subject 001",
      covers: ["participant", "research", "ctms"],
      data: { displayName: "Subject 001", studyId: "fixture_study_trial_a", status: "screening", consentStatus: "unknown" },
    },
    {
      id: "fixture_sample_tube_a",
      collectionName: "samples",
      label: "Tube A",
      covers: ["sample", "labs", "lims", "research_sample"],
      data: { label: "Tube A", studyId: "fixture_study_trial_a", status: "collected", evidence: ["fixture_evidence_intake_note"] },
    },
    {
      id: "fixture_assay_cbc",
      collectionName: "assays",
      label: "CBC",
      covers: ["assay", "labs", "lims"],
      data: { name: "CBC", sampleId: "fixture_sample_tube_a", status: "ordered" },
    },
    {
      id: "fixture_organism_mouse_a",
      collectionName: "organisms",
      label: "Mouse A",
      covers: ["organism", "biology"],
      data: { label: "Mouse A", species: "Mus musculus", status: "active" },
    },
    {
      id: "fixture_biology_experiment_dose_response",
      collectionName: "biology_experiments",
      label: "Dose response",
      covers: ["experiment", "biology", "eln"],
      data: { title: "Dose response", organismId: "fixture_organism_mouse_a", status: "planned" },
    },
    {
      id: "fixture_sample_exp_1",
      collectionName: "samples",
      label: "Exp sample 1",
      covers: ["sample", "biology", "experiment_sample"],
      data: { label: "Exp sample 1", biologyExperimentId: "fixture_biology_experiment_dose_response", organismId: "fixture_organism_mouse_a", status: "collected" },
    },
    {
      id: "fixture_assay_marker",
      collectionName: "assays",
      label: "Marker assay",
      covers: ["assay", "biology", "experiment_assay"],
      data: { name: "Marker assay", sampleId: "fixture_sample_exp_1", status: "ordered" },
    },
    {
      id: "fixture_legal_case_smith",
      collectionName: "legal_cases",
      label: "Smith v Jones",
      covers: ["legal_case", "legal"],
      data: { title: "Smith v Jones", status: "open", evidence: ["fixture_evidence_contract"] },
    },
    {
      id: "fixture_case_evidence_contract",
      collectionName: "case_evidence",
      label: "Signed contract",
      covers: ["case_evidence", "evidence"],
      data: { title: "Signed contract", caseId: "fixture_legal_case_smith", source: { fixtureId: "fixture_evidence_contract" } },
    },
    {
      id: "fixture_billing_customer_acme",
      collectionName: "billing_customers",
      label: "Acme Billing",
      covers: ["billing_customer", "invoice_company", "company_timeline"],
      data: { name: "Acme Billing", companyId: "fixture_company_acme" },
    },
    {
      id: "fixture_account_acme",
      collectionName: "accounts",
      label: "Acme Account",
      covers: ["account", "crm", "erp_company_overview", "asset_timeline", "company_timeline"],
      data: { name: "Acme Account", companyId: "fixture_company_acme", industry: "research_manufacturing" },
    },
    {
      id: "fixture_product_press_model",
      collectionName: "products_catalog",
      label: "Press Model",
      covers: ["product_catalog", "erp", "crm", "asset_timeline", "company_timeline"],
      data: { name: "Press Model", companyId: "fixture_company_acme", type: "physical", active: true },
    },
    {
      id: "fixture_asset_press_001",
      collectionName: "assets",
      label: "Press 001",
      covers: ["asset", "manufacturing", "mes", "crm", "asset_timeline", "company_timeline", "partial_data"],
      data: { companyId: "fixture_company_acme", accountId: "fixture_account_acme", productCatalogId: "fixture_product_press_model", serialNumber: "PRESS-001", status: "active" },
    },
    {
      id: "fixture_deal_acme_pilot",
      collectionName: "deals",
      label: "Pilot",
      covers: ["deal", "crm", "erp_company_overview", "crm_account_overview", "company_timeline"],
      data: { title: "Pilot", companyId: "fixture_company_acme", accountId: "fixture_account_acme", valueCents: 2500, currency: "USD", status: "open" },
    },
    {
      id: "fixture_contact_acme_ada",
      collectionName: "contacts",
      label: "Ada Buyer",
      covers: ["contact", "crm", "crm_account_overview", "company_timeline"],
      data: { firstName: "Ada", lastName: "Buyer", email: "ada@example.test", companyId: "fixture_company_acme", accountId: "fixture_account_acme", lifecycleStage: "customer" },
    },
    {
      id: "fixture_activity_acme_demo",
      collectionName: "activities",
      label: "Demo call",
      covers: ["activity", "crm", "crm_account_overview", "company_timeline"],
      data: { kind: "demo", subject: "Demo call", companyId: "fixture_company_acme", accountId: "fixture_account_acme", dealId: "fixture_deal_acme_pilot" },
    },
    {
      id: "fixture_invoice_001",
      collectionName: "invoices",
      label: "INV-001",
      covers: ["invoice", "erp", "finance", "company_timeline"],
      data: { number: "INV-001", billingCustomerId: "fixture_billing_customer_acme", totalCents: 9900, currency: "USD", status: "draft" },
    },
    {
      id: "fixture_payment_intent_001",
      collectionName: "payment_intents",
      label: "INV-001 payment intent",
      covers: ["payment", "erp", "finance", "erp_company_overview", "company_timeline"],
      data: { billingCustomerId: "fixture_billing_customer_acme", invoiceId: "fixture_invoice_001", amountCents: 9900, currency: "USD", status: "requires_payment_method" },
    },
    {
      id: "fixture_financial_account_ops",
      collectionName: "financial_accounts",
      label: "Operating Account",
      covers: ["financial_account", "finance", "accounting", "finance_entity_overview"],
      data: { name: "Operating Account", kind: "checking", currency: "USD", active: true },
    },
    {
      id: "fixture_transaction_lunch",
      collectionName: "transactions",
      label: "Lunch",
      covers: ["transaction", "finance", "accounting", "finance_entity_overview"],
      data: { description: "Lunch", accountId: "fixture_financial_account_ops", amountCents: 1200, currency: "USD", kind: "debit", postedAt: "2026-05-17T00:00:00.000Z" },
    },
    {
      id: "fixture_service_api",
      collectionName: "services",
      label: "API",
      covers: ["service", "ops", "itsm", "company_timeline"],
      data: { name: "API", companyId: "fixture_company_acme", status: "active" },
    },
    {
      id: "fixture_incident_outage",
      collectionName: "incidents",
      label: "Outage",
      covers: ["incident", "ops", "itsm"],
      data: { title: "Outage", serviceId: "fixture_service_api", severity: "sev2", status: "open" },
    },
    {
      id: "fixture_learner_ada",
      collectionName: "learners",
      label: "Ada Learner",
      covers: ["learner", "education", "lms", "learner_timeline", "partial_data"],
      data: { displayName: "Ada Learner", status: "active", program: "Biology", startedAt: "2026-05-17T00:00:00.000Z", evidence: ["fixture_evidence_learner_record"], qualityGaps: ["fixture_gap_learner_credential"] },
    },
    {
      id: "fixture_course_intro_biology",
      collectionName: "courses",
      label: "Intro Biology",
      covers: ["course", "education", "lms", "learner_timeline", "course_timeline"],
      data: { title: "Intro Biology", status: "enrolled" },
    },
    {
      id: "fixture_lesson_cell_basics",
      collectionName: "lessons",
      label: "Cell basics",
      covers: ["lesson", "education", "lms", "course_timeline"],
      data: { title: "Cell basics", courseId: "fixture_course_intro_biology", position: 1, status: "completed" },
    },
    {
      id: "fixture_study_session_biology",
      collectionName: "study_sessions",
      label: "Biology review",
      covers: ["study_session", "education", "lms", "course_timeline"],
      data: { topic: "Biology review", courseId: "fixture_course_intro_biology", startedAt: "2026-05-17T00:00:00.000Z", durationMinutes: 45 },
    },
    {
      id: "fixture_relation_learner_course",
      collectionName: "entity_relations",
      label: "Ada enrolled in Intro Biology",
      covers: ["entity_relation", "education", "lms", "learner_timeline", "course_timeline"],
      data: { fromEntityKind: "learners", fromEntityId: "fixture_learner_ada", toEntityKind: "courses", toEntityId: "fixture_course_intro_biology", type: "member_of" },
    },
    {
      id: "fixture_work_order_batch_42",
      collectionName: "work_orders",
      label: "Batch 42",
      covers: ["work_order", "manufacturing", "mes", "asset_timeline", "company_timeline"],
      data: { title: "Batch 42", companyId: "fixture_company_acme", assetId: "fixture_asset_press_001", status: "planned" },
    },
    {
      id: "fixture_relation_asset_service",
      collectionName: "entity_relations",
      label: "Press supports API",
      covers: ["entity_relation", "asset_timeline", "ops", "manufacturing"],
      data: { fromEntityKind: "assets", fromEntityId: "fixture_asset_press_001", toEntityKind: "services", toEntityId: "fixture_service_api", type: "references" },
    },
    {
      id: "fixture_evidence_asset_install",
      collectionName: "evidence_sources",
      label: "Asset install record",
      covers: ["evidence", "asset_timeline", "document_evidence"],
      data: { label: "Asset install record", kind: "document", collectionName: "assets", recordId: "fixture_asset_press_001", capturedAt: "2026-05-17T00:00:00.000Z" },
    },
    {
      id: "fixture_evidence_course_syllabus",
      collectionName: "evidence_sources",
      label: "Course syllabus",
      covers: ["evidence", "course_timeline", "document_evidence"],
      data: { label: "Course syllabus", kind: "document", collectionName: "courses", recordId: "fixture_course_intro_biology", capturedAt: "2026-05-17T00:00:00.000Z" },
    },
    {
      id: "fixture_evidence_learner_record",
      collectionName: "evidence_sources",
      label: "Learner import record",
      covers: ["evidence", "learner_timeline", "document_evidence"],
      data: { label: "Learner import record", kind: "document", collectionName: "learners", recordId: "fixture_learner_ada", capturedAt: "2026-05-17T00:00:00.000Z" },
    },
    {
      id: "fixture_evidence_work_order_batch_42",
      collectionName: "evidence_sources",
      label: "Batch 42 traveler",
      covers: ["evidence", "manufacturing_evidence", "document_evidence"],
      data: { label: "Batch 42 traveler", kind: "document", collectionName: "work_orders", recordId: "fixture_work_order_batch_42", capturedAt: "2026-05-17T00:00:00.000Z" },
    },
    {
      id: "fixture_evidence_company_import",
      collectionName: "evidence_sources",
      label: "Company import note",
      covers: ["evidence", "erp_company_overview", "company_timeline", "document_evidence"],
      data: { label: "Company import note", kind: "document", collectionName: "companies", recordId: "fixture_company_acme", capturedAt: "2026-05-17T00:00:00.000Z" },
    },
    {
      id: "fixture_evidence_account_discovery",
      collectionName: "evidence_sources",
      label: "Account discovery note",
      covers: ["evidence", "crm_account_overview", "document_evidence"],
      data: { label: "Account discovery note", kind: "document", collectionName: "accounts", recordId: "fixture_account_acme", capturedAt: "2026-05-17T00:00:00.000Z" },
    },
    {
      id: "fixture_evidence_finance_statement",
      collectionName: "evidence_sources",
      label: "Bank statement",
      covers: ["evidence", "finance_entity_overview", "document_evidence"],
      data: { label: "Bank statement", kind: "document", collectionName: "financial_accounts", recordId: "fixture_financial_account_ops", capturedAt: "2026-05-17T00:00:00.000Z" },
    },
    {
      id: "fixture_evidence_intake_note",
      collectionName: "evidence_sources",
      label: "Clinic intake note",
      covers: ["evidence", "document_evidence", "raw_import"],
      data: { label: "Clinic intake note", kind: "document", collectionName: "patients", recordId: "fixture_patient_ada", capturedAt: "2026-05-17T00:00:00.000Z" },
    },
    {
      id: "fixture_evidence_contract",
      collectionName: "evidence_sources",
      label: "Signed contract file",
      covers: ["evidence", "legal_evidence", "document_evidence"],
      data: { label: "Signed contract file", kind: "file", collectionName: "legal_cases", recordId: "fixture_legal_case_smith", capturedAt: "2026-05-17T00:00:00.000Z" },
    },
    {
      id: "fixture_provenance_asset_import",
      collectionName: "provenance_events",
      label: "Asset imported from install record",
      covers: ["provenance", "asset_timeline", "auditability"],
      data: { eventType: "imported", targetCollection: "assets", targetId: "fixture_asset_press_001", evidenceSourceId: "fixture_evidence_asset_install", occurredAt: "2026-05-17T00:00:00.000Z" },
    },
    {
      id: "fixture_provenance_course_import",
      collectionName: "provenance_events",
      label: "Course imported from LMS",
      covers: ["provenance", "course_timeline", "auditability"],
      data: { eventType: "imported", targetCollection: "courses", targetId: "fixture_course_intro_biology", evidenceSourceId: "fixture_evidence_course_syllabus", occurredAt: "2026-05-17T00:00:00.000Z" },
    },
    {
      id: "fixture_provenance_learner_import",
      collectionName: "provenance_events",
      label: "Learner imported from LMS record",
      covers: ["provenance", "learner_timeline", "auditability"],
      data: { eventType: "imported", targetCollection: "learners", targetId: "fixture_learner_ada", evidenceSourceId: "fixture_evidence_learner_record", occurredAt: "2026-05-17T00:00:00.000Z" },
    },
    {
      id: "fixture_provenance_patient_import",
      collectionName: "provenance_events",
      label: "Patient imported from intake note",
      covers: ["provenance", "auditability"],
      data: { eventType: "imported", targetCollection: "patients", targetId: "fixture_patient_ada", evidenceSourceId: "fixture_evidence_intake_note", occurredAt: "2026-05-17T00:00:00.000Z" },
    },
    {
      id: "fixture_provenance_company_import",
      collectionName: "provenance_events",
      label: "Company imported from ERP note",
      covers: ["provenance", "erp_company_overview", "company_timeline", "auditability"],
      data: { eventType: "imported", targetCollection: "companies", targetId: "fixture_company_acme", evidenceSourceId: "fixture_evidence_company_import", occurredAt: "2026-05-17T00:00:00.000Z" },
    },
    {
      id: "fixture_provenance_account_discovery",
      collectionName: "provenance_events",
      label: "Account imported from discovery note",
      covers: ["provenance", "crm_account_overview", "auditability"],
      data: { eventType: "imported", targetCollection: "accounts", targetId: "fixture_account_acme", evidenceSourceId: "fixture_evidence_account_discovery", occurredAt: "2026-05-17T00:00:00.000Z" },
    },
    {
      id: "fixture_provenance_finance_statement",
      collectionName: "provenance_events",
      label: "Finance account imported from statement",
      covers: ["provenance", "finance_entity_overview", "auditability"],
      data: { eventType: "imported", targetCollection: "financial_accounts", targetId: "fixture_financial_account_ops", evidenceSourceId: "fixture_evidence_finance_statement", occurredAt: "2026-05-17T00:00:00.000Z" },
    },
    {
      id: "fixture_gap_asset_maintenance_plan",
      collectionName: "quality_gaps",
      label: "Missing maintenance plan",
      covers: ["partial_data_gap", "quality_gap", "asset_timeline"],
      data: { label: "Missing maintenance plan", targetCollection: "assets", targetId: "fixture_asset_press_001", gapKind: "missing", status: "open", severity: "medium", evidenceSourceId: "fixture_evidence_asset_install" },
    },
    {
      id: "fixture_gap_course_assessment",
      collectionName: "quality_gaps",
      label: "Missing assessment rubric",
      covers: ["partial_data_gap", "quality_gap", "course_timeline"],
      data: { label: "Missing assessment rubric", targetCollection: "courses", targetId: "fixture_course_intro_biology", gapKind: "missing", status: "open", severity: "medium", evidenceSourceId: "fixture_evidence_course_syllabus" },
    },
    {
      id: "fixture_gap_learner_credential",
      collectionName: "quality_gaps",
      label: "Missing credential evidence",
      covers: ["partial_data_gap", "quality_gap", "learner_timeline"],
      data: { label: "Missing credential evidence", targetCollection: "learners", targetId: "fixture_learner_ada", gapKind: "missing", status: "open", severity: "medium", evidenceSourceId: "fixture_evidence_learner_record" },
    },
    {
      id: "fixture_gap_missing_dob",
      collectionName: "quality_gaps",
      label: "Missing date of birth",
      covers: ["partial_data_gap", "quality_gap"],
      data: { label: "Missing date of birth", targetCollection: "patients", targetId: "fixture_patient_ada", gapKind: "missing", status: "open", severity: "medium", evidenceSourceId: "fixture_evidence_intake_note" },
    },
    {
      id: "fixture_gap_company_tax_id",
      collectionName: "quality_gaps",
      label: "Missing tax ID",
      covers: ["partial_data_gap", "quality_gap", "erp_company_overview", "company_timeline"],
      data: { label: "Missing tax ID", targetCollection: "companies", targetId: "fixture_company_acme", gapKind: "missing", status: "open", severity: "medium", evidenceSourceId: "fixture_evidence_company_import" },
    },
    {
      id: "fixture_gap_account_owner",
      collectionName: "quality_gaps",
      label: "Missing account owner",
      covers: ["partial_data_gap", "quality_gap", "crm_account_overview"],
      data: { label: "Missing account owner", targetCollection: "accounts", targetId: "fixture_account_acme", gapKind: "missing", status: "open", severity: "medium", evidenceSourceId: "fixture_evidence_account_discovery" },
    },
    {
      id: "fixture_gap_finance_reconciliation",
      collectionName: "quality_gaps",
      label: "Missing reconciliation status",
      covers: ["partial_data_gap", "quality_gap", "finance_entity_overview"],
      data: { label: "Missing reconciliation status", targetCollection: "financial_accounts", targetId: "fixture_financial_account_ops", gapKind: "missing", status: "open", severity: "medium", evidenceSourceId: "fixture_evidence_finance_statement" },
    },
  ],
};

export function listClawDenseDataAcceptanceFixtureRecords(): ClawDenseDataFixtureRecord[] {
  return [...clawDenseDataAcceptanceFixture.records];
}
