import { clawDomainSchema, type ClawDomain } from "./host-contracts.ts";

export type ClawDomainMigrationStatus =
  | "contract_defined"
  | "framework_canonical"
  | "host_pattern_done"
  | "clawix_projection_only";

export type ClawDomainOwnership = {
  domain: ClawDomain;
  phase: number;
  status: ClawDomainMigrationStatus;
  frameworkOwns: readonly string[];
  hostOwns: readonly string[];
  clawixUiOwns: readonly string[];
  brokerRequired: boolean;
  destructivePolicy: "none" | "explicit_grant" | "explicit_grant_and_audit";
  costPolicy: "none" | "host_approval_or_grant";
  requiredTests: readonly string[];
};

const commonContractTests = [
  "contract_fixture",
  "cli_json",
  "claw_app_standalone",
  "clawix_embedded",
  "no_clawix_canonical_store",
] as const;

const hostCapabilityTests = [
  ...commonContractTests,
  "host_branding",
  "host_specific_audit",
  "host_grants",
] as const;

export const clawDomainOwnershipMatrixV1 = {
  agents: {
    domain: "agents",
    phase: 7,
    status: "contract_defined",
    frameworkOwns: ["agent definitions", "personalities", "connections", "delegation", "runtime bindings", "import/export", "validation"],
    hostOwns: ["host approvals for privileged runtime bindings"],
    clawixUiOwns: ["agent sidebar", "selection", "visual pins", "agent editing chrome"],
    brokerRequired: false,
    destructivePolicy: "explicit_grant_and_audit",
    costPolicy: "host_approval_or_grant",
    requiredTests: commonContractTests,
  },
  skills: {
    domain: "skills",
    phase: 7,
    status: "contract_defined",
    frameworkOwns: ["catalog", "install", "sync", "assignments", "context resolution"],
    hostOwns: ["brokered opt-in sync into external sources"],
    clawixUiOwns: ["catalog browsing", "visual assignment controls", "installation progress UI"],
    brokerRequired: true,
    destructivePolicy: "explicit_grant_and_audit",
    costPolicy: "none",
    requiredTests: commonContractTests,
  },
  design: {
    domain: "design",
    phase: 7,
    status: "contract_defined",
    frameworkOwns: ["styles", "templates", "references", "builtins", "serializers", "render contracts"],
    hostOwns: ["host filesystem access for local references"],
    clawixUiOwns: ["visual editor", "preview chrome", "pure UI caches"],
    brokerRequired: false,
    destructivePolicy: "explicit_grant_and_audit",
    costPolicy: "host_approval_or_grant",
    requiredTests: commonContractTests,
  },
  calendar: {
    domain: "calendar",
    phase: 8,
    status: "contract_defined",
    frameworkOwns: ["schemas", "CLI/API", "event query and mutation contract"],
    hostOwns: ["macOS calendar permission", "native event adapters", "audit", "grants"],
    clawixUiOwns: ["calendar previews", "approval UI", "status projection"],
    brokerRequired: true,
    destructivePolicy: "explicit_grant_and_audit",
    costPolicy: "none",
    requiredTests: [...hostCapabilityTests, "signed_permission_preflight"],
  },
  contacts: {
    domain: "contacts",
    phase: 8,
    status: "contract_defined",
    frameworkOwns: ["schemas", "CLI/API", "contact query and mutation contract"],
    hostOwns: ["macOS contacts permission", "native contacts adapters", "audit", "grants"],
    clawixUiOwns: ["contact previews", "approval UI", "status projection"],
    brokerRequired: true,
    destructivePolicy: "explicit_grant_and_audit",
    costPolicy: "none",
    requiredTests: [...hostCapabilityTests, "signed_permission_preflight"],
  },
  reminders: {
    domain: "reminders",
    phase: 8,
    status: "contract_defined",
    frameworkOwns: ["schemas", "CLI/API", "reminder query and mutation contract"],
    hostOwns: ["macOS reminders permission", "native reminders adapters", "audit", "grants"],
    clawixUiOwns: ["reminder previews", "approval UI", "status projection"],
    brokerRequired: true,
    destructivePolicy: "explicit_grant_and_audit",
    costPolicy: "none",
    requiredTests: [...hostCapabilityTests, "signed_permission_preflight"],
  },
  services: {
    domain: "services",
    phase: 9,
    status: "contract_defined",
    frameworkOwns: ["service ids", "ports", "launch args", "health", "logs", "restart/backoff", "token contract"],
    hostOwns: ["paths", "identity", "installation", "LaunchAgents", "real process start/stop"],
    clawixUiOwns: ["service status", "restart requester UI", "log viewer"],
    brokerRequired: true,
    destructivePolicy: "explicit_grant_and_audit",
    costPolicy: "host_approval_or_grant",
    requiredTests: hostCapabilityTests,
  },
  database: {
    domain: "database",
    phase: 9,
    status: "contract_defined",
    frameworkOwns: ["schema registry", "query/mutation contract", "backup/import/export contract"],
    hostOwns: ["service lifecycle", "host-local database paths", "audit"],
    clawixUiOwns: ["database browser", "status projection"],
    brokerRequired: true,
    destructivePolicy: "explicit_grant_and_audit",
    costPolicy: "none",
    requiredTests: hostCapabilityTests,
  },
  sessions: {
    domain: "sessions",
    phase: 10,
    status: "contract_defined",
    frameworkOwns: ["sessions", "metadata", "search", "streaming/events", "Codex mirror read-only"],
    hostOwns: ["host-specific audit", "external source broker"],
    clawixUiOwns: ["selected thread", "sidebar grouping", "visual pins", "scroll state"],
    brokerRequired: true,
    destructivePolicy: "explicit_grant_and_audit",
    costPolicy: "host_approval_or_grant",
    requiredTests: [...hostCapabilityTests, "codex_read_only"],
  },
  projects: {
    domain: "projects",
    phase: 10,
    status: "contract_defined",
    frameworkOwns: ["projects", "workspaces", "agent-project assignments", "metadata"],
    hostOwns: ["workspace filesystem broker", "audit"],
    clawixUiOwns: ["project picker", "sidebar grouping", "visual filters"],
    brokerRequired: true,
    destructivePolicy: "explicit_grant_and_audit",
    costPolicy: "none",
    requiredTests: hostCapabilityTests,
  },
  memory: {
    domain: "memory",
    phase: 11,
    status: "contract_defined",
    frameworkOwns: ["memory notes", "scopes", "search", "audit", "embeddings/caches derived from framework data"],
    hostOwns: ["external source broker", "host-specific audit"],
    clawixUiOwns: ["memory pickers", "previews", "visual navigation"],
    brokerRequired: true,
    destructivePolicy: "explicit_grant_and_audit",
    costPolicy: "host_approval_or_grant",
    requiredTests: hostCapabilityTests,
  },
  files: {
    domain: "files",
    phase: 11,
    status: "contract_defined",
    frameworkOwns: ["file ingestion", "attachment metadata", "document/index references"],
    hostOwns: ["file permissions", "security-scoped access", "audit", "external source deletes"],
    clawixUiOwns: ["pickers", "previews", "drag/drop", "visual caches"],
    brokerRequired: true,
    destructivePolicy: "explicit_grant_and_audit",
    costPolicy: "none",
    requiredTests: hostCapabilityTests,
  },
  productivity: {
    domain: "productivity",
    phase: 11,
    status: "contract_defined",
    frameworkOwns: ["tasks", "goals", "projects", "events", "workspace search contracts"],
    hostOwns: ["external integrations", "audit"],
    clawixUiOwns: ["productivity views", "filters", "visual grouping"],
    brokerRequired: true,
    destructivePolicy: "explicit_grant_and_audit",
    costPolicy: "none",
    requiredTests: hostCapabilityTests,
  },
  browser: {
    domain: "browser",
    phase: 12,
    status: "contract_defined",
    frameworkOwns: ["browser sessions", "commands", "extraction", "permission model", "automation contract"],
    hostOwns: ["WebView", "cookies", "local browser state", "visible UI"],
    clawixUiOwns: ["browser pane", "right sidebar", "navigation chrome"],
    brokerRequired: true,
    destructivePolicy: "explicit_grant_and_audit",
    costPolicy: "host_approval_or_grant",
    requiredTests: hostCapabilityTests,
  },
  terminal: {
    domain: "terminal",
    phase: 12,
    status: "contract_defined",
    frameworkOwns: ["execution policy", "sessions", "logs", "command API"],
    hostOwns: ["PTY identity", "local process execution", "approvals", "audit"],
    clawixUiOwns: ["terminal UI", "tabs", "visual status"],
    brokerRequired: true,
    destructivePolicy: "explicit_grant_and_audit",
    costPolicy: "host_approval_or_grant",
    requiredTests: hostCapabilityTests,
  },
  voice: {
    domain: "voice",
    phase: 12,
    status: "contract_defined",
    frameworkOwns: ["STT/TTS providers", "rules", "vocabulary", "replacements", "transcript formatting", "audio catalog"],
    hostOwns: ["mic capture", "hotkeys", "overlays", "text injection"],
    clawixUiOwns: ["dictation controls", "voice overlays", "transcript preview"],
    brokerRequired: true,
    destructivePolicy: "none",
    costPolicy: "host_approval_or_grant",
    requiredTests: [...hostCapabilityTests, "signed_permission_preflight"],
  },
  models: {
    domain: "models",
    phase: 12,
    status: "contract_defined",
    frameworkOwns: ["provider catalog", "model catalog", "Ollama-compatible contract", "model API"],
    hostOwns: ["installer", "runtime launch", "LaunchAgent", "logs", "isolation"],
    clawixUiOwns: ["model picker", "runtime status", "install progress"],
    brokerRequired: true,
    destructivePolicy: "explicit_grant_and_audit",
    costPolicy: "host_approval_or_grant",
    requiredTests: hostCapabilityTests,
  },
  integrations: {
    domain: "integrations",
    phase: 12,
    status: "contract_defined",
    frameworkOwns: ["contracts", "CLI/API", "runtime connectors"],
    hostOwns: ["secrets", "approvals", "native permission surfaces"],
    clawixUiOwns: ["integration settings", "connection status", "approval UI"],
    brokerRequired: true,
    destructivePolicy: "explicit_grant_and_audit",
    costPolicy: "host_approval_or_grant",
    requiredTests: hostCapabilityTests,
  },
  secrets: {
    domain: "secrets",
    phase: 9,
    status: "contract_defined",
    frameworkOwns: ["vault contracts", "secret reference model", "capability contracts"],
    hostOwns: ["secret material", "native keychain or vault access", "audit"],
    clawixUiOwns: ["secrets settings", "status projection", "approval UI"],
    brokerRequired: true,
    destructivePolicy: "explicit_grant_and_audit",
    costPolicy: "none",
    requiredTests: hostCapabilityTests,
  },
  system: {
    domain: "system",
    phase: 5,
    status: "contract_defined",
    frameworkOwns: ["capability listing", "grant/revoke CLI contracts", "host registry contract"],
    hostOwns: ["native permission prompts", "LaunchAgents", "Mach services", "audit"],
    clawixUiOwns: ["permission panels", "technical logs", "settings projection"],
    brokerRequired: true,
    destructivePolicy: "explicit_grant_and_audit",
    costPolicy: "none",
    requiredTests: hostCapabilityTests,
  },
  mail: {
    domain: "mail",
    phase: 12,
    status: "contract_defined",
    frameworkOwns: ["mail schemas", "query/send contract", "provider contracts"],
    hostOwns: ["account permissions", "native send surfaces", "audit"],
    clawixUiOwns: ["mail preview", "compose approval UI"],
    brokerRequired: true,
    destructivePolicy: "explicit_grant_and_audit",
    costPolicy: "host_approval_or_grant",
    requiredTests: hostCapabilityTests,
  },
  notes: {
    domain: "notes",
    phase: 12,
    status: "contract_defined",
    frameworkOwns: ["note schemas", "query/mutation contract"],
    hostOwns: ["native notes permissions", "external source broker", "audit"],
    clawixUiOwns: ["note preview", "editor chrome"],
    brokerRequired: true,
    destructivePolicy: "explicit_grant_and_audit",
    costPolicy: "none",
    requiredTests: hostCapabilityTests,
  },
  messages: {
    domain: "messages",
    phase: 12,
    status: "contract_defined",
    frameworkOwns: ["message schemas", "send/read contract"],
    hostOwns: ["native messaging permissions", "send approvals", "audit"],
    clawixUiOwns: ["message preview", "send approval UI"],
    brokerRequired: true,
    destructivePolicy: "explicit_grant_and_audit",
    costPolicy: "host_approval_or_grant",
    requiredTests: hostCapabilityTests,
  },
  mini_apps: {
    domain: "mini_apps",
    phase: 12,
    status: "contract_defined",
    frameworkOwns: ["SDK", "manifest", "permission protocol", "tool-call bridge"],
    hostOwns: ["visual host runtime", "approval surfaces", "sandbox identity"],
    clawixUiOwns: ["mini-app shell", "visual runtime", "navigation"],
    brokerRequired: true,
    destructivePolicy: "explicit_grant_and_audit",
    costPolicy: "host_approval_or_grant",
    requiredTests: hostCapabilityTests,
  },
} as const satisfies Record<ClawDomain, ClawDomainOwnership>;

export const clawDomainOwnershipEntriesV1 = clawDomainSchema.options.map((domain) => clawDomainOwnershipMatrixV1[domain]);
