export interface ProductivityRelationDefinition {
  collectionName: string;
}

export interface ProductivityFieldDefinition {
  name: string;
  type: "text" | "number" | "boolean" | "json" | "select" | "relation" | "date" | "email" | "file";
  required?: boolean;
  options?: string[];
  relation?: ProductivityRelationDefinition;
}

export interface ProductivityIndexDefinition {
  name: string;
  fields: string[];
  unique?: boolean;
}

export interface ProductivityCollectionDefinition {
  name: string;
  displayName: string;
  coreFieldNames: string[];
  fields: ProductivityFieldDefinition[];
  indexes: ProductivityIndexDefinition[];
}

function withWorkspaceMetadataFields(fields: ProductivityFieldDefinition[]): ProductivityFieldDefinition[] {
  return [
    ...fields,
    { name: "source", type: "json" },
    { name: "links", type: "json" },
    { name: "metadata", type: "json" },
    { name: "archivedAt", type: "date" },
  ];
}

export const PRODUCTIVITY_COLLECTION_DEFINITIONS: ProductivityCollectionDefinition[] = [
  {
    name: "areas",
    displayName: "Areas",
    coreFieldNames: ["name", "status"],
    fields: withWorkspaceMetadataFields([
      { name: "name", type: "text", required: true },
      { name: "description", type: "text" },
      { name: "status", type: "select", required: true, options: ["active", "paused", "archived"] },
      { name: "color", type: "text" },
      { name: "ownerPersonId", type: "relation", relation: { collectionName: "people" } },
    ]),
    indexes: [
      { name: "areas_status_idx", fields: ["status"] },
      { name: "areas_owner_idx", fields: ["ownerPersonId"] },
    ],
  },
  {
    name: "people",
    displayName: "People",
    coreFieldNames: ["displayName", "kind"],
    fields: withWorkspaceMetadataFields([
      { name: "displayName", type: "text", required: true },
      { name: "kind", type: "select", required: true, options: ["human", "agent", "org"] },
      { name: "identities", type: "json" },
      { name: "emails", type: "json" },
      { name: "phones", type: "json" },
      { name: "handles", type: "json" },
      { name: "role", type: "text" },
      { name: "organization", type: "text" },
    ]),
    indexes: [{ name: "people_display_name_idx", fields: ["displayName"] }],
  },
  {
    name: "tasks",
    displayName: "Tasks",
    coreFieldNames: ["title", "status"],
    fields: withWorkspaceMetadataFields([
      { name: "title", type: "text", required: true },
      { name: "description", type: "text" },
      { name: "status", type: "select", required: true, options: ["todo", "in_progress", "blocked", "done", "cancelled"] },
      { name: "type", type: "select", options: ["todo", "task", "bug", "story", "feature", "chore"] },
      { name: "priority", type: "select", options: ["low", "medium", "high", "urgent"] },
      { name: "rank", type: "number" },
      { name: "labels", type: "json" },
      { name: "areaId", type: "relation", relation: { collectionName: "areas" } },
      { name: "listId", type: "relation", relation: { collectionName: "lists" } },
      { name: "sectionId", type: "relation", relation: { collectionName: "sections" } },
      { name: "assigneePersonId", type: "relation", relation: { collectionName: "people" } },
      { name: "reporterPersonId", type: "relation", relation: { collectionName: "people" } },
      { name: "watcherPersonIds", type: "json" },
      { name: "startAt", type: "date" },
      { name: "deferUntil", type: "date" },
      { name: "dueAt", type: "date" },
      { name: "deadlineAt", type: "date" },
      { name: "snoozedUntil", type: "date" },
      { name: "recurrenceRule", type: "text" },
      { name: "estimateMinutes", type: "number" },
      { name: "actualMinutes", type: "number" },
      { name: "storyPoints", type: "number" },
      { name: "blockedReason", type: "text" },
      { name: "waitingOn", type: "text" },
      { name: "startedAt", type: "date" },
      { name: "completedAt", type: "date" },
      { name: "cancelledAt", type: "date" },
      { name: "scheduledEventId", type: "relation", relation: { collectionName: "events" } },
      { name: "eventId", type: "relation", relation: { collectionName: "events" } },
      { name: "projectId", type: "relation", relation: { collectionName: "projects" } },
      { name: "goalId", type: "relation", relation: { collectionName: "goals" } },
      { name: "cycleId", type: "relation", relation: { collectionName: "cycles" } },
      { name: "epicId", type: "relation", relation: { collectionName: "epics" } },
      { name: "parentTaskId", type: "relation", relation: { collectionName: "tasks" } },
      { name: "childTaskIds", type: "json" },
      { name: "dependsOnTaskIds", type: "json" },
      { name: "commentIds", type: "json" },
      { name: "attachmentIds", type: "json" },
      { name: "createdBy", type: "text" },
      { name: "updatedBy", type: "text" },
      { name: "assignedToAgentId", type: "text" },
      { name: "assignedBy", type: "text" },
      { name: "delegatedBy", type: "text" },
      { name: "reviewerAgentId", type: "text" },
      { name: "blockedByIds", type: "json" },
      { name: "evidenceIds", type: "json" },
      { name: "decisionIds", type: "json" },
      { name: "assignmentIds", type: "json" },
      { name: "handoffIds", type: "json" },
      { name: "approvalIds", type: "json" },
      { name: "sourceItemId", type: "text" },
      { name: "confidence", type: "number" },
      { name: "handoffTo", type: "text" },
      { name: "approvedBy", type: "text" },
      { name: "companyId", type: "relation", relation: { collectionName: "companies" } },
      { name: "portfolioId", type: "relation", relation: { collectionName: "portfolios" } },
      { name: "portfolioItemId", type: "relation", relation: { collectionName: "portfolio_items" } },
      { name: "checklist", type: "json" },
    ]),
    indexes: [
      { name: "tasks_status_idx", fields: ["status"] },
      { name: "tasks_area_idx", fields: ["areaId"] },
      { name: "tasks_list_idx", fields: ["listId"] },
      { name: "tasks_section_idx", fields: ["sectionId"] },
      { name: "tasks_project_idx", fields: ["projectId"] },
      { name: "tasks_goal_idx", fields: ["goalId"] },
      { name: "tasks_cycle_idx", fields: ["cycleId"] },
      { name: "tasks_epic_idx", fields: ["epicId"] },
    ],
  },
  {
    name: "goals",
    displayName: "Goals",
    coreFieldNames: ["title", "status"],
    fields: withWorkspaceMetadataFields([
      { name: "title", type: "text", required: true },
      { name: "status", type: "select", required: true, options: ["active", "paused", "done"] },
      { name: "description", type: "text" },
      { name: "level", type: "select", options: ["company", "team", "personal"] },
      { name: "areaId", type: "relation", relation: { collectionName: "areas" } },
      { name: "projectId", type: "relation", relation: { collectionName: "projects" } },
      { name: "parentId", type: "relation", relation: { collectionName: "goals" } },
      { name: "parentGoalId", type: "relation", relation: { collectionName: "goals" } },
      { name: "ownerPersonId", type: "relation", relation: { collectionName: "people" } },
      { name: "ownerAgentId", type: "relation", relation: { collectionName: "company_agents" } },
      { name: "companyId", type: "relation", relation: { collectionName: "companies" } },
      { name: "portfolioId", type: "relation", relation: { collectionName: "portfolios" } },
      { name: "portfolioItemId", type: "relation", relation: { collectionName: "portfolio_items" } },
      { name: "metricKey", type: "text" },
      { name: "metricLabel", type: "text" },
      { name: "targetValue", type: "number" },
      { name: "currentValue", type: "number" },
      { name: "unit", type: "text" },
      { name: "period", type: "text" },
      { name: "timeframeStart", type: "date" },
      { name: "timeframeEnd", type: "date" },
      { name: "reviewCadence", type: "select", options: ["daily", "weekly", "monthly", "quarterly"] },
      { name: "metricDirection", type: "select", options: ["increase", "decrease", "maintain"] },
      { name: "healthStatus", type: "select", options: ["green", "yellow", "red", "unknown"] },
    ]),
    indexes: [
      { name: "goals_status_idx", fields: ["status"] },
      { name: "goals_area_idx", fields: ["areaId"] },
      { name: "goals_project_idx", fields: ["projectId"] },
      { name: "goals_company_idx", fields: ["companyId"] },
    ],
  },
  {
    name: "projects",
    displayName: "Projects",
    coreFieldNames: ["name", "status"],
    fields: withWorkspaceMetadataFields([
      { name: "name", type: "text", required: true },
      { name: "status", type: "select", required: true, options: ["draft", "in_progress", "paused", "done", "archived"] },
      { name: "description", type: "text" },
      { name: "areaId", type: "relation", relation: { collectionName: "areas" } },
      { name: "goalId", type: "relation", relation: { collectionName: "goals" } },
      { name: "ownerPersonId", type: "relation", relation: { collectionName: "people" } },
      { name: "leadAgentId", type: "relation", relation: { collectionName: "company_agents" } },
      { name: "companyId", type: "relation", relation: { collectionName: "companies" } },
      { name: "portfolioId", type: "relation", relation: { collectionName: "portfolios" } },
      { name: "portfolioItemId", type: "relation", relation: { collectionName: "portfolio_items" } },
      { name: "color", type: "text" },
      { name: "kind", type: "select", options: ["delivery", "growth", "ops", "research", "migration", "other"] },
      { name: "rank", type: "number" },
      { name: "statusCategory", type: "select", options: ["active", "someday", "planned", "done", "archived"] },
      { name: "healthStatus", type: "select", options: ["green", "yellow", "red", "unknown"] },
      { name: "startAt", type: "date" },
      { name: "targetDate", type: "date" },
      { name: "deadlineAt", type: "date" },
      { name: "startDate", type: "date" },
      { name: "milestoneIds", type: "json" },
      { name: "defaultSectionIds", type: "json" },
      { name: "templateId", type: "relation", relation: { collectionName: "templates" } },
      { name: "reviewAt", type: "date" },
      { name: "reviewCadence", type: "select", options: ["daily", "weekly", "monthly", "quarterly"] },
      { name: "archiveReason", type: "text" },
      { name: "completedAt", type: "date" },
    ]),
    indexes: [
      { name: "projects_status_idx", fields: ["status"] },
      { name: "projects_area_idx", fields: ["areaId"] },
      { name: "projects_goal_idx", fields: ["goalId"] },
      { name: "projects_company_idx", fields: ["companyId"] },
    ],
  },
  {
    name: "lists",
    displayName: "Lists",
    coreFieldNames: ["title", "kind", "status"],
    fields: withWorkspaceMetadataFields([
      { name: "title", type: "text", required: true },
      { name: "kind", type: "select", required: true, options: ["inbox", "today", "upcoming", "anytime", "someday", "backlog", "project", "custom"] },
      { name: "status", type: "select", required: true, options: ["active", "archived"] },
      { name: "description", type: "text" },
      { name: "areaId", type: "relation", relation: { collectionName: "areas" } },
      { name: "projectId", type: "relation", relation: { collectionName: "projects" } },
      { name: "rank", type: "number" },
      { name: "filter", type: "json" },
    ]),
    indexes: [
      { name: "lists_kind_idx", fields: ["kind"] },
      { name: "lists_status_idx", fields: ["status"] },
      { name: "lists_project_idx", fields: ["projectId"] },
    ],
  },
  {
    name: "sections",
    displayName: "Sections",
    coreFieldNames: ["title", "status"],
    fields: withWorkspaceMetadataFields([
      { name: "title", type: "text", required: true },
      { name: "status", type: "select", required: true, options: ["active", "archived"] },
      { name: "description", type: "text" },
      { name: "listId", type: "relation", relation: { collectionName: "lists" } },
      { name: "projectId", type: "relation", relation: { collectionName: "projects" } },
      { name: "areaId", type: "relation", relation: { collectionName: "areas" } },
      { name: "rank", type: "number" },
    ]),
    indexes: [
      { name: "sections_status_idx", fields: ["status"] },
      { name: "sections_list_idx", fields: ["listId"] },
      { name: "sections_project_idx", fields: ["projectId"] },
    ],
  },
  {
    name: "comments",
    displayName: "Comments",
    coreFieldNames: ["entityType", "entityId", "body"],
    fields: withWorkspaceMetadataFields([
      { name: "entityType", type: "select", required: true, options: ["task", "project", "goal", "epic", "cycle", "note", "inbox_thread", "event"] },
      { name: "entityId", type: "text", required: true },
      { name: "body", type: "text", required: true },
      { name: "authorPersonId", type: "relation", relation: { collectionName: "people" } },
      { name: "authorAgentId", type: "text" },
      { name: "visibility", type: "select", options: ["internal", "shared"] },
    ]),
    indexes: [
      { name: "comments_entity_idx", fields: ["entityType", "entityId"] },
      { name: "comments_author_person_idx", fields: ["authorPersonId"] },
    ],
  },
  {
    name: "attachments",
    displayName: "Attachments",
    coreFieldNames: ["title", "entityType", "entityId"],
    fields: withWorkspaceMetadataFields([
      { name: "title", type: "text", required: true },
      { name: "entityType", type: "select", required: true, options: ["task", "project", "goal", "epic", "cycle", "note", "inbox_thread", "event"] },
      { name: "entityId", type: "text", required: true },
      { name: "name", type: "text" },
      { name: "mimeType", type: "text" },
      { name: "uri", type: "text" },
      { name: "path", type: "text" },
      { name: "sizeBytes", type: "number" },
      { name: "preview", type: "text" },
      { name: "uploadedBy", type: "text" },
    ]),
    indexes: [
      { name: "attachments_entity_idx", fields: ["entityType", "entityId"] },
      { name: "attachments_mime_type_idx", fields: ["mimeType"] },
    ],
  },
  {
    name: "saved_views",
    displayName: "Saved Views",
    coreFieldNames: ["name", "domain"],
    fields: withWorkspaceMetadataFields([
      { name: "name", type: "text", required: true },
      { name: "domain", type: "select", required: true, options: ["tasks", "projects", "goals", "inbox", "events", "workspace"] },
      { name: "query", type: "text" },
      { name: "filters", type: "json" },
      { name: "sort", type: "json" },
      { name: "groupBy", type: "text" },
      { name: "favorite", type: "boolean" },
      { name: "rank", type: "number" },
    ]),
    indexes: [
      { name: "saved_views_domain_idx", fields: ["domain"] },
      { name: "saved_views_favorite_idx", fields: ["favorite"] },
    ],
  },
  {
    name: "recurrences",
    displayName: "Recurrences",
    coreFieldNames: ["title", "status", "rule"],
    fields: withWorkspaceMetadataFields([
      { name: "title", type: "text", required: true },
      { name: "status", type: "select", required: true, options: ["active", "paused", "ended"] },
      { name: "rule", type: "text", required: true },
      { name: "timezone", type: "text" },
      { name: "anchorType", type: "select", options: ["task", "project", "goal", "event", "standalone"] },
      { name: "anchorId", type: "text" },
      { name: "nextRunAt", type: "date" },
      { name: "lastRunAt", type: "date" },
    ]),
    indexes: [
      { name: "recurrences_status_idx", fields: ["status"] },
      { name: "recurrences_anchor_idx", fields: ["anchorType", "anchorId"] },
      { name: "recurrences_next_run_idx", fields: ["nextRunAt"] },
    ],
  },
  {
    name: "cycles",
    displayName: "Cycles",
    coreFieldNames: ["name", "status"],
    fields: withWorkspaceMetadataFields([
      { name: "name", type: "text", required: true },
      { name: "status", type: "select", required: true, options: ["planned", "active", "completed", "archived"] },
      { name: "description", type: "text" },
      { name: "teamId", type: "text" },
      { name: "projectId", type: "relation", relation: { collectionName: "projects" } },
      { name: "goalId", type: "relation", relation: { collectionName: "goals" } },
      { name: "startsAt", type: "date" },
      { name: "endsAt", type: "date" },
      { name: "capacityPoints", type: "number" },
      { name: "taskIds", type: "json" },
    ]),
    indexes: [
      { name: "cycles_status_idx", fields: ["status"] },
      { name: "cycles_project_idx", fields: ["projectId"] },
      { name: "cycles_time_idx", fields: ["startsAt", "endsAt"] },
    ],
  },
  {
    name: "epics",
    displayName: "Epics",
    coreFieldNames: ["title", "status", "kind"],
    fields: withWorkspaceMetadataFields([
      { name: "title", type: "text", required: true },
      { name: "status", type: "select", required: true, options: ["planned", "active", "done", "archived"] },
      { name: "kind", type: "select", required: true, options: ["epic", "initiative"] },
      { name: "description", type: "text" },
      { name: "projectId", type: "relation", relation: { collectionName: "projects" } },
      { name: "goalId", type: "relation", relation: { collectionName: "goals" } },
      { name: "ownerPersonId", type: "relation", relation: { collectionName: "people" } },
      { name: "rank", type: "number" },
      { name: "targetDate", type: "date" },
      { name: "healthStatus", type: "select", options: ["green", "yellow", "red", "unknown"] },
      { name: "taskIds", type: "json" },
    ]),
    indexes: [
      { name: "epics_status_idx", fields: ["status"] },
      { name: "epics_kind_idx", fields: ["kind"] },
      { name: "epics_project_idx", fields: ["projectId"] },
    ],
  },
  {
    name: "custom_fields",
    displayName: "Custom Fields",
    coreFieldNames: ["name", "entityType", "fieldType"],
    fields: withWorkspaceMetadataFields([
      { name: "name", type: "text", required: true },
      { name: "entityType", type: "select", required: true, options: ["task", "project", "goal", "epic", "cycle", "person"] },
      { name: "fieldType", type: "select", required: true, options: ["text", "number", "boolean", "date", "select", "multi_select", "person", "relation", "url", "json"] },
      { name: "description", type: "text" },
      { name: "options", type: "json" },
      { name: "required", type: "boolean" },
      { name: "rank", type: "number" },
    ]),
    indexes: [
      { name: "custom_fields_entity_idx", fields: ["entityType"] },
      { name: "custom_fields_name_idx", fields: ["name"] },
    ],
  },
  {
    name: "field_values",
    displayName: "Field Values",
    coreFieldNames: ["fieldId", "entityType", "entityId"],
    fields: withWorkspaceMetadataFields([
      { name: "fieldId", type: "relation", required: true, relation: { collectionName: "custom_fields" } },
      { name: "entityType", type: "select", required: true, options: ["task", "project", "goal", "epic", "cycle", "person"] },
      { name: "entityId", type: "text", required: true },
      { name: "value", type: "json" },
    ]),
    indexes: [
      { name: "field_values_field_idx", fields: ["fieldId"] },
      { name: "field_values_entity_idx", fields: ["entityType", "entityId"] },
    ],
  },
  {
    name: "templates",
    displayName: "Templates",
    coreFieldNames: ["name", "entityType", "status"],
    fields: withWorkspaceMetadataFields([
      { name: "name", type: "text", required: true },
      { name: "entityType", type: "select", required: true, options: ["task", "project", "goal", "epic", "cycle", "note"] },
      { name: "status", type: "select", required: true, options: ["active", "archived"] },
      { name: "description", type: "text" },
      { name: "body", type: "json" },
      { name: "rank", type: "number" },
    ]),
    indexes: [
      { name: "templates_entity_idx", fields: ["entityType"] },
      { name: "templates_status_idx", fields: ["status"] },
    ],
  },
  {
    name: "milestones",
    displayName: "Milestones",
    coreFieldNames: ["title", "status"],
    fields: withWorkspaceMetadataFields([
      { name: "title", type: "text", required: true },
      { name: "description", type: "text" },
      { name: "status", type: "select", required: true, options: ["planned", "active", "done", "archived"] },
      { name: "areaId", type: "relation", relation: { collectionName: "areas" } },
      { name: "projectId", type: "relation", relation: { collectionName: "projects" } },
      { name: "goalId", type: "relation", relation: { collectionName: "goals" } },
      { name: "targetDate", type: "date" },
      { name: "completedAt", type: "date" },
    ]),
    indexes: [
      { name: "milestones_status_idx", fields: ["status"] },
      { name: "milestones_area_idx", fields: ["areaId"] },
      { name: "milestones_project_idx", fields: ["projectId"] },
      { name: "milestones_goal_idx", fields: ["goalId"] },
    ],
  },
  {
    name: "events",
    displayName: "Events",
    coreFieldNames: ["title", "startsAt"],
    fields: withWorkspaceMetadataFields([
      { name: "title", type: "text", required: true },
      { name: "description", type: "text" },
      { name: "startsAt", type: "date", required: true },
      { name: "endsAt", type: "date" },
      { name: "location", type: "text" },
      { name: "attendeePersonIds", type: "json" },
      { name: "linkedTaskIds", type: "json" },
      { name: "linkedNoteIds", type: "json" },
      { name: "reminders", type: "json" },
    ]),
    indexes: [{ name: "events_starts_at_idx", fields: ["startsAt"] }],
  },
  {
    name: "activity_entries",
    displayName: "Activity Entries",
    coreFieldNames: ["entityType", "entityId", "kind", "title"],
    fields: withWorkspaceMetadataFields([
      { name: "entityType", type: "select", required: true, options: ["area", "list", "section", "task", "goal", "project", "comment", "attachment", "saved_view", "recurrence", "cycle", "epic", "custom_field", "field_value", "template", "milestone", "activity_entry", "blocker", "artifact", "decision", "work_session", "assignment", "handoff", "approval", "capacity", "agent", "release", "incident", "feedback_item", "operational_check", "reminder", "deadline", "note", "person", "inbox_thread", "inbox_message", "event"] },
      { name: "entityId", type: "text", required: true },
      { name: "kind", type: "select", required: true, options: ["created", "updated", "completed", "archived", "processed", "commented"] },
      { name: "title", type: "text", required: true },
      { name: "content", type: "text" },
      { name: "areaId", type: "relation", relation: { collectionName: "areas" } },
      { name: "projectId", type: "relation", relation: { collectionName: "projects" } },
      { name: "goalId", type: "relation", relation: { collectionName: "goals" } },
      { name: "milestoneId", type: "relation", relation: { collectionName: "milestones" } },
      { name: "taskId", type: "relation", relation: { collectionName: "tasks" } },
      { name: "threadId", type: "relation", relation: { collectionName: "inbox_threads" } },
      { name: "actor", type: "text" },
    ]),
    indexes: [
      { name: "activity_entries_entity_idx", fields: ["entityType", "entityId"] },
      { name: "activity_entries_kind_idx", fields: ["kind"] },
      { name: "activity_entries_project_idx", fields: ["projectId"] },
      { name: "activity_entries_task_idx", fields: ["taskId"] },
    ],
  },
  {
    name: "blockers",
    displayName: "Blockers",
    coreFieldNames: ["title", "status", "kind"],
    fields: withWorkspaceMetadataFields([
      { name: "title", type: "text", required: true },
      { name: "description", type: "text" },
      { name: "status", type: "select", required: true, options: ["active", "resolved", "cancelled"] },
      { name: "kind", type: "select", required: true, options: ["waiting_human", "waiting_agent", "waiting_system", "missing_context", "policy_block"] },
      { name: "taskId", type: "relation", relation: { collectionName: "tasks" } },
      { name: "projectId", type: "relation", relation: { collectionName: "projects" } },
      { name: "goalId", type: "relation", relation: { collectionName: "goals" } },
      { name: "ownerPersonId", type: "relation", relation: { collectionName: "people" } },
      { name: "ownerAgentId", type: "text" },
      { name: "dependencyTaskIds", type: "json" },
      { name: "evidenceIds", type: "json" },
      { name: "resolvedAt", type: "date" },
      { name: "confidence", type: "number" },
    ]),
    indexes: [
      { name: "blockers_status_idx", fields: ["status"] },
      { name: "blockers_task_idx", fields: ["taskId"] },
      { name: "blockers_project_idx", fields: ["projectId"] },
    ],
  },
  {
    name: "artifacts",
    displayName: "Artifacts",
    coreFieldNames: ["title", "kind"],
    fields: withWorkspaceMetadataFields([
      { name: "title", type: "text", required: true },
      { name: "kind", type: "select", required: true, options: ["link", "file", "command", "test", "screenshot", "message", "note"] },
      { name: "taskId", type: "relation", relation: { collectionName: "tasks" } },
      { name: "projectId", type: "relation", relation: { collectionName: "projects" } },
      { name: "goalId", type: "relation", relation: { collectionName: "goals" } },
      { name: "threadId", type: "relation", relation: { collectionName: "inbox_threads" } },
      { name: "decisionId", type: "relation", relation: { collectionName: "decisions" } },
      { name: "uri", type: "text" },
      { name: "summary", type: "text" },
      { name: "content", type: "text" },
      { name: "confidence", type: "number" },
    ]),
    indexes: [
      { name: "artifacts_task_idx", fields: ["taskId"] },
      { name: "artifacts_project_idx", fields: ["projectId"] },
      { name: "artifacts_decision_idx", fields: ["decisionId"] },
    ],
  },
  {
    name: "decisions",
    displayName: "Decisions",
    coreFieldNames: ["title", "status"],
    fields: withWorkspaceMetadataFields([
      { name: "title", type: "text", required: true },
      { name: "summary", type: "text" },
      { name: "status", type: "select", required: true, options: ["proposed", "accepted", "rejected", "superseded"] },
      { name: "taskId", type: "relation", relation: { collectionName: "tasks" } },
      { name: "projectId", type: "relation", relation: { collectionName: "projects" } },
      { name: "goalId", type: "relation", relation: { collectionName: "goals" } },
      { name: "ownerPersonId", type: "relation", relation: { collectionName: "people" } },
      { name: "ownerAgentId", type: "text" },
      { name: "outcome", type: "text" },
      { name: "rationale", type: "text" },
      { name: "alternatives", type: "json" },
      { name: "artifactIds", type: "json" },
      { name: "confidence", type: "number" },
    ]),
    indexes: [
      { name: "decisions_status_idx", fields: ["status"] },
      { name: "decisions_task_idx", fields: ["taskId"] },
      { name: "decisions_project_idx", fields: ["projectId"] },
    ],
  },
  {
    name: "work_sessions",
    displayName: "Work Sessions",
    coreFieldNames: ["title", "status", "startedAt"],
    fields: withWorkspaceMetadataFields([
      { name: "title", type: "text", required: true },
      { name: "status", type: "select", required: true, options: ["active", "completed", "cancelled"] },
      { name: "objective", type: "text" },
      { name: "taskIds", type: "json" },
      { name: "blockerIds", type: "json" },
      { name: "startedAt", type: "date", required: true },
      { name: "endedAt", type: "date" },
      { name: "outcome", type: "text" },
      { name: "timeboxMinutes", type: "number" },
      { name: "ownerAgentId", type: "text" },
      { name: "confidence", type: "number" },
    ]),
    indexes: [
      { name: "work_sessions_status_idx", fields: ["status"] },
      { name: "work_sessions_started_at_idx", fields: ["startedAt"] },
    ],
  },
  {
    name: "assignments",
    displayName: "Assignments",
    coreFieldNames: ["title", "status", "assignedToAgentId"],
    fields: withWorkspaceMetadataFields([
      { name: "title", type: "text", required: true },
      { name: "status", type: "select", required: true, options: ["proposed", "accepted", "rejected", "released", "completed"] },
      { name: "taskId", type: "relation", relation: { collectionName: "tasks" } },
      { name: "projectId", type: "relation", relation: { collectionName: "projects" } },
      { name: "goalId", type: "relation", relation: { collectionName: "goals" } },
      { name: "assignedToAgentId", type: "text", required: true },
      { name: "assignedBy", type: "text" },
      { name: "delegatedBy", type: "text" },
      { name: "reviewerAgentId", type: "text" },
      { name: "rationale", type: "text" },
      { name: "rejectionReason", type: "text" },
      { name: "acceptedAt", type: "date" },
      { name: "rejectedAt", type: "date" },
      { name: "completedAt", type: "date" },
      { name: "dueAt", type: "date" },
      { name: "priority", type: "select", options: ["low", "medium", "high", "urgent"] },
      { name: "confidence", type: "number" },
    ]),
    indexes: [
      { name: "assignments_status_idx", fields: ["status"] },
      { name: "assignments_agent_idx", fields: ["assignedToAgentId"] },
      { name: "assignments_task_idx", fields: ["taskId"] },
    ],
  },
  {
    name: "handoffs",
    displayName: "Handoffs",
    coreFieldNames: ["title", "status", "toAgentId"],
    fields: withWorkspaceMetadataFields([
      { name: "title", type: "text", required: true },
      { name: "status", type: "select", required: true, options: ["proposed", "accepted", "rejected", "returned", "completed"] },
      { name: "taskId", type: "relation", relation: { collectionName: "tasks" } },
      { name: "projectId", type: "relation", relation: { collectionName: "projects" } },
      { name: "goalId", type: "relation", relation: { collectionName: "goals" } },
      { name: "fromAgentId", type: "text", required: true },
      { name: "toAgentId", type: "text", required: true },
      { name: "objective", type: "text" },
      { name: "currentState", type: "text" },
      { name: "contextSummary", type: "text" },
      { name: "nextStep", type: "text" },
      { name: "riskSummary", type: "text" },
      { name: "artifactIds", type: "json" },
      { name: "blockerIds", type: "json" },
      { name: "approvalId", type: "relation", relation: { collectionName: "approvals" } },
      { name: "rejectionReason", type: "text" },
      { name: "acceptedAt", type: "date" },
      { name: "completedAt", type: "date" },
      { name: "confidence", type: "number" },
    ]),
    indexes: [
      { name: "handoffs_status_idx", fields: ["status"] },
      { name: "handoffs_to_agent_idx", fields: ["toAgentId"] },
      { name: "handoffs_task_idx", fields: ["taskId"] },
    ],
  },
  {
    name: "approvals",
    displayName: "Approvals",
    coreFieldNames: ["title", "status", "kind"],
    fields: withWorkspaceMetadataFields([
      { name: "title", type: "text", required: true },
      { name: "status", type: "select", required: true, options: ["pending", "approved", "rejected", "cancelled"] },
      { name: "kind", type: "select", required: true, options: ["deploy", "publish", "delete", "external_send", "spend", "policy_gate", "other"] },
      { name: "taskId", type: "relation", relation: { collectionName: "tasks" } },
      { name: "projectId", type: "relation", relation: { collectionName: "projects" } },
      { name: "goalId", type: "relation", relation: { collectionName: "goals" } },
      { name: "handoffId", type: "relation", relation: { collectionName: "handoffs" } },
      { name: "requestedByAgentId", type: "text" },
      { name: "approverAgentId", type: "text" },
      { name: "policyReason", type: "text", required: true },
      { name: "evidenceIds", type: "json" },
      { name: "decisionIds", type: "json" },
      { name: "approvedBy", type: "text" },
      { name: "outcome", type: "text" },
      { name: "approvedAt", type: "date" },
      { name: "rejectedAt", type: "date" },
      { name: "confidence", type: "number" },
    ]),
    indexes: [
      { name: "approvals_status_idx", fields: ["status"] },
      { name: "approvals_kind_idx", fields: ["kind"] },
      { name: "approvals_task_idx", fields: ["taskId"] },
    ],
  },
  {
    name: "capacity",
    displayName: "Capacity",
    coreFieldNames: ["title", "status", "agentId"],
    fields: withWorkspaceMetadataFields([
      { name: "title", type: "text", required: true },
      { name: "status", type: "select", required: true, options: ["active", "limited", "overloaded", "offline"] },
      { name: "agentId", type: "text", required: true },
      { name: "teamId", type: "text" },
      { name: "role", type: "text" },
      { name: "availability", type: "select", required: true, options: ["available", "busy", "away", "offline"] },
      { name: "maxWip", type: "number" },
      { name: "currentWip", type: "number", required: true },
      { name: "queueDepth", type: "number", required: true },
      { name: "blockedCount", type: "number", required: true },
      { name: "overdueCount", type: "number", required: true },
      { name: "responseLatencyMinutes", type: "number" },
      { name: "utilization", type: "number" },
      { name: "assignedTaskIds", type: "json" },
      { name: "pendingApprovalIds", type: "json" },
      { name: "pendingHandoffIds", type: "json" },
      { name: "snapshotAt", type: "date" },
      { name: "confidence", type: "number" },
    ]),
    indexes: [
      { name: "capacity_agent_idx", fields: ["agentId"], unique: true },
      { name: "capacity_status_idx", fields: ["status"] },
      { name: "capacity_team_idx", fields: ["teamId"] },
    ],
  },
  {
    name: "agents",
    displayName: "Agents",
    coreFieldNames: ["name", "status", "role"],
    fields: withWorkspaceMetadataFields([
      { name: "name", type: "text", required: true },
      { name: "status", type: "select", required: true, options: ["active", "limited", "offline"] },
      { name: "role", type: "text", required: true },
      { name: "teamId", type: "text" },
      { name: "domains", type: "json" },
      { name: "shift", type: "text" },
      { name: "availability", type: "select", required: true, options: ["available", "busy", "away", "offline"] },
      { name: "autonomyLevel", type: "select", required: true, options: ["observe", "suggest", "act_limited", "act_full"] },
      { name: "permissions", type: "json" },
      { name: "policyGate", type: "select", required: true, options: ["none", "approval_required", "restricted"] },
      { name: "currentFocus", type: "text" },
      { name: "linkedTaskIds", type: "json" },
      { name: "confidence", type: "number" },
    ]),
    indexes: [
      { name: "agents_status_idx", fields: ["status"] },
      { name: "agents_team_idx", fields: ["teamId"] },
      { name: "agents_availability_idx", fields: ["availability"] },
    ],
  },
  {
    name: "releases",
    displayName: "Releases",
    coreFieldNames: ["title", "status"],
    fields: withWorkspaceMetadataFields([
      { name: "title", type: "text", required: true },
      { name: "status", type: "select", required: true, options: ["planned", "active", "at_risk", "released", "cancelled"] },
      { name: "projectId", type: "relation", relation: { collectionName: "projects" } },
      { name: "goalId", type: "relation", relation: { collectionName: "goals" } },
      { name: "ownerAgentId", type: "text" },
      { name: "targetDate", type: "date" },
      { name: "shippedAt", type: "date" },
      { name: "riskSummary", type: "text" },
      { name: "linkedTaskIds", type: "json" },
      { name: "incidentIds", type: "json" },
      { name: "approvalIds", type: "json" },
      { name: "confidence", type: "number" },
    ]),
    indexes: [
      { name: "releases_status_idx", fields: ["status"] },
      { name: "releases_project_idx", fields: ["projectId"] },
      { name: "releases_goal_idx", fields: ["goalId"] },
    ],
  },
  {
    name: "incidents",
    displayName: "Incidents",
    coreFieldNames: ["title", "status", "severity"],
    fields: withWorkspaceMetadataFields([
      { name: "title", type: "text", required: true },
      { name: "status", type: "select", required: true, options: ["open", "investigating", "mitigating", "resolved", "closed"] },
      { name: "severity", type: "select", required: true, options: ["sev1", "sev2", "sev3", "sev4"] },
      { name: "projectId", type: "relation", relation: { collectionName: "projects" } },
      { name: "goalId", type: "relation", relation: { collectionName: "goals" } },
      { name: "taskId", type: "relation", relation: { collectionName: "tasks" } },
      { name: "releaseId", type: "relation", relation: { collectionName: "releases" } },
      { name: "ownerAgentId", type: "text" },
      { name: "summary", type: "text" },
      { name: "customerImpact", type: "text" },
      { name: "blockerIds", type: "json" },
      { name: "feedbackIds", type: "json" },
      { name: "startedAt", type: "date" },
      { name: "resolvedAt", type: "date" },
      { name: "confidence", type: "number" },
    ]),
    indexes: [
      { name: "incidents_status_idx", fields: ["status"] },
      { name: "incidents_severity_idx", fields: ["severity"] },
      { name: "incidents_release_idx", fields: ["releaseId"] },
    ],
  },
  {
    name: "feedback",
    displayName: "Feedback",
    coreFieldNames: ["title", "status", "origin"],
    fields: withWorkspaceMetadataFields([
      { name: "title", type: "text", required: true },
      { name: "status", type: "select", required: true, options: ["new", "triaged", "planned", "closed"] },
      { name: "origin", type: "select", required: true, options: ["customer", "agent", "system", "sales", "support", "ops"] },
      { name: "priority", type: "select", required: true, options: ["low", "medium", "high", "urgent"] },
      { name: "projectId", type: "relation", relation: { collectionName: "projects" } },
      { name: "goalId", type: "relation", relation: { collectionName: "goals" } },
      { name: "taskId", type: "relation", relation: { collectionName: "tasks" } },
      { name: "incidentId", type: "relation", relation: { collectionName: "incidents" } },
      { name: "ownerAgentId", type: "text" },
      { name: "summary", type: "text" },
      { name: "followUpTaskId", type: "relation", relation: { collectionName: "tasks" } },
      { name: "confidence", type: "number" },
    ]),
    indexes: [
      { name: "feedback_status_idx", fields: ["status"] },
      { name: "feedback_priority_idx", fields: ["priority"] },
      { name: "feedback_incident_idx", fields: ["incidentId"] },
    ],
  },
  {
    name: "checks",
    displayName: "Operational Checks",
    coreFieldNames: ["title", "status", "kind"],
    fields: withWorkspaceMetadataFields([
      { name: "title", type: "text", required: true },
      { name: "status", type: "select", required: true, options: ["pending", "passing", "failing", "snoozed"] },
      { name: "kind", type: "select", required: true, options: ["release_readiness", "incident_followup", "sla", "quality", "compliance", "ops"] },
      { name: "projectId", type: "relation", relation: { collectionName: "projects" } },
      { name: "goalId", type: "relation", relation: { collectionName: "goals" } },
      { name: "releaseId", type: "relation", relation: { collectionName: "releases" } },
      { name: "incidentId", type: "relation", relation: { collectionName: "incidents" } },
      { name: "ownerAgentId", type: "text" },
      { name: "cadence", type: "select", options: ["hourly", "daily", "weekly", "monthly"] },
      { name: "lastRunAt", type: "date" },
      { name: "nextRunAt", type: "date" },
      { name: "resultSummary", type: "text" },
      { name: "playbook", type: "text" },
      { name: "confidence", type: "number" },
    ]),
    indexes: [
      { name: "checks_status_idx", fields: ["status"] },
      { name: "checks_kind_idx", fields: ["kind"] },
      { name: "checks_release_idx", fields: ["releaseId"] },
      { name: "checks_incident_idx", fields: ["incidentId"] },
    ],
  },
  {
    name: "reminders",
    displayName: "Reminders",
    coreFieldNames: ["title", "status", "triggerAt"],
    fields: withWorkspaceMetadataFields([
      { name: "title", type: "text", required: true },
      { name: "description", type: "text" },
      { name: "status", type: "select", required: true, options: ["active", "paused", "done", "cancelled"] },
      { name: "triggerAt", type: "date", required: true },
      { name: "anchorType", type: "select", options: ["task", "project", "goal", "event", "thread", "standalone"] },
      { name: "anchorId", type: "text" },
      { name: "channel", type: "text" },
    ]),
    indexes: [
      { name: "reminders_status_idx", fields: ["status"] },
      { name: "reminders_anchor_idx", fields: ["anchorType", "anchorId"] },
      { name: "reminders_trigger_at_idx", fields: ["triggerAt"] },
    ],
  },
  {
    name: "deadlines",
    displayName: "Deadlines",
    coreFieldNames: ["title", "status", "dueAt"],
    fields: withWorkspaceMetadataFields([
      { name: "title", type: "text", required: true },
      { name: "description", type: "text" },
      { name: "status", type: "select", required: true, options: ["active", "paused", "done", "cancelled"] },
      { name: "dueAt", type: "date", required: true },
      { name: "anchorType", type: "select", options: ["task", "project", "goal", "event", "thread", "standalone"] },
      { name: "anchorId", type: "text" },
    ]),
    indexes: [
      { name: "deadlines_status_idx", fields: ["status"] },
      { name: "deadlines_anchor_idx", fields: ["anchorType", "anchorId"] },
      { name: "deadlines_due_at_idx", fields: ["dueAt"] },
    ],
  },
  {
    name: "notes",
    displayName: "Notes",
    coreFieldNames: ["title", "searchText"],
    fields: withWorkspaceMetadataFields([
      { name: "title", type: "text", required: true },
      { name: "blocks", type: "json" },
      { name: "tags", type: "json" },
      { name: "summary", type: "text" },
      { name: "attachments", type: "json" },
      { name: "linkedEntityIds", type: "json" },
      { name: "searchText", type: "text", required: true },
    ]),
    indexes: [{ name: "notes_title_idx", fields: ["title"] }],
  },
  {
    name: "inbox_threads",
    displayName: "Inbox Threads",
    coreFieldNames: ["channel", "status"],
    fields: withWorkspaceMetadataFields([
      { name: "channel", type: "text", required: true },
      { name: "subject", type: "text" },
      { name: "externalThreadId", type: "text" },
      { name: "participantPersonIds", type: "json" },
      { name: "status", type: "select", required: true, options: ["unread", "read", "archived"] },
      { name: "replyTarget", type: "json" },
      { name: "linkedTaskIds", type: "json" },
      { name: "linkedNoteIds", type: "json" },
      { name: "latestMessageAt", type: "date" },
      { name: "preview", type: "text" },
    ]),
    indexes: [
      { name: "inbox_threads_status_idx", fields: ["status"] },
      { name: "inbox_threads_channel_idx", fields: ["channel"] },
    ],
  },
  {
    name: "inbox_messages",
    displayName: "Inbox Messages",
    coreFieldNames: ["threadId", "channel", "status"],
    fields: withWorkspaceMetadataFields([
      { name: "threadId", type: "relation", required: true, relation: { collectionName: "inbox_threads" } },
      { name: "channel", type: "text", required: true },
      { name: "externalThreadId", type: "text" },
      { name: "externalMessageId", type: "text" },
      { name: "participantPersonIds", type: "json" },
      { name: "direction", type: "select", required: true, options: ["inbound", "outbound", "system"] },
      { name: "status", type: "select", required: true, options: ["unread", "read", "archived", "draft", "sent", "failed"] },
      { name: "replyTarget", type: "json" },
      { name: "attachments", type: "json" },
      { name: "linkedTaskIds", type: "json" },
      { name: "linkedNoteIds", type: "json" },
      { name: "content", type: "text", required: true },
    ]),
    indexes: [
      { name: "inbox_messages_thread_idx", fields: ["threadId"] },
      { name: "inbox_messages_status_idx", fields: ["status"] },
    ],
  },
];
