import assert from "node:assert/strict";

import { normalizeConnectorCatalog } from "./catalog.ts";

export const GUILD_FIELD = field("guildId", "string");
export const CHANNEL_FIELD = field("channelId", "string");
export const OVERWRITE_FIELD = field("overwriteId", "string");
export const MESSAGE_FIELD = field("messageId", "string");
export const ANSWER_FIELD = field("answerId", "string");
export const USER_FIELD = field("userId", "string");
export const ROLE_FIELD = field("roleId", "string");
export const INTEGRATION_FIELD = field("integrationId", "string");
export const WEBHOOK_FIELD = field("webhookId", "string");
export const WEBHOOK_TOKEN_FIELD = field("webhookToken", "string");
export const APPLICATION_FIELD = field("applicationId", "string");
export const INTERACTION_FIELD = field("interactionId", "string");
export const INTERACTION_TOKEN_FIELD = field("interactionToken", "string");
export const INSTANCE_FIELD = field("instanceId", "string");
export const COMMAND_FIELD = field("commandId", "string");
export const ENTITLEMENT_FIELD = field("entitlementId", "string");
export const SKU_FIELD = field("skuId", "string");
export const SUBSCRIPTION_FIELD = field("subscriptionId", "string");
export const TEMPLATE_CODE_FIELD = field("templateCode", "string");
export const SOUNDBOARD_SOUND_FIELD = field("soundboardSoundId", "string");
export const STICKER_FIELD = field("stickerId", "string");
export const STICKER_PACK_FIELD = field("stickerPackId", "string");
export const LOBBY_FIELD = field("lobbyId", "string");
export const AUTO_MODERATION_RULE_FIELD = field("autoModerationRuleId", "string");
export const AUTO_MODERATION_ACTIONS_FIELD = field("actions", "array", false, { default: [{ type: 1, metadata: { custom_message: "sample" } }] });
export const AUTO_MODERATION_TRIGGER_METADATA_FIELD = field("triggerMetadata", "object", true, { default: { keyword_filter: ["sample"] } });
export const APPLICATION_COMMAND_METADATA_FIELDS = [
  field("nameLocalizations", "object", true, { default: null }),
  field("descriptionLocalizations", "object", true, { default: null }),
  field("defaultMemberPermissions", "string", true, { default: null }),
  field("defaultPermission", "boolean", true, { default: null }),
  field("dmPermission", "boolean", true, { default: null }),
  field("integrationTypes", "array", true, { default: null }),
  field("contexts", "array", true, { default: null }),
  field("type", "integer", true, { default: null }),
  field("nsfw", "boolean", true, { default: null }),
  field("handler", "integer", true, { default: null }),
];
export const WEBHOOK_CREATE_MESSAGE_FIELDS = [
  field("content", "string"),
  field("username", "string", true, { default: null }),
  field("avatarUrl", "string", true, { default: null }),
  field("tts", "boolean", true, { default: null }),
  field("embeds", "array", true, { default: null }),
  field("allowedMentions", "object", true, { default: null }),
  field("components", "array", true, { default: null }),
  field("attachments", "array", true, { default: null }),
  field("files", "array", true, { default: null }),
  field("flags", "integer", true, { default: null }),
  field("threadName", "string", true, { default: null }),
  field("appliedTags", "array", true, { default: null }),
  field("poll", "object", true, { default: null }),
];
export const WEBHOOK_EDIT_MESSAGE_FIELDS = [
  field("content", "string", true, { default: "sample" }),
  field("embeds", "array", true, { default: null }),
  field("allowedMentions", "object", true, { default: null }),
  field("components", "array", true, { default: null }),
  field("attachments", "array", true, { default: null }),
  field("files", "array", true, { default: null }),
  field("flags", "integer", true, { default: null }),
  field("poll", "object", true, { default: null }),
];
export const ROLE_CREATE_FIELDS = [
  field("name", "string", true, { default: "sample" }),
  field("permissions", "string", true, { default: "0" }),
  field("color", "integer", true, { default: 1 }),
  field("colors", "object", true, { default: { primary_color: 1, secondary_color: null, tertiary_color: null } }),
  field("hoist", "boolean", true, { default: false }),
  field("icon", "string", true, { default: "data:image/png;base64,c2FtcGxl" }),
  field("unicodeEmoji", "string", true, { default: "sample" }),
  field("mentionable", "boolean", true, { default: false }),
  field("auditLogReason", "string", true),
];
export const ROLE_UPDATE_FIELDS = [
  field("name", "string", true, { default: null }),
  field("permissions", "string", true, { default: null }),
  field("color", "integer", true, { default: null }),
  field("colors", "object", true, { default: null }),
  field("hoist", "boolean", true, { default: null }),
  field("icon", "string", true, { default: null }),
  field("unicodeEmoji", "string", true, { default: null }),
  field("mentionable", "boolean", true, { default: null }),
  field("auditLogReason", "string", true),
];
export const CHANNEL_CREATE_FIELDS = [
  GUILD_FIELD,
  field("name", "string"),
  field("type", "integer", true, { default: null }),
  field("topic", "string", true, { default: null }),
  field("bitrate", "integer", true, { default: null }),
  field("userLimit", "integer", true, { default: null }),
  field("rateLimitPerUser", "integer", true, { default: null }),
  field("position", "integer", true, { default: null }),
  field("permissionOverwrites", "array", true, { default: null }),
  field("parentId", "string", true, { default: null }),
  field("nsfw", "boolean", true, { default: null }),
  field("rtcRegion", "string", true, { default: null }),
  field("videoQualityMode", "integer", true, { default: null }),
  field("defaultAutoArchiveDuration", "integer", true, { default: null }),
  field("defaultReactionEmoji", "object", true, { default: null }),
  field("availableTags", "array", true, { default: null }),
  field("defaultSortOrder", "integer", true, { default: null }),
  field("defaultForumLayout", "integer", true, { default: null }),
  field("defaultThreadRateLimitPerUser", "integer", true, { default: null }),
  field("auditLogReason", "string", true),
];
export const CHANNEL_UPDATE_FIELDS = [
  CHANNEL_FIELD,
  field("name", "string", true, { default: "sample" }),
  field("icon", "string", true, { default: null }),
  field("type", "integer", true, { default: 5 }),
  field("position", "integer", true, { default: 1 }),
  field("topic", "string", true, { default: null }),
  field("nsfw", "boolean", true, { default: false }),
  field("rateLimitPerUser", "integer", true, { default: 5 }),
  field("bitrate", "integer", true, { default: 64000 }),
  field("userLimit", "integer", true, { default: 25 }),
  field("permissionOverwrites", "array", true, { default: [{ id: "sample", type: 0, allow: "0", deny: null }] }),
  field("parentId", "string", true, { default: null }),
  field("rtcRegion", "string", true, { default: null }),
  field("videoQualityMode", "integer", true, { default: 2 }),
  field("defaultAutoArchiveDuration", "integer", true, { default: 1440 }),
  field("flags", "integer", true, { default: 16 }),
  field("availableTags", "array", true, { default: [{ name: "sample", moderated: false, emoji_id: null, emoji_name: "sample" }] }),
  field("defaultReactionEmoji", "object", true, { default: null }),
  field("defaultThreadRateLimitPerUser", "integer", true, { default: 10 }),
  field("defaultSortOrder", "integer", true, { default: null }),
  field("defaultForumLayout", "integer", true, { default: 2 }),
  field("archived", "boolean", true, { default: false }),
  field("autoArchiveDuration", "integer", true, { default: 1440 }),
  field("locked", "boolean", true, { default: false }),
  field("invitable", "boolean", true, { default: true }),
  field("appliedTags", "array", true, { default: ["sample"] }),
  field("auditLogReason", "string", true),
];

export const DISCORD_ACTIONS = [
  action("get-current-user", "Get Current User", []),
  action("get-user", "Get User", [USER_FIELD]),
  action("modify-current-user", "Modify Current User", [field("username", "string", true, { default: "sample" }), field("avatar", "string", true), field("banner", "string", true)]),
  action("list-current-user-guilds", "List Current User Guilds", pagingFields()),
  action("get-current-user-guild-member", "Get Current User Guild Member", [GUILD_FIELD], ["discordBearerToken"]),
  action("leave-guild", "Leave Guild", [GUILD_FIELD], ["discordBearerToken"]),
  action("create-dm", "Create DM", [field("recipientId", "string")]),
  action("create-group-dm", "Create Group DM", [field("accessTokens", "array", false, { default: ["sample"] }), field("nicks", "object", false, { default: { sample: "sample" } })], ["discordBearerToken"]),
  action("get-current-user-connections", "Get Current User Connections", [], ["discordBearerToken"]),
  action("get-current-user-application-role-connection", "Get Current User Application Role Connection", [APPLICATION_FIELD], ["discordBearerToken"]),
  action("update-current-user-application-role-connection", "Update Current User Application Role Connection", [APPLICATION_FIELD, field("platformName", "string", true, { default: "sample" }), field("platformUsername", "string", true, { default: "sample" }), field("metadata", "object", true, { default: { score: "100" } })], ["discordBearerToken"]),
  action("get-gateway", "Get Gateway", [], []),
  action("get-gateway-bot", "Get Gateway Bot", []),
  action("get-current-bot-application-information", "Get Current Bot Application Information", []),
  action("get-current-authorization-information", "Get Current Authorization Information", [], ["discordBearerToken"]),
  action("get-guild", "Get Guild", [GUILD_FIELD, field("withCounts", "boolean", true)]),
  action("get-guild-preview", "Get Guild Preview", [GUILD_FIELD]),
  action("modify-guild", "Modify Guild", [GUILD_FIELD, field("name", "string", true, { default: "sample" }), field("verificationLevel", "integer", true, { default: 1 }), field("defaultMessageNotifications", "integer", true, { default: 1 }), field("explicitContentFilter", "integer", true, { default: 1 }), field("afkChannelId", "string", true, { default: "sample" }), field("afkTimeout", "integer", true, { default: 60 }), field("icon", "string", true, { default: "data:image/png;base64,c2FtcGxl" }), field("ownerId", "string", true, { default: "sample" }), field("splash", "string", true, { default: "data:image/png;base64,c2FtcGxl" }), field("discoverySplash", "string", true, { default: "data:image/png;base64,c2FtcGxl" }), field("banner", "string", true, { default: "data:image/png;base64,c2FtcGxl" }), field("systemChannelId", "string", true, { default: "sample" }), field("systemChannelFlags", "integer", true, { default: 0 }), field("rulesChannelId", "string", true, { default: "sample" }), field("publicUpdatesChannelId", "string", true, { default: "sample" }), field("preferredLocale", "string", true, { default: "en-US" }), field("features", "array", true, { default: ["COMMUNITY"] }), field("description", "string", true, { default: "sample" }), field("premiumProgressBarEnabled", "boolean", true, { default: true }), field("safetyAlertsChannelId", "string", true, { default: "sample" }), field("auditLogReason", "string", true)]),
  action("get-guild-voice-regions", "Get Guild Voice Regions", [GUILD_FIELD]),
  action("list-guild-channels", "List Guild Channels", [GUILD_FIELD]),
  action("create-guild-channel", "Create Guild Channel", CHANNEL_CREATE_FIELDS),
  action("modify-guild-channel-positions", "Modify Guild Channel Positions", [GUILD_FIELD, field("positions", "array", false, { default: [{ id: "sample", position: 1, lock_permissions: false, parent_id: "sample" }] }), field("auditLogReason", "string", true)]),
  action("get-guild-template", "Get Guild Template", [TEMPLATE_CODE_FIELD]),
  action("list-guild-templates", "List Guild Templates", [GUILD_FIELD]),
  action("create-guild-template", "Create Guild Template", [GUILD_FIELD, field("name", "string"), field("description", "string", true, { default: null })]),
  action("sync-guild-template", "Sync Guild Template", [GUILD_FIELD, TEMPLATE_CODE_FIELD]),
  action("update-guild-template", "Update Guild Template", [GUILD_FIELD, TEMPLATE_CODE_FIELD, field("name", "string", true, { default: "sample" }), field("description", "string", true, { default: null })]),
  action("delete-guild-template", "Delete Guild Template", [GUILD_FIELD, TEMPLATE_CODE_FIELD]),
  action("send-soundboard-sound", "Send Soundboard Sound", [CHANNEL_FIELD, SOUNDBOARD_SOUND_FIELD, field("sourceGuildId", "string", true)]),
  action("list-default-soundboard-sounds", "List Default Soundboard Sounds", []),
  action("list-guild-soundboard-sounds", "List Guild Soundboard Sounds", [GUILD_FIELD]),
  action("get-guild-soundboard-sound", "Get Guild Soundboard Sound", [GUILD_FIELD, SOUNDBOARD_SOUND_FIELD]),
  action("create-guild-soundboard-sound", "Create Guild Soundboard Sound", [GUILD_FIELD, field("name", "string"), field("sound", "string", false, { default: "data:audio/mpeg;base64,c2FtcGxl" }), field("volume", "number", true, { default: null }), field("emojiId", "string", true, { default: null }), field("emojiName", "string", true, { default: null }), field("auditLogReason", "string", true)]),
  action("update-guild-soundboard-sound", "Update Guild Soundboard Sound", [GUILD_FIELD, SOUNDBOARD_SOUND_FIELD, field("name", "string", true, { default: "sample" }), field("volume", "number", true, { default: 1 }), field("emojiId", "string", true), field("emojiName", "string", true), field("auditLogReason", "string", true)]),
  action("delete-guild-soundboard-sound", "Delete Guild Soundboard Sound", [GUILD_FIELD, SOUNDBOARD_SOUND_FIELD, field("auditLogReason", "string", true)]),
  action("get-current-application", "Get Current Application", []),
  action("edit-current-application", "Edit Current Application", [field("customInstallUrl", "string", true), field("description", "string", true, { default: "sample" }), field("roleConnectionsVerificationUrl", "string", true), field("installParams", "object", true, { default: { scopes: ["bot", "applications.commands"], permissions: "0" } }), field("integrationTypesConfig", "object", true, { default: { "0": { oauth2_install_params: { scopes: ["bot"], permissions: "0" } } } }), field("flags", "integer", true), field("icon", "string", true), field("coverImage", "string", true), field("interactionsEndpointUrl", "string", true), field("tags", "array", true, { default: ["sample"] }), field("eventWebhooksUrl", "string", true), field("eventWebhooksStatus", "integer", true, { default: 1 }), field("eventWebhooksTypes", "array", true)]),
  action("get-application-activity-instance", "Get Application Activity Instance", [APPLICATION_FIELD, INSTANCE_FIELD]),
  action("get-application-role-connection-metadata", "Get Application Role Connection Metadata", [APPLICATION_FIELD]),
  action("update-application-role-connection-metadata", "Update Application Role Connection Metadata", [APPLICATION_FIELD, field("records", "array", false, { default: [{ type: 2, key: "score", name: "Score", description: "Sample score" }] })]),
  action("list-entitlements", "List Entitlements", [APPLICATION_FIELD, field("userId", "string", true), field("skuIds", "array", true, { default: ["sample"] }), field("before", "string", true), field("after", "string", true), field("limit", "integer", true, { default: 1, min: 1, max: 100 }), field("guildId", "string", true), field("excludeEnded", "boolean", true), field("excludeDeleted", "boolean", true)]),
  action("get-entitlement", "Get Entitlement", [APPLICATION_FIELD, ENTITLEMENT_FIELD]),
  action("consume-entitlement", "Consume Entitlement", [APPLICATION_FIELD, ENTITLEMENT_FIELD]),
  action("create-test-entitlement", "Create Test Entitlement", [APPLICATION_FIELD, SKU_FIELD, field("ownerId", "string"), field("ownerType", "integer", false, { default: 1, min: 1, max: 2 })]),
  action("delete-test-entitlement", "Delete Test Entitlement", [APPLICATION_FIELD, ENTITLEMENT_FIELD]),
  action("list-skus", "List SKUs", [APPLICATION_FIELD]),
  action("list-sku-subscriptions", "List SKU Subscriptions", [SKU_FIELD, USER_FIELD, field("before", "string", true), field("after", "string", true), field("limit", "integer", true, { default: 1, min: 1, max: 100 })]),
  action("get-sku-subscription", "Get SKU Subscription", [SKU_FIELD, SUBSCRIPTION_FIELD]),
  action("get-guild-audit-log", "Get Guild Audit Log", [GUILD_FIELD, USER_FIELD, field("actionType", "integer", true, { default: 1 }), field("before", "string", true), field("after", "string", true), field("limit", "integer", true, { default: 1, min: 1, max: 100 })]),
  action("list-guild-emojis", "List Guild Emojis", [GUILD_FIELD]),
  action("get-guild-emoji", "Get Guild Emoji", [GUILD_FIELD, field("emojiId", "string")]),
  action("create-guild-emoji", "Create Guild Emoji", [GUILD_FIELD, field("name", "string"), field("image", "string", false, { default: "data:image/png;base64,c2FtcGxl" }), field("roles", "array", true, { default: ["sample"] }), field("auditLogReason", "string", true)]),
  action("update-guild-emoji", "Update Guild Emoji", [GUILD_FIELD, field("emojiId", "string"), field("name", "string", true, { default: "sample" }), field("roles", "array", true, { default: ["sample"] }), field("auditLogReason", "string", true)]),
  action("delete-guild-emoji", "Delete Guild Emoji", [GUILD_FIELD, field("emojiId", "string"), field("auditLogReason", "string", true)]),
  action("get-sticker", "Get Sticker", [STICKER_FIELD]),
  action("list-sticker-packs", "List Sticker Packs", []),
  action("get-sticker-pack", "Get Sticker Pack", [STICKER_PACK_FIELD]),
  action("list-guild-stickers", "List Guild Stickers", [GUILD_FIELD]),
  action("get-guild-sticker", "Get Guild Sticker", [GUILD_FIELD, STICKER_FIELD]),
  action("create-guild-sticker", "Create Guild Sticker", [GUILD_FIELD, field("name", "string"), field("description", "string"), field("tags", "string"), field("file", "string", false, { default: "sample-file" }), field("auditLogReason", "string", true)]),
  action("update-guild-sticker", "Update Guild Sticker", [GUILD_FIELD, STICKER_FIELD, field("name", "string", true, { default: "sample" }), field("description", "string", true, { default: "sample" }), field("tags", "string", true, { default: "sample" }), field("auditLogReason", "string", true)]),
  action("delete-guild-sticker", "Delete Guild Sticker", [GUILD_FIELD, STICKER_FIELD, field("auditLogReason", "string", true)]),
  action("list-voice-regions", "List Voice Regions", []),
  action("get-current-user-voice-state", "Get Current User Voice State", [GUILD_FIELD]),
  action("get-user-voice-state", "Get User Voice State", [GUILD_FIELD, USER_FIELD]),
  action("modify-current-user-voice-state", "Modify Current User Voice State", [GUILD_FIELD, CHANNEL_FIELD, field("suppress", "boolean", true), field("requestToSpeakTimestamp", "string", true)]),
  action("modify-user-voice-state", "Modify User Voice State", [GUILD_FIELD, USER_FIELD, CHANNEL_FIELD, field("suppress", "boolean", true)]),
  action("create-lobby", "Create Lobby", [field("metadata", "object", true, { default: { topic: "sample" } }), field("members", "array", true, { default: [{ id: "sample" }] }), field("idleTimeoutSeconds", "integer", true, { default: 5, min: 5, max: 604800 })]),
  action("get-lobby", "Get Lobby", [LOBBY_FIELD]),
  action("modify-lobby", "Modify Lobby", [LOBBY_FIELD, field("metadata", "object", true, { default: { topic: "sample" } }), field("members", "array", true, { default: [{ id: "sample" }] }), field("idleTimeoutSeconds", "integer", true, { default: 5, min: 5, max: 604800 })]),
  action("delete-lobby", "Delete Lobby", [LOBBY_FIELD]),
  action("add-lobby-member", "Add Lobby Member", [LOBBY_FIELD, USER_FIELD, field("metadata", "object", true, { default: { role: "sample" } }), field("flags", "integer", true, { default: 1 })]),
  action("bulk-update-lobby-members", "Bulk Update Lobby Members", [LOBBY_FIELD, field("members", "array", false, { default: [{ id: "sample", metadata: { role: "sample" }, flags: 1, remove_member: false }] })]),
  action("remove-lobby-member", "Remove Lobby Member", [LOBBY_FIELD, USER_FIELD]),
  action("leave-lobby", "Leave Lobby", [LOBBY_FIELD], ["discordBearerToken"]),
  action("link-channel-to-lobby", "Link Channel to Lobby", [LOBBY_FIELD, CHANNEL_FIELD], ["discordBearerToken"]),
  action("unlink-channel-from-lobby", "Unlink Channel from Lobby", [LOBBY_FIELD], ["discordBearerToken"]),
  action("update-lobby-message-moderation-metadata", "Update Lobby Message Moderation Metadata", [LOBBY_FIELD, MESSAGE_FIELD, field("metadata", "object", false, { default: { action: "show" } })]),
  action("get-channel", "Get Channel", [CHANNEL_FIELD]),
  action("update-channel", "Update Channel", CHANNEL_UPDATE_FIELDS),
  action("set-voice-channel-status", "Set Voice Channel Status", [CHANNEL_FIELD, field("status", "string", true, { default: "sample" }), field("auditLogReason", "string", true)]),
  action("delete-channel", "Delete Channel", [CHANNEL_FIELD, field("auditLogReason", "string", true)]),
  action("edit-channel-permissions", "Edit Channel Permissions", [CHANNEL_FIELD, OVERWRITE_FIELD, field("allow", "string", true, { default: "0" }), field("deny", "string", true, { default: "0" }), field("permissionType", "integer", false, { default: 0, min: 0, max: 1 }), field("auditLogReason", "string", true)]),
  action("delete-channel-permission", "Delete Channel Permission", [CHANNEL_FIELD, OVERWRITE_FIELD, field("auditLogReason", "string", true)]),
  action("follow-announcement-channel", "Follow Announcement Channel", [CHANNEL_FIELD, field("webhookChannelId", "string"), field("auditLogReason", "string", true)]),
  action("trigger-typing-indicator", "Trigger Typing Indicator", [CHANNEL_FIELD]),
  action("group-dm-add-recipient", "Group DM Add Recipient", [CHANNEL_FIELD, USER_FIELD, field("accessToken", "string", false, { default: "sample-access-token" }), field("nick", "string", true, { default: "sample" })]),
  action("group-dm-remove-recipient", "Group DM Remove Recipient", [CHANNEL_FIELD, USER_FIELD]),
  action("list-messages", "List Messages", [CHANNEL_FIELD, field("around", "string", true, { default: null }), field("before", "string", true, { default: null }), field("after", "string", true, { default: null }), field("limit", "integer", true, { default: 1, min: 1, max: 100 })]),
  action("search-guild-messages", "Search Guild Messages", [
    GUILD_FIELD,
    field("content", "string", true, { default: "sample" }),
    field("limit", "integer", true, { default: 1, min: 1, max: 25 }),
    field("offset", "integer", true, { default: null }),
    field("maxId", "string", true, { default: null }),
    field("minId", "string", true, { default: null }),
    field("slop", "integer", true, { default: null }),
    field("channelIds", "array", true, { default: null }),
    field("authorTypes", "array", true, { default: null }),
    field("authorIds", "array", true, { default: null }),
    field("mentions", "array", true, { default: null }),
    field("mentionRoleIds", "array", true, { default: null }),
    field("mentionEveryone", "boolean", true, { default: null }),
    field("repliedToUserIds", "array", true, { default: null }),
    field("repliedToMessageIds", "array", true, { default: null }),
    field("pinned", "boolean", true, { default: null }),
    field("has", "array", true, { default: null }),
    field("embedTypes", "array", true, { default: null }),
    field("embedProviders", "array", true, { default: null }),
    field("linkHostnames", "array", true, { default: null }),
    field("attachmentFilenames", "array", true, { default: null }),
    field("attachmentExtensions", "array", true, { default: null }),
    field("sortBy", "string", true, { default: null }),
    field("sortOrder", "string", true, { default: null }),
    field("includeNsfw", "boolean", true, { default: null }),
  ]),
  action("get-message", "Get Message", [CHANNEL_FIELD, MESSAGE_FIELD]),
  action("send-message", "Send Message", [
    CHANNEL_FIELD,
    field("content", "string"),
    field("nonce", "string", true, { default: null }),
    field("tts", "boolean", true, { default: null }),
    field("embeds", "array", true, { default: null }),
    field("components", "array", true, { default: null }),
    field("allowedMentions", "object", true, { default: null }),
    field("stickerIds", "array", true, { default: null }),
    field("attachments", "array", true, { default: null }),
    field("files", "array", true, { default: null }),
    field("flags", "integer", true, { default: null }),
    field("enforceNonce", "boolean", true, { default: null }),
    field("poll", "object", true, { default: null }),
    field("sharedClientTheme", "object", true, { default: null }),
    field("messageId", "string", true),
    field("guildId", "string", true),
  ]),
  action("edit-message", "Edit Message", [
    CHANNEL_FIELD,
    MESSAGE_FIELD,
    field("content", "string", true, { default: "sample" }),
    field("embeds", "array", true, { default: null }),
    field("components", "array", true, { default: null }),
    field("allowedMentions", "object", true, { default: null }),
    field("attachments", "array", true, { default: null }),
    field("files", "array", true, { default: null }),
    field("flags", "integer", true, { default: null }),
  ]),
  action("delete-message", "Delete Message", [CHANNEL_FIELD, MESSAGE_FIELD, field("auditLogReason", "string", true)]),
  action("bulk-delete-messages", "Bulk Delete Messages", [CHANNEL_FIELD, field("messages", "array", false, { default: ["sample"] }), field("auditLogReason", "string", true)]),
  action("crosspost-message", "Crosspost Message", [CHANNEL_FIELD, MESSAGE_FIELD]),
  action("list-pinned-messages", "List Pinned Messages", [CHANNEL_FIELD, field("before", "string", true, { default: null }), field("limit", "integer", true, { default: 1, min: 1, max: 50 })]),
  action("pin-message", "Pin Message", [CHANNEL_FIELD, MESSAGE_FIELD, field("auditLogReason", "string", true)]),
  action("unpin-message", "Unpin Message", [CHANNEL_FIELD, MESSAGE_FIELD, field("auditLogReason", "string", true)]),
  action("create-reaction", "Create Reaction", [CHANNEL_FIELD, MESSAGE_FIELD, field("emoji", "string", false, { default: "thumbsup" })]),
  action("delete-own-reaction", "Delete Own Reaction", [CHANNEL_FIELD, MESSAGE_FIELD, field("emoji", "string", false, { default: "thumbsup" })]),
  action("delete-user-reaction", "Delete User Reaction", [CHANNEL_FIELD, MESSAGE_FIELD, USER_FIELD, field("emoji", "string", false, { default: "thumbsup" })]),
  action("list-reactions", "List Reactions", [CHANNEL_FIELD, MESSAGE_FIELD, field("emoji", "string", false, { default: "thumbsup" }), field("after", "string", true, { default: null }), field("limit", "integer", true, { default: 1, min: 1, max: 100 }), field("type", "integer", true, { default: null, min: 0, max: 1 })]),
  action("delete-all-reactions", "Delete All Reactions", [CHANNEL_FIELD, MESSAGE_FIELD]),
  action("delete-all-reactions-for-emoji", "Delete All Reactions For Emoji", [CHANNEL_FIELD, MESSAGE_FIELD, field("emoji", "string", false, { default: "thumbsup" })]),
  action("get-answer-voters", "Get Answer Voters", [CHANNEL_FIELD, MESSAGE_FIELD, ANSWER_FIELD, field("after", "string", true), field("limit", "integer", true, { default: 1, min: 1, max: 100 })]),
  action("end-poll", "End Poll", [CHANNEL_FIELD, MESSAGE_FIELD]),
  action("start-thread-from-message", "Start Thread From Message", [CHANNEL_FIELD, MESSAGE_FIELD, field("name", "string")]),
  action("start-thread-without-message", "Start Thread Without Message", [CHANNEL_FIELD, field("name", "string"), field("type", "integer", true, { default: 11 })]),
  action("start-thread-in-forum-or-media-channel", "Start Thread In Forum Or Media Channel", [CHANNEL_FIELD, field("name", "string"), field("autoArchiveDuration", "integer", true, { default: 60 }), field("rateLimitPerUser", "integer", true, { default: 0 }), field("message", "object", false, { default: { content: "sample" } }), field("appliedTags", "array", true, { default: ["sample"] }), field("auditLogReason", "string", true)]),
  action("list-active-threads", "List Active Threads", [GUILD_FIELD]),
  action("list-public-archived-threads", "List Public Archived Threads", [CHANNEL_FIELD, field("before", "string", true, { default: "2026-05-13T10:00:00.000Z" }), field("limit", "integer", true, { default: 1, min: 1 })]),
  action("list-private-archived-threads", "List Private Archived Threads", [CHANNEL_FIELD, field("before", "string", true, { default: "2026-05-13T10:00:00.000Z" }), field("limit", "integer", true, { default: 1, min: 1 })]),
  action("list-joined-private-archived-threads", "List Joined Private Archived Threads", [CHANNEL_FIELD, field("before", "string", true), field("limit", "integer", true, { default: 1, min: 1 })]),
  action("join-thread", "Join Thread", [CHANNEL_FIELD]),
  action("leave-thread", "Leave Thread", [CHANNEL_FIELD]),
  action("add-thread-member", "Add Thread Member", [CHANNEL_FIELD, USER_FIELD]),
  action("remove-thread-member", "Remove Thread Member", [CHANNEL_FIELD, USER_FIELD]),
  action("get-thread-member", "Get Thread Member", [CHANNEL_FIELD, USER_FIELD, field("withMember", "boolean", true)]),
  action("list-thread-members", "List Thread Members", [CHANNEL_FIELD, field("withMember", "boolean", true), field("limit", "integer", true, { default: 1, min: 1, max: 100 })]),
  action("add-guild-member", "Add Guild Member", [GUILD_FIELD, USER_FIELD, field("accessToken", "string", false, { default: "sample-access-token" }), field("nick", "string", true, { default: "sample" }), field("roles", "array", true, { default: ["sample"] }), field("mute", "boolean", true), field("deaf", "boolean", true)]),
  action("list-guild-members", "List Guild Members", [GUILD_FIELD, field("limit", "integer", true, { default: 1, min: 1, max: 100 })]),
  action("get-guild-member", "Get Guild Member", [GUILD_FIELD, USER_FIELD]),
  action("search-guild-members", "Search Guild Members", [GUILD_FIELD, field("query", "string"), field("limit", "integer", true, { default: 1, min: 1, max: 100 })]),
  action("modify-guild-member", "Modify Guild Member", [GUILD_FIELD, USER_FIELD, field("nick", "string", true, { default: "sample" }), field("roles", "array", true), field("mute", "boolean", true), field("deaf", "boolean", true), field("voiceChannelId", "string", true), field("communicationDisabledUntil", "string", true), field("flags", "integer", true), field("auditLogReason", "string", true)]),
  action("modify-current-member", "Modify Current Member", [GUILD_FIELD, field("nick", "string", true, { default: "sample" }), field("avatar", "string", true, { default: "data:image/png;base64,c2FtcGxl" }), field("banner", "string", true, { default: "data:image/png;base64,c2FtcGxl" }), field("bio", "string", true, { default: "sample" }), field("auditLogReason", "string", true)]),
  action("modify-current-user-nick", "Modify Current User Nick", [GUILD_FIELD, field("nick", "string"), field("auditLogReason", "string", true)]),
  action("remove-guild-member", "Remove Guild Member", [GUILD_FIELD, USER_FIELD, field("auditLogReason", "string", true)]),
  action("list-guild-roles", "List Guild Roles", [GUILD_FIELD]),
  action("get-guild-role", "Get Guild Role", [GUILD_FIELD, ROLE_FIELD]),
  action("get-guild-role-member-counts", "Get Guild Role Member Counts", [GUILD_FIELD]),
  action("create-guild-role", "Create Guild Role", [GUILD_FIELD, ...ROLE_CREATE_FIELDS]),
  action("modify-guild-role-positions", "Modify Guild Role Positions", [GUILD_FIELD, field("positions", "array", false, { default: [{ id: "sample", position: 1 }] }), field("auditLogReason", "string", true)]),
  action("update-guild-role", "Update Guild Role", [GUILD_FIELD, ROLE_FIELD, ...ROLE_UPDATE_FIELDS]),
  action("delete-guild-role", "Delete Guild Role", [GUILD_FIELD, ROLE_FIELD, field("auditLogReason", "string", true)]),
  action("add-guild-member-role", "Add Guild Member Role", [GUILD_FIELD, USER_FIELD, ROLE_FIELD, field("auditLogReason", "string", true)]),
  action("remove-guild-member-role", "Remove Guild Member Role", [GUILD_FIELD, USER_FIELD, ROLE_FIELD, field("auditLogReason", "string", true)]),
  action("list-guild-bans", "List Guild Bans", [GUILD_FIELD, field("limit", "integer", true, { default: 1, min: 1, max: 100 })]),
  action("get-guild-ban", "Get Guild Ban", [GUILD_FIELD, USER_FIELD]),
  action("create-guild-ban", "Create Guild Ban", [GUILD_FIELD, USER_FIELD, field("deleteMessageSeconds", "integer", true, { default: 0, min: 0 })]),
  action("remove-guild-ban", "Remove Guild Ban", [GUILD_FIELD, USER_FIELD]),
  action("bulk-ban-guild-users", "Bulk Ban Guild Users", [GUILD_FIELD, field("userIds", "array", false, { default: ["sample"] }), field("deleteMessageSeconds", "integer", true, { default: 0, min: 0 }), field("auditLogReason", "string", true)]),
  action("get-guild-prune-count", "Get Guild Prune Count", [GUILD_FIELD, field("days", "integer", true, { default: 7, min: 1 }), field("includeRoles", "array", true, { default: ["sample"] })]),
  action("begin-guild-prune", "Begin Guild Prune", [GUILD_FIELD, field("days", "integer", true, { default: 7, min: 1 }), field("computePruneCount", "boolean", true, { default: true }), field("includeRoles", "array", true, { default: ["sample"] }), field("auditLogReason", "string", true)]),
  action("get-guild-integrations", "Get Guild Integrations", [GUILD_FIELD]),
  action("delete-guild-integration", "Delete Guild Integration", [GUILD_FIELD, INTEGRATION_FIELD, field("auditLogReason", "string", true)]),
  action("get-guild-widget-settings", "Get Guild Widget Settings", [GUILD_FIELD]),
  action("modify-guild-widget", "Modify Guild Widget", [GUILD_FIELD, field("enabled", "boolean", true, { default: true }), field("channelId", "string", true, { default: "sample" }), field("auditLogReason", "string", true)]),
  action("get-guild-widget", "Get Guild Widget", [GUILD_FIELD]),
  action("get-guild-vanity-url", "Get Guild Vanity URL", [GUILD_FIELD]),
  action("get-guild-welcome-screen", "Get Guild Welcome Screen", [GUILD_FIELD]),
  action("modify-guild-welcome-screen", "Modify Guild Welcome Screen", [GUILD_FIELD, field("enabled", "boolean", true, { default: true }), field("welcomeChannels", "array", true, { default: [{ channel_id: "sample", description: "sample" }] }), field("description", "string", true, { default: "sample" }), field("auditLogReason", "string", true)]),
  action("get-guild-onboarding", "Get Guild Onboarding", [GUILD_FIELD]),
  action("modify-guild-onboarding", "Modify Guild Onboarding", [GUILD_FIELD, field("prompts", "array", true, { default: [{ id: "sample", type: 0, options: [], title: "sample", single_select: true, required: false, in_onboarding: true }] }), field("defaultChannelIds", "array", true, { default: ["sample"] }), field("enabled", "boolean", true, { default: true }), field("mode", "integer", true, { default: 0 }), field("auditLogReason", "string", true)]),
  action("modify-guild-incident-actions", "Modify Guild Incident Actions", [GUILD_FIELD, field("invitesDisabledUntil", "string", true, { default: null }), field("dmsDisabledUntil", "string", true, { default: "2026-05-13T14:00:00.000Z" })]),
  action("list-auto-moderation-rules", "List Auto Moderation Rules", [GUILD_FIELD]),
  action("get-auto-moderation-rule", "Get Auto Moderation Rule", [GUILD_FIELD, AUTO_MODERATION_RULE_FIELD]),
  action("create-auto-moderation-rule", "Create Auto Moderation Rule", [GUILD_FIELD, field("name", "string"), field("eventType", "integer", false, { default: 1 }), field("triggerType", "integer", false, { default: 1 }), AUTO_MODERATION_TRIGGER_METADATA_FIELD, AUTO_MODERATION_ACTIONS_FIELD, field("enabled", "boolean", true), field("exemptRoles", "array", true, { default: ["sample"] }), field("exemptChannels", "array", true, { default: ["sample"] }), field("auditLogReason", "string", true)]),
  action("update-auto-moderation-rule", "Update Auto Moderation Rule", [GUILD_FIELD, AUTO_MODERATION_RULE_FIELD, field("name", "string", true, { default: "sample" }), field("eventType", "integer", true, { default: 1 }), AUTO_MODERATION_TRIGGER_METADATA_FIELD, field("actions", "array", true, { default: [{ type: 1, metadata: { custom_message: "sample" } }] }), field("enabled", "boolean", true), field("exemptRoles", "array", true, { default: ["sample"] }), field("exemptChannels", "array", true, { default: ["sample"] }), field("auditLogReason", "string", true)]),
  action("delete-auto-moderation-rule", "Delete Auto Moderation Rule", [GUILD_FIELD, AUTO_MODERATION_RULE_FIELD, field("auditLogReason", "string", true)]),
  action("list-guild-invites", "List Guild Invites", [GUILD_FIELD]),
  action("list-channel-invites", "List Channel Invites", [CHANNEL_FIELD]),
  action("create-channel-invite", "Create Channel Invite", [CHANNEL_FIELD, field("maxAge", "integer", true, { default: 86400, min: 0, max: 604800 }), field("maxUses", "integer", true, { default: 0, min: 0, max: 100 }), field("temporary", "boolean", true), field("unique", "boolean", true), field("targetType", "integer", true, { default: null }), field("targetUserId", "string", true, { default: null }), field("targetApplicationId", "string", true, { default: null }), field("payloadJson", "string", true, { default: "{\"max_age\":3600}" }), field("roleIds", "array", true, { default: null }), field("auditLogReason", "string", true)]),
  action("list-guild-scheduled-events", "List Guild Scheduled Events", [GUILD_FIELD, field("withUserCount", "boolean", true)]),
  action("create-guild-scheduled-event", "Create Guild Scheduled Event", [
    GUILD_FIELD,
    field("channelId", "string", true, { default: "sample" }),
    field("entityMetadata", "object", true),
    field("name", "string"),
    field("privacyLevel", "integer", false, { default: 2 }),
    field("scheduledStartTime", "string", false, { default: "2026-05-13T10:00:00.000Z" }),
    field("scheduledEndTime", "string", true, { default: "2026-05-13T11:00:00.000Z" }),
    field("entityType", "integer", false, { default: 2 }),
    field("description", "string", true, { default: "sample" }),
    field("image", "string", true, { default: null }),
    field("recurrenceRule", "object", true),
    field("auditLogReason", "string", true),
  ]),
  action("get-guild-scheduled-event", "Get Guild Scheduled Event", [GUILD_FIELD, field("guildScheduledEventId", "string"), field("withUserCount", "boolean", true)]),
  action("update-guild-scheduled-event", "Update Guild Scheduled Event", [
    GUILD_FIELD,
    field("guildScheduledEventId", "string"),
    field("channelId", "string", true, { default: "sample" }),
    field("entityMetadata", "object", true),
    field("name", "string", true, { default: "sample" }),
    field("privacyLevel", "integer", true, { default: 2 }),
    field("scheduledStartTime", "string", true, { default: "2026-05-13T10:00:00.000Z" }),
    field("scheduledEndTime", "string", true, { default: "2026-05-13T11:00:00.000Z" }),
    field("entityType", "integer", true, { default: 2 }),
    field("description", "string", true, { default: "sample" }),
    field("status", "integer", true, { default: 2 }),
    field("image", "string", true, { default: null }),
    field("recurrenceRule", "object", true),
    field("auditLogReason", "string", true),
  ]),
  action("delete-guild-scheduled-event", "Delete Guild Scheduled Event", [GUILD_FIELD, field("guildScheduledEventId", "string")]),
  action("list-guild-scheduled-event-users", "List Guild Scheduled Event Users", [GUILD_FIELD, field("guildScheduledEventId", "string"), field("limit", "integer", true, { default: 1, min: 1, max: 100 }), field("withMember", "boolean", true), field("before", "string", true, { default: null }), field("after", "string", true, { default: null })]),
  action("create-stage-instance", "Create Stage Instance", [CHANNEL_FIELD, field("topic", "string"), field("privacyLevel", "integer", true, { default: 2 }), field("sendStartNotification", "boolean", true), field("guildScheduledEventId", "string", true), field("auditLogReason", "string", true)]),
  action("get-stage-instance", "Get Stage Instance", [CHANNEL_FIELD]),
  action("update-stage-instance", "Update Stage Instance", [CHANNEL_FIELD, field("topic", "string", true, { default: "sample" }), field("privacyLevel", "integer", true, { default: 2 }), field("auditLogReason", "string", true)]),
  action("delete-stage-instance", "Delete Stage Instance", [CHANNEL_FIELD, field("auditLogReason", "string", true)]),
  action("get-invite", "Get Invite", [field("inviteCode", "string"), field("withCounts", "boolean", true), field("withExpiration", "boolean", true), field("guildScheduledEventId", "string", true, { default: null })]),
  action("delete-invite", "Delete Invite", [field("inviteCode", "string")]),
  action("get-invite-target-users", "Get Invite Target Users", [field("inviteCode", "string")]),
  action("update-invite-target-users", "Update Invite Target Users", [field("inviteCode", "string"), field("targetUsersFile", "string", false, { default: "user_id\n123" })]),
  action("get-invite-target-users-job-status", "Get Invite Target Users Job Status", [field("inviteCode", "string")]),
  action("list-channel-webhooks", "List Channel Webhooks", [CHANNEL_FIELD]),
  action("list-guild-webhooks", "List Guild Webhooks", [GUILD_FIELD]),
  action("create-webhook", "Create Webhook", [CHANNEL_FIELD, field("name", "string"), field("avatar", "string", true), field("auditLogReason", "string", true)]),
  action("get-webhook", "Get Webhook", [WEBHOOK_FIELD]),
  action("update-webhook", "Update Webhook", [WEBHOOK_FIELD, field("name", "string", true, { default: "sample" }), field("avatar", "string", true), field("targetChannelId", "string", true), field("auditLogReason", "string", true)]),
  action("delete-webhook", "Delete Webhook", [WEBHOOK_FIELD, field("auditLogReason", "string", true)]),
  action("get-webhook-with-token", "Get Webhook With Token", [WEBHOOK_FIELD, WEBHOOK_TOKEN_FIELD], []),
  action("update-webhook-with-token", "Update Webhook With Token", [WEBHOOK_FIELD, WEBHOOK_TOKEN_FIELD, field("name", "string", true, { default: "sample" }), field("avatar", "string", true)], []),
  action("delete-webhook-with-token", "Delete Webhook With Token", [WEBHOOK_FIELD, WEBHOOK_TOKEN_FIELD], []),
  action("execute-webhook", "Execute Webhook", [WEBHOOK_FIELD, WEBHOOK_TOKEN_FIELD, ...WEBHOOK_CREATE_MESSAGE_FIELDS, field("wait", "boolean", true), field("threadId", "string", true, { default: null }), field("withComponents", "boolean", true)], []),
  action("execute-slack-compatible-webhook", "Execute Slack-Compatible Webhook", [WEBHOOK_FIELD, WEBHOOK_TOKEN_FIELD, field("payload", "object", false, { default: { text: "sample" } }), field("wait", "boolean", true), field("threadId", "string", true)], []),
  action("execute-github-compatible-webhook", "Execute GitHub-Compatible Webhook", [WEBHOOK_FIELD, WEBHOOK_TOKEN_FIELD, field("payload", "object", false, { default: { ref: "refs/heads/main" } }), field("wait", "boolean", true), field("threadId", "string", true)], []),
  action("get-webhook-message", "Get Webhook Message", [WEBHOOK_FIELD, WEBHOOK_TOKEN_FIELD, MESSAGE_FIELD, field("threadId", "string", true)], []),
  action("edit-webhook-message", "Edit Webhook Message", [WEBHOOK_FIELD, WEBHOOK_TOKEN_FIELD, MESSAGE_FIELD, ...WEBHOOK_EDIT_MESSAGE_FIELDS, field("threadId", "string", true, { default: null }), field("withComponents", "boolean", true)], []),
  action("delete-webhook-message", "Delete Webhook Message", [WEBHOOK_FIELD, WEBHOOK_TOKEN_FIELD, MESSAGE_FIELD, field("threadId", "string", true)], []),
  action("create-interaction-response", "Create Interaction Response", [INTERACTION_FIELD, INTERACTION_TOKEN_FIELD, field("responseType", "integer", false, { default: 4 }), field("responseData", "object", true, { default: { content: "sample" } }), field("withResponse", "boolean", true)], []),
  action("get-original-interaction-response", "Get Original Interaction Response", [APPLICATION_FIELD, INTERACTION_TOKEN_FIELD], []),
  action("edit-original-interaction-response", "Edit Original Interaction Response", [APPLICATION_FIELD, INTERACTION_TOKEN_FIELD, ...WEBHOOK_EDIT_MESSAGE_FIELDS], []),
  action("delete-original-interaction-response", "Delete Original Interaction Response", [APPLICATION_FIELD, INTERACTION_TOKEN_FIELD], []),
  action("create-followup-message", "Create Followup Message", [APPLICATION_FIELD, INTERACTION_TOKEN_FIELD, ...WEBHOOK_CREATE_MESSAGE_FIELDS], []),
  action("get-followup-message", "Get Followup Message", [APPLICATION_FIELD, INTERACTION_TOKEN_FIELD, MESSAGE_FIELD], []),
  action("edit-followup-message", "Edit Followup Message", [APPLICATION_FIELD, INTERACTION_TOKEN_FIELD, MESSAGE_FIELD, ...WEBHOOK_EDIT_MESSAGE_FIELDS], []),
  action("delete-followup-message", "Delete Followup Message", [APPLICATION_FIELD, INTERACTION_TOKEN_FIELD, MESSAGE_FIELD], []),
  action("list-global-application-commands", "List Global Application Commands", [APPLICATION_FIELD]),
  action("create-global-application-command", "Create Global Application Command", [APPLICATION_FIELD, field("name", "string"), field("description", "string", true, { default: "sample" }), ...APPLICATION_COMMAND_METADATA_FIELDS]),
  action("get-global-application-command", "Get Global Application Command", [APPLICATION_FIELD, COMMAND_FIELD]),
  action("update-global-application-command", "Update Global Application Command", [APPLICATION_FIELD, COMMAND_FIELD, field("name", "string"), field("description", "string", true, { default: "sample" }), ...APPLICATION_COMMAND_METADATA_FIELDS]),
  action("delete-global-application-command", "Delete Global Application Command", [APPLICATION_FIELD, COMMAND_FIELD]),
  action("bulk-overwrite-global-application-commands", "Bulk Overwrite Global Application Commands", [APPLICATION_FIELD, field("commands", "array", false, { default: [{ name: "sample", description: "sample", type: 1 }] })]),
  action("list-application-emojis", "List Application Emojis", [APPLICATION_FIELD]),
  action("get-application-emoji", "Get Application Emoji", [APPLICATION_FIELD, field("emojiId", "string")]),
  action("create-application-emoji", "Create Application Emoji", [APPLICATION_FIELD, field("name", "string"), field("image", "string", false, { default: "data:image/png;base64,c2FtcGxl" })]),
  action("update-application-emoji", "Update Application Emoji", [APPLICATION_FIELD, field("emojiId", "string"), field("name", "string", true, { default: "sample" })]),
  action("delete-application-emoji", "Delete Application Emoji", [APPLICATION_FIELD, field("emojiId", "string")]),
  action("list-guild-application-commands", "List Guild Application Commands", [APPLICATION_FIELD, GUILD_FIELD]),
  action("create-guild-application-command", "Create Guild Application Command", [APPLICATION_FIELD, GUILD_FIELD, field("name", "string"), field("description", "string", true, { default: "sample" }), ...APPLICATION_COMMAND_METADATA_FIELDS]),
  action("get-guild-application-command", "Get Guild Application Command", [APPLICATION_FIELD, GUILD_FIELD, COMMAND_FIELD]),
  action("update-guild-application-command", "Update Guild Application Command", [APPLICATION_FIELD, GUILD_FIELD, COMMAND_FIELD, field("name", "string"), field("description", "string", true, { default: "sample" }), ...APPLICATION_COMMAND_METADATA_FIELDS]),
  action("delete-guild-application-command", "Delete Guild Application Command", [APPLICATION_FIELD, GUILD_FIELD, COMMAND_FIELD]),
  action("bulk-overwrite-guild-application-commands", "Bulk Overwrite Guild Application Commands", [APPLICATION_FIELD, GUILD_FIELD, field("commands", "array", false, { default: [{ name: "sample", description: "sample", type: 1 }] })]),
  action("get-guild-application-command-permissions", "Get Guild Application Command Permissions", [APPLICATION_FIELD, GUILD_FIELD], ["discordBearerToken"]),
  action("get-application-command-permissions", "Get Application Command Permissions", [APPLICATION_FIELD, GUILD_FIELD, COMMAND_FIELD], ["discordBearerToken"]),
  action("edit-application-command-permissions", "Edit Application Command Permissions", [APPLICATION_FIELD, GUILD_FIELD, COMMAND_FIELD, field("permissions", "array", false, { default: [{ id: "sample", type: 1, permission: true }] })], ["discordBearerToken"]),
];

export const DISCORD_CATALOG = normalizeConnectorCatalog({
  version: 1,
  apps: [{
    id: "discord",
    name: "Discord",
    authFieldNames: ["discordBotToken", "discordBearerToken"],
    fields: [{
      name: "discordBotToken",
      type: "app",
      optional: false,
      secret: true,
    }, {
      name: "discordBearerToken",
      type: "app",
      optional: false,
      secret: true,
    }],
    operations: DISCORD_ACTIONS,
  }],
});

export function operation(operationId: string) {
  const found = DISCORD_CATALOG.apps[0]?.operations.find((candidate) => candidate.id === operationId);
  assert.ok(found);
  return found;
}

export function action(id: string, name: string, fields: Field[], authFieldNames = ["discordBotToken"]) {
  return {
    id: `discord.action.${id}`,
    appId: "discord",
    kind: "action" as const,
    name,
    fields,
    authFieldNames,
  };
}

export type Field = {
  name: string;
  type: string;
  optional: boolean;
  default?: unknown;
  min?: number;
  max?: number;
};

export function field(name: string, type: string, optional = false, extras: {
  default?: unknown;
  min?: number;
  max?: number;
} = {}): Field {
  return { name, type, optional, ...extras };
}

export function pagingFields(): Field[] {
  return [
    field("limit", "integer", true, { default: 1, min: 1, max: 100 }),
    field("after", "string", true),
    field("before", "string", true),
  ];
}
