import {
  arrayField,
  CALENDAR,
  channelFields,
  eventFields,
  objectField,
  PAGE,
  spec,
  stringField,
  type GoogleOperationSpec,
} from "./google-operation-core.ts";

const EVENT = [stringField("eventId", { default: "event-123" })];
const ACL_RULE = [stringField("ruleId", { default: "user:reader@example.invalid" })];

export const GOOGLE_CALENDAR_ACTION_SPECS = [
  spec("list-calendars", "GET", "calendar/v3/users/me/calendarList", PAGE, { query: ["maxResults", "pageToken"], requiredPaths: ["items"], pageItems: "items" }),
  spec("get-calendar-list-entry", "GET", "calendar/v3/users/me/calendarList/{calendarId}", CALENDAR, { requiredPaths: ["id", "summary"] }),
  spec("insert-calendar-list-entry", "POST", "calendar/v3/users/me/calendarList", [stringField("id", { default: "calendar@example.invalid" })], { body: ["id"], requiredPaths: ["id"] }),
  spec("update-calendar-list-entry", "PUT", "calendar/v3/users/me/calendarList/{calendarId}", [...CALENDAR, stringField("summaryOverride", { default: "Work" })], { body: ["summaryOverride"], requiredPaths: ["id"] }),
  spec("patch-calendar-list-entry", "PATCH", "calendar/v3/users/me/calendarList/{calendarId}", [...CALENDAR, stringField("summaryOverride", { default: "Work" })], { body: ["summaryOverride"], requiredPaths: ["id"] }),
  spec("delete-calendar-list-entry", "DELETE", "calendar/v3/users/me/calendarList/{calendarId}", CALENDAR),
  spec("watch-calendar-list", "POST", "calendar/v3/users/me/calendarList/watch", channelFields(), { body: ["id", "type", "address", "token", "expiration"], requiredPaths: ["id", "resourceId"] }),
  spec("create-calendar", "POST", "calendar/v3/calendars", [stringField("summary", { default: "Team Calendar" }), stringField("timeZone", { optional: true, default: "UTC" })], { body: ["summary", "timeZone"], requiredPaths: ["id", "summary"] }),
  spec("get-calendar", "GET", "calendar/v3/calendars/{calendarId}", CALENDAR, { requiredPaths: ["id", "summary"] }),
  spec("update-calendar", "PUT", "calendar/v3/calendars/{calendarId}", [...CALENDAR, stringField("summary", { default: "Updated Calendar" })], { body: ["summary"], requiredPaths: ["id", "summary"] }),
  spec("patch-calendar", "PATCH", "calendar/v3/calendars/{calendarId}", [...CALENDAR, stringField("summary", { default: "Patched Calendar" })], { body: ["summary"], requiredPaths: ["id", "summary"] }),
  spec("delete-calendar", "DELETE", "calendar/v3/calendars/{calendarId}", CALENDAR),
  spec("clear-calendar", "POST", "calendar/v3/calendars/{calendarId}/clear", CALENDAR),
  spec("list-calendar-events", "GET", "calendar/v3/calendars/{calendarId}/events", [...CALENDAR, ...PAGE, stringField("timeMin", { optional: true, default: "2026-05-01T00:00:00Z" })], { query: ["maxResults", "pageToken", "timeMin"], requiredPaths: ["items"], pageItems: "items" }),
  spec("get-calendar-event", "GET", "calendar/v3/calendars/{calendarId}/events/{eventId}", [...CALENDAR, ...EVENT], { requiredPaths: ["id", "summary"] }),
  spec("create-calendar-event", "POST", "calendar/v3/calendars/{calendarId}/events", [...CALENDAR, ...eventFields()], { body: ["summary", "description", "start", "end", "attendees", "location"], requiredPaths: ["id", "summary"] }),
  spec("update-calendar-event", "PUT", "calendar/v3/calendars/{calendarId}/events/{eventId}", [...CALENDAR, ...EVENT, ...eventFields()], { body: ["summary", "description", "start", "end", "attendees", "location"], requiredPaths: ["id", "summary"] }),
  spec("patch-calendar-event", "PATCH", "calendar/v3/calendars/{calendarId}/events/{eventId}", [...CALENDAR, ...EVENT, stringField("summary", { default: "Updated Event" })], { body: ["summary"], requiredPaths: ["id", "summary"] }),
  spec("delete-calendar-event", "DELETE", "calendar/v3/calendars/{calendarId}/events/{eventId}", [...CALENDAR, ...EVENT]),
  spec("import-calendar-event", "POST", "calendar/v3/calendars/{calendarId}/events/import", [...CALENDAR, ...eventFields()], { body: ["summary", "description", "start", "end", "attendees", "location"], requiredPaths: ["id", "summary"] }),
  spec("move-calendar-event", "POST", "calendar/v3/calendars/{calendarId}/events/{eventId}/move", [...CALENDAR, ...EVENT, stringField("destination", { default: "target@example.invalid" })], { query: ["destination"], requiredPaths: ["id"] }),
  spec("quick-add-calendar-event", "POST", "calendar/v3/calendars/{calendarId}/events/quickAdd", [...CALENDAR, stringField("text", { default: "Lunch tomorrow at noon" })], { query: ["text"], requiredPaths: ["id"] }),
  spec("watch-calendar-events", "POST", "calendar/v3/calendars/{calendarId}/events/watch", [...CALENDAR, ...channelFields()], { body: ["id", "type", "address", "token", "expiration"], requiredPaths: ["id", "resourceId"] }),
  spec("query-calendar-freebusy", "POST", "calendar/v3/freeBusy", [arrayField("items", [{ id: "primary" }]), stringField("timeMin", { default: "2026-05-01T00:00:00Z" }), stringField("timeMax", { default: "2026-05-02T00:00:00Z" })], { body: ["items", "timeMin", "timeMax"], requiredPaths: ["calendars"] }),
  spec("list-calendar-colors", "GET", "calendar/v3/colors", [], { requiredPaths: ["calendar", "event"] }),
  spec("list-calendar-settings", "GET", "calendar/v3/users/me/settings", PAGE, { query: ["maxResults", "pageToken"], requiredPaths: ["items"], pageItems: "items" }),
  spec("get-calendar-setting", "GET", "calendar/v3/users/me/settings/{settingId}", [stringField("settingId", { default: "timezone" })], { requiredPaths: ["id", "value"] }),
  spec("list-calendar-acl", "GET", "calendar/v3/calendars/{calendarId}/acl", [...CALENDAR, ...PAGE], { query: ["maxResults", "pageToken"], requiredPaths: ["items"], pageItems: "items" }),
  spec("get-calendar-acl-rule", "GET", "calendar/v3/calendars/{calendarId}/acl/{ruleId}", [...CALENDAR, ...ACL_RULE], { requiredPaths: ["id", "role"] }),
  spec("create-calendar-acl-rule", "POST", "calendar/v3/calendars/{calendarId}/acl", [...CALENDAR, stringField("role", { default: "reader" }), objectField("scope", { type: "user", value: "reader@example.invalid" })], { body: ["role", "scope"], requiredPaths: ["id", "role"] }),
  spec("update-calendar-acl-rule", "PUT", "calendar/v3/calendars/{calendarId}/acl/{ruleId}", [...CALENDAR, ...ACL_RULE, stringField("role", { default: "writer" }), objectField("scope", { type: "user", value: "reader@example.invalid" })], { body: ["role", "scope"], requiredPaths: ["id", "role"] }),
  spec("patch-calendar-acl-rule", "PATCH", "calendar/v3/calendars/{calendarId}/acl/{ruleId}", [...CALENDAR, ...ACL_RULE, stringField("role", { default: "reader" })], { body: ["role"], requiredPaths: ["id", "role"] }),
  spec("delete-calendar-acl-rule", "DELETE", "calendar/v3/calendars/{calendarId}/acl/{ruleId}", [...CALENDAR, ...ACL_RULE]),
  spec("stop-calendar-channel", "POST", "calendar/v3/channels/stop", [stringField("id", { default: "channel-123" }), stringField("resourceId", { default: "resource-123" })], { body: ["id", "resourceId"] }),
] as const satisfies readonly GoogleOperationSpec[];
