import {
  arrayField,
  booleanField,
  objectField,
  PAGE,
  spec,
  stringField,
  USER,
  type GoogleOperationSpec,
} from "./google-operation-core.ts";

export const GOOGLE_GMAIL_ACTION_SPECS = [
  spec("get-gmail-profile", "GET", "https://gmail.googleapis.com/gmail/v1/users/{userId}/profile", USER, { requiredPaths: ["emailAddress"] }),
  spec("list-gmail-messages", "GET", "https://gmail.googleapis.com/gmail/v1/users/{userId}/messages", [...USER, ...PAGE, stringField("q", { optional: true, default: "from:example.invalid" })], { query: ["maxResults", "pageToken", "q"], requiredPaths: ["messages"], pageItems: "messages" }),
  spec("get-gmail-message", "GET", "https://gmail.googleapis.com/gmail/v1/users/{userId}/messages/{messageId}", [...USER, stringField("messageId", { default: "msg-123" }), stringField("format", { optional: true, default: "full" })], { query: ["format"], requiredPaths: ["id", "threadId"] }),
  spec("send-gmail-message", "POST", "https://gmail.googleapis.com/gmail/v1/users/{userId}/messages/send", [...USER, stringField("raw", { default: "RnJvbTogbWVAZXhhbXBsZS5pbnZhbGlkCg==" })], { body: ["raw"], requiredPaths: ["id"] }),
  spec("import-gmail-message", "POST", "https://gmail.googleapis.com/gmail/v1/users/{userId}/messages/import", [...USER, stringField("raw", { default: "RnJvbTogbWVAZXhhbXBsZS5pbnZhbGlkCg==" })], { body: ["raw"], requiredPaths: ["id"] }),
  spec("insert-gmail-message", "POST", "https://gmail.googleapis.com/gmail/v1/users/{userId}/messages", [...USER, stringField("raw", { default: "RnJvbTogbWVAZXhhbXBsZS5pbnZhbGlkCg==" })], { body: ["raw"], requiredPaths: ["id"] }),
  spec("delete-gmail-message", "DELETE", "https://gmail.googleapis.com/gmail/v1/users/{userId}/messages/{messageId}", [...USER, stringField("messageId", { default: "msg-123" })]),
  spec("trash-gmail-message", "POST", "https://gmail.googleapis.com/gmail/v1/users/{userId}/messages/{messageId}/trash", [...USER, stringField("messageId", { default: "msg-123" })], { requiredPaths: ["id"] }),
  spec("untrash-gmail-message", "POST", "https://gmail.googleapis.com/gmail/v1/users/{userId}/messages/{messageId}/untrash", [...USER, stringField("messageId", { default: "msg-123" })], { requiredPaths: ["id"] }),
  spec("modify-gmail-message", "POST", "https://gmail.googleapis.com/gmail/v1/users/{userId}/messages/{messageId}/modify", [...USER, stringField("messageId", { default: "msg-123" }), arrayField("addLabelIds", ["Label_1"]), arrayField("removeLabelIds", [])], { body: ["addLabelIds", "removeLabelIds"], requiredPaths: ["id"] }),
  spec("batch-delete-gmail-messages", "POST", "https://gmail.googleapis.com/gmail/v1/users/{userId}/messages/batchDelete", [...USER, arrayField("ids", ["msg-123"])], { body: ["ids"] }),
  spec("batch-modify-gmail-messages", "POST", "https://gmail.googleapis.com/gmail/v1/users/{userId}/messages/batchModify", [...USER, arrayField("ids", ["msg-123"]), arrayField("addLabelIds", ["Label_1"]), arrayField("removeLabelIds", [])], { body: ["ids", "addLabelIds", "removeLabelIds"] }),
  spec("get-gmail-attachment", "GET", "https://gmail.googleapis.com/gmail/v1/users/{userId}/messages/{messageId}/attachments/{attachmentId}", [...USER, stringField("messageId", { default: "msg-123" }), stringField("attachmentId", { default: "att-123" })], { requiredPaths: ["data"] }),
  spec("list-gmail-threads", "GET", "https://gmail.googleapis.com/gmail/v1/users/{userId}/threads", [...USER, ...PAGE], { query: ["maxResults", "pageToken"], requiredPaths: ["threads"], pageItems: "threads" }),
  spec("get-gmail-thread", "GET", "https://gmail.googleapis.com/gmail/v1/users/{userId}/threads/{threadId}", [...USER, stringField("threadId", { default: "thread-123" })], { requiredPaths: ["id", "messages"] }),
  spec("modify-gmail-thread", "POST", "https://gmail.googleapis.com/gmail/v1/users/{userId}/threads/{threadId}/modify", [...USER, stringField("threadId", { default: "thread-123" }), arrayField("addLabelIds", ["Label_1"]), arrayField("removeLabelIds", [])], { body: ["addLabelIds", "removeLabelIds"], requiredPaths: ["id"] }),
  spec("trash-gmail-thread", "POST", "https://gmail.googleapis.com/gmail/v1/users/{userId}/threads/{threadId}/trash", [...USER, stringField("threadId", { default: "thread-123" })], { requiredPaths: ["id"] }),
  spec("untrash-gmail-thread", "POST", "https://gmail.googleapis.com/gmail/v1/users/{userId}/threads/{threadId}/untrash", [...USER, stringField("threadId", { default: "thread-123" })], { requiredPaths: ["id"] }),
  spec("delete-gmail-thread", "DELETE", "https://gmail.googleapis.com/gmail/v1/users/{userId}/threads/{threadId}", [...USER, stringField("threadId", { default: "thread-123" })]),
  spec("list-gmail-labels", "GET", "https://gmail.googleapis.com/gmail/v1/users/{userId}/labels", USER, { requiredPaths: ["labels"] }),
  spec("get-gmail-label", "GET", "https://gmail.googleapis.com/gmail/v1/users/{userId}/labels/{labelId}", [...USER, stringField("labelId", { default: "Label_1" })], { requiredPaths: ["id", "name"] }),
  spec("create-gmail-label", "POST", "https://gmail.googleapis.com/gmail/v1/users/{userId}/labels", [...USER, stringField("name", { default: "Claw" })], { body: ["name"], requiredPaths: ["id", "name"] }),
  spec("update-gmail-label", "PUT", "https://gmail.googleapis.com/gmail/v1/users/{userId}/labels/{labelId}", [...USER, stringField("labelId", { default: "Label_1" }), stringField("name", { default: "Claw Updated" })], { body: ["name"], requiredPaths: ["id", "name"] }),
  spec("patch-gmail-label", "PATCH", "https://gmail.googleapis.com/gmail/v1/users/{userId}/labels/{labelId}", [...USER, stringField("labelId", { default: "Label_1" }), stringField("name", { default: "Claw Patched" })], { body: ["name"], requiredPaths: ["id", "name"] }),
  spec("delete-gmail-label", "DELETE", "https://gmail.googleapis.com/gmail/v1/users/{userId}/labels/{labelId}", [...USER, stringField("labelId", { default: "Label_1" })]),
  spec("list-gmail-drafts", "GET", "https://gmail.googleapis.com/gmail/v1/users/{userId}/drafts", [...USER, ...PAGE], { query: ["maxResults", "pageToken"], requiredPaths: ["drafts"], pageItems: "drafts" }),
  spec("get-gmail-draft", "GET", "https://gmail.googleapis.com/gmail/v1/users/{userId}/drafts/{draftId}", [...USER, stringField("draftId", { default: "draft-123" })], { requiredPaths: ["id", "message"] }),
  spec("create-gmail-draft", "POST", "https://gmail.googleapis.com/gmail/v1/users/{userId}/drafts", [...USER, objectField("message", { raw: "RnJvbTogbWVAZXhhbXBsZS5pbnZhbGlkCg==" })], { body: ["message"], requiredPaths: ["id", "message"] }),
  spec("update-gmail-draft", "PUT", "https://gmail.googleapis.com/gmail/v1/users/{userId}/drafts/{draftId}", [...USER, stringField("draftId", { default: "draft-123" }), objectField("message", { raw: "RnJvbTogbWVAZXhhbXBsZS5pbnZhbGlkCg==" })], { body: ["message"], requiredPaths: ["id", "message"] }),
  spec("delete-gmail-draft", "DELETE", "https://gmail.googleapis.com/gmail/v1/users/{userId}/drafts/{draftId}", [...USER, stringField("draftId", { default: "draft-123" })]),
  spec("send-gmail-draft", "POST", "https://gmail.googleapis.com/gmail/v1/users/{userId}/drafts/send", [...USER, stringField("id", { default: "draft-123" })], { body: ["id"], requiredPaths: ["id"] }),
  spec("list-gmail-history", "GET", "https://gmail.googleapis.com/gmail/v1/users/{userId}/history", [...USER, stringField("startHistoryId", { default: "1000" }), ...PAGE], { query: ["startHistoryId", "maxResults", "pageToken"], requiredPaths: ["history"], pageItems: "history" }),
  spec("watch-gmail-mailbox", "POST", "https://gmail.googleapis.com/gmail/v1/users/{userId}/watch", [...USER, stringField("topicName", { default: "projects/offline/topics/gmail" }), arrayField("labelIds", ["INBOX"])], { body: ["topicName", "labelIds"], requiredPaths: ["historyId", "expiration"] }),
  spec("stop-gmail-mailbox", "POST", "https://gmail.googleapis.com/gmail/v1/users/{userId}/stop", USER),
  spec("list-gmail-filters", "GET", "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/filters", USER, { requiredPaths: ["filter"] }),
  spec("get-gmail-filter", "GET", "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/filters/{filterId}", [...USER, stringField("filterId", { default: "filter-123" })], { requiredPaths: ["id"] }),
  spec("create-gmail-filter", "POST", "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/filters", [...USER, objectField("criteria", { from: "sender@example.invalid" }), objectField("action", { addLabelIds: ["Label_1"] })], { body: ["criteria", "action"], requiredPaths: ["id"] }),
  spec("delete-gmail-filter", "DELETE", "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/filters/{filterId}", [...USER, stringField("filterId", { default: "filter-123" })]),
  spec("get-gmail-auto-forwarding", "GET", "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/autoForwarding", USER, { requiredPaths: ["enabled"] }),
  spec("update-gmail-auto-forwarding", "PUT", "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/autoForwarding", [...USER, booleanField("enabled", { default: false }), stringField("emailAddress", { optional: true, default: "forward@example.invalid" })], { body: ["enabled", "emailAddress"], requiredPaths: ["enabled"] }),
  spec("get-gmail-imap", "GET", "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/imap", USER, { requiredPaths: ["enabled"] }),
  spec("update-gmail-imap", "PUT", "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/imap", [...USER, booleanField("enabled", { default: true })], { body: ["enabled"], requiredPaths: ["enabled"] }),
  spec("get-gmail-pop", "GET", "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/pop", USER, { requiredPaths: ["accessWindow"] }),
  spec("update-gmail-pop", "PUT", "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/pop", [...USER, stringField("accessWindow", { default: "disabled" })], { body: ["accessWindow"], requiredPaths: ["accessWindow"] }),
  spec("get-gmail-vacation", "GET", "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/vacation", USER, { requiredPaths: ["enableAutoReply"] }),
  spec("update-gmail-vacation", "PUT", "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/vacation", [...USER, booleanField("enableAutoReply", { default: true }), stringField("responseSubject", { default: "Away" }), stringField("responseBodyPlainText", { default: "I am away." })], { body: ["enableAutoReply", "responseSubject", "responseBodyPlainText"], requiredPaths: ["enableAutoReply"] }),
  spec("list-gmail-delegates", "GET", "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/delegates", USER, { requiredPaths: ["delegates"] }),
  spec("get-gmail-delegate", "GET", "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/delegates/{delegateEmail}", [...USER, stringField("delegateEmail", { default: "delegate@example.invalid" })], { requiredPaths: ["delegateEmail"] }),
  spec("create-gmail-delegate", "POST", "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/delegates", [...USER, stringField("delegateEmail", { default: "delegate@example.invalid" })], { body: ["delegateEmail"], requiredPaths: ["delegateEmail"] }),
  spec("delete-gmail-delegate", "DELETE", "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/delegates/{delegateEmail}", [...USER, stringField("delegateEmail", { default: "delegate@example.invalid" })]),
  spec("list-gmail-send-as", "GET", "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/sendAs", USER, { requiredPaths: ["sendAs"] }),
  spec("get-gmail-send-as", "GET", "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}", [...USER, stringField("sendAsEmail", { default: "me@example.invalid" })], { requiredPaths: ["sendAsEmail"] }),
  spec("update-gmail-send-as", "PUT", "https://gmail.googleapis.com/gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}", [...USER, stringField("sendAsEmail", { default: "me@example.invalid" }), stringField("displayName", { default: "Example User" })], { body: ["displayName"], requiredPaths: ["sendAsEmail"] }),
] as const satisfies readonly GoogleOperationSpec[];
