import {
  arrayField,
  booleanField,
  channelFields,
  DRIVE_PAGE,
  FILE,
  integerField,
  permissionBodyField,
  spec,
  stringField,
  type GoogleOperationSpec,
} from "./google-operation-core.ts";

export const GOOGLE_DRIVE_ACTION_SPECS = [
  spec("list-drive-files", "GET", "drive/v3/files", [...DRIVE_PAGE, stringField("q", { optional: true, default: "trashed = false" })], { query: ["pageSize", "pageToken", "q"], requiredPaths: ["files"], pageItems: "files" }),
  spec("get-drive-file", "GET", "drive/v3/files/{fileId}", FILE, { query: ["fields"], requiredPaths: ["id", "name"] }),
  spec("create-drive-file", "POST", "drive/v3/files", [stringField("name", { default: "Sample" }), stringField("mimeType", { optional: true, default: "text/plain" }), arrayField("parents", ["folder-123"]), stringField("description", { optional: true, default: "Sample file" })], { body: ["name", "mimeType", "parents", "description"], requiredPaths: ["id", "name"] }),
  spec("update-drive-file", "PATCH", "drive/v3/files/{fileId}", [...FILE, stringField("name", { optional: true, default: "Renamed" }), stringField("description", { optional: true, default: "Updated" })], { body: ["name", "description"], requiredPaths: ["id", "name"] }),
  spec("delete-drive-file", "DELETE", "drive/v3/files/{fileId}", FILE),
  spec("copy-drive-file", "POST", "drive/v3/files/{fileId}/copy", [...FILE, stringField("name", { default: "Copy" }), arrayField("parents", ["folder-123"])], { body: ["name", "parents"], requiredPaths: ["id", "name"] }),
  spec("empty-drive-trash", "DELETE", "drive/v3/files/trash", []),
  spec("export-drive-file", "GET", "drive/v3/files/{fileId}/export", [...FILE, stringField("mimeType", { default: "text/plain" })], { query: ["mimeType"], responseType: "string" }),
  spec("generate-drive-ids", "GET", "drive/v3/files/generateIds", [integerField("count", { optional: true, default: 1, min: 1, max: 100 })], { query: ["count"], requiredPaths: ["ids"] }),
  spec("list-drive-changes", "GET", "drive/v3/changes", [stringField("pageToken", { default: "start-token" }), integerField("pageSize", { optional: true, default: 100, min: 1, max: 1000 })], { query: ["pageToken", "pageSize"], requiredPaths: ["changes"], pageItems: "changes" }),
  spec("get-drive-start-page-token", "GET", "drive/v3/changes/startPageToken", [], { requiredPaths: ["startPageToken"] }),
  spec("watch-drive-changes", "POST", "drive/v3/changes/watch", [stringField("pageToken", { default: "start-token" }), ...channelFields()], { query: ["pageToken"], body: ["id", "type", "address", "token", "expiration"], requiredPaths: ["id", "resourceId"] }),
  spec("stop-drive-channel", "POST", "drive/v3/channels/stop", [stringField("id", { default: "channel-123" }), stringField("resourceId", { default: "resource-123" })], { body: ["id", "resourceId"] }),
  spec("list-drive-permissions", "GET", "drive/v3/files/{fileId}/permissions", [...FILE, ...DRIVE_PAGE], { query: ["pageSize", "pageToken"], requiredPaths: ["permissions"], pageItems: "permissions" }),
  spec("get-drive-permission", "GET", "drive/v3/files/{fileId}/permissions/{permissionId}", [...FILE, stringField("permissionId", { default: "perm-123" })], { requiredPaths: ["id", "role"] }),
  spec("create-drive-permission", "POST", "drive/v3/files/{fileId}/permissions", [...FILE, ...permissionBodyField()], { body: ["type", "role", "emailAddress", "domain", "allowFileDiscovery"], requiredPaths: ["id", "role"] }),
  spec("update-drive-permission", "PATCH", "drive/v3/files/{fileId}/permissions/{permissionId}", [...FILE, stringField("permissionId", { default: "perm-123" }), ...permissionBodyField()], { body: ["type", "role", "emailAddress", "domain", "allowFileDiscovery"], requiredPaths: ["id", "role"] }),
  spec("delete-drive-permission", "DELETE", "drive/v3/files/{fileId}/permissions/{permissionId}", [...FILE, stringField("permissionId", { default: "perm-123" })]),
  spec("list-drive-comments", "GET", "drive/v3/files/{fileId}/comments", [...FILE, ...DRIVE_PAGE], { query: ["pageSize", "pageToken"], requiredPaths: ["comments"], pageItems: "comments" }),
  spec("get-drive-comment", "GET", "drive/v3/files/{fileId}/comments/{commentId}", [...FILE, stringField("commentId", { default: "comment-123" })], { requiredPaths: ["id", "content"] }),
  spec("create-drive-comment", "POST", "drive/v3/files/{fileId}/comments", [...FILE, stringField("content", { default: "Looks good" })], { body: ["content"], requiredPaths: ["id", "content"] }),
  spec("update-drive-comment", "PATCH", "drive/v3/files/{fileId}/comments/{commentId}", [...FILE, stringField("commentId", { default: "comment-123" }), stringField("content", { default: "Updated comment" })], { body: ["content"], requiredPaths: ["id", "content"] }),
  spec("delete-drive-comment", "DELETE", "drive/v3/files/{fileId}/comments/{commentId}", [...FILE, stringField("commentId", { default: "comment-123" })]),
  spec("list-drive-replies", "GET", "drive/v3/files/{fileId}/comments/{commentId}/replies", [...FILE, stringField("commentId", { default: "comment-123" }), ...DRIVE_PAGE], { query: ["pageSize", "pageToken"], requiredPaths: ["replies"], pageItems: "replies" }),
  spec("get-drive-reply", "GET", "drive/v3/files/{fileId}/comments/{commentId}/replies/{replyId}", [...FILE, stringField("commentId", { default: "comment-123" }), stringField("replyId", { default: "reply-123" })], { requiredPaths: ["id", "content"] }),
  spec("create-drive-reply", "POST", "drive/v3/files/{fileId}/comments/{commentId}/replies", [...FILE, stringField("commentId", { default: "comment-123" }), stringField("content", { default: "Reply" })], { body: ["content"], requiredPaths: ["id", "content"] }),
  spec("update-drive-reply", "PATCH", "drive/v3/files/{fileId}/comments/{commentId}/replies/{replyId}", [...FILE, stringField("commentId", { default: "comment-123" }), stringField("replyId", { default: "reply-123" }), stringField("content", { default: "Updated reply" })], { body: ["content"], requiredPaths: ["id", "content"] }),
  spec("delete-drive-reply", "DELETE", "drive/v3/files/{fileId}/comments/{commentId}/replies/{replyId}", [...FILE, stringField("commentId", { default: "comment-123" }), stringField("replyId", { default: "reply-123" })]),
  spec("list-drive-revisions", "GET", "drive/v3/files/{fileId}/revisions", FILE, { requiredPaths: ["revisions"] }),
  spec("get-drive-revision", "GET", "drive/v3/files/{fileId}/revisions/{revisionId}", [...FILE, stringField("revisionId", { default: "rev-123" })], { requiredPaths: ["id"] }),
  spec("update-drive-revision", "PATCH", "drive/v3/files/{fileId}/revisions/{revisionId}", [...FILE, stringField("revisionId", { default: "rev-123" }), booleanField("keepForever", { optional: true, default: true })], { body: ["keepForever"], requiredPaths: ["id"] }),
  spec("delete-drive-revision", "DELETE", "drive/v3/files/{fileId}/revisions/{revisionId}", [...FILE, stringField("revisionId", { default: "rev-123" })]),
  spec("list-shared-drives", "GET", "drive/v3/drives", DRIVE_PAGE, { query: ["pageSize", "pageToken"], requiredPaths: ["drives"], pageItems: "drives" }),
  spec("get-shared-drive", "GET", "drive/v3/drives/{driveId}", [stringField("driveId", { default: "drive-123" })], { requiredPaths: ["id", "name"] }),
  spec("create-shared-drive", "POST", "drive/v3/drives", [stringField("requestId", { default: "request-123" }), stringField("name", { default: "Shared Drive" })], { query: ["requestId"], body: ["name"], requiredPaths: ["id", "name"] }),
  spec("update-shared-drive", "PATCH", "drive/v3/drives/{driveId}", [stringField("driveId", { default: "drive-123" }), stringField("name", { default: "Updated Drive" })], { body: ["name"], requiredPaths: ["id", "name"] }),
  spec("delete-shared-drive", "DELETE", "drive/v3/drives/{driveId}", [stringField("driveId", { default: "drive-123" })]),
  spec("hide-shared-drive", "POST", "drive/v3/drives/{driveId}/hide", [stringField("driveId", { default: "drive-123" })], { requiredPaths: ["id"] }),
  spec("unhide-shared-drive", "POST", "drive/v3/drives/{driveId}/unhide", [stringField("driveId", { default: "drive-123" })], { requiredPaths: ["id"] }),
] as const satisfies readonly GoogleOperationSpec[];
