import type { BuiltinCollectionDefinition } from "../_types.ts";

export const INSTRUCTIONS: BuiltinCollectionDefinition = {
  name: "instructions",
  displayName: "CLI Instructions",
  family: "meta",
  aliases: ["instruction", "instructions", "claw_instruction", "claw_instructions"],
  catalog: {
    purpose:
      "Normalized policy and hook layer for agents using the claw CLI. Each row attaches operational guidance to a CLI surface (alias, family, command, subcommand, collection or action) or to an agent lifecycle trigger (session-start, user-turn, input-kind, pre/post tool call, correction-detected). Defaults ship in the @clawjs/core catalog; overrides and agent-proposed rules live here.",
    evidence: ["agent_useful", "multi_domain_reuse"],
    fieldGuidance:
      "Body fields useWhen/useNot/readPolicy/writePolicy are capped at 240 chars; before/after/forbid at 180; notes at 500. Caps are enforced at the API layer. Target axes are denormalized for indexing; rebuild the InstructionTarget object via the cli-instructions resolver.",
    relationGuidance:
      "Not relational. References to other collections or commands are expressed by string axes (targetCollection, targetCommand) not as relations.",
    notes:
      "State machine: proposed -> active -> archived. Agent-authored rows enter as proposed and require claw instructions approve. Activation=on always renders; auto follows ship defaults; off hides.",
  },
  fields: [
    { name: "schemaVersion", type: "number", required: true, requiredReason: "integrity", min: 1, max: 1 },
    { name: "targetAlias", type: "text", maxLength: 64 },
    { name: "targetFamily", type: "text", maxLength: 64 },
    { name: "targetCommand", type: "text", maxLength: 64 },
    { name: "targetSubcommand", type: "text", maxLength: 64 },
    { name: "targetCollection", type: "text", maxLength: 64 },
    {
      name: "targetAction",
      type: "select",
      options: ["read", "write", "edit", "delete", "list", "search", "*"],
    },
    {
      name: "trigger",
      type: "select",
      required: true,
      requiredReason: "lifecycle",
      options: [
        "surface-action",
        "session-start",
        "user-turn",
        "pre-tool-call",
        "post-tool-call",
        "correction-detected",
        "input-kind:audio",
        "input-kind:image",
        "input-kind:video",
        "input-kind:file",
        "input-kind:url",
        "input-kind:text",
      ],
    },
    {
      name: "activation",
      type: "select",
      required: true,
      requiredReason: "lifecycle",
      options: ["on", "off", "auto"],
    },
    {
      name: "priority",
      type: "number",
      required: true,
      requiredReason: "integrity",
      min: 0,
      max: 100,
    },
    {
      name: "severity",
      type: "select",
      required: true,
      requiredReason: "integrity",
      options: ["info", "warn", "block"],
    },
    { name: "useWhen", type: "text", maxLength: 240 },
    { name: "useNot", type: "text", maxLength: 240 },
    { name: "readPolicy", type: "text", maxLength: 240 },
    { name: "writePolicy", type: "text", maxLength: 240 },
    { name: "before", type: "text", maxLength: 180 },
    { name: "after", type: "text", maxLength: 180 },
    { name: "forbid", type: "text", maxLength: 180 },
    { name: "notes", type: "text", maxLength: 500 },
    {
      name: "provenance",
      type: "select",
      required: true,
      requiredReason: "integrity",
      options: ["seed", "user", "agent"],
    },
    {
      name: "state",
      type: "select",
      required: true,
      requiredReason: "lifecycle",
      options: ["proposed", "active", "archived"],
    },
    { name: "confidence", type: "number", min: 0, max: 1 },
    { name: "proposedFrom", type: "text", maxLength: 128 },
    { name: "source", type: "text", maxLength: 128 },
    { name: "validations", type: "json" },
  ],
  indexes: [
    { name: "instructions_trigger_idx", fields: ["trigger"] },
    { name: "instructions_state_idx", fields: ["state"] },
    { name: "instructions_command_idx", fields: ["targetCommand"] },
    { name: "instructions_collection_idx", fields: ["targetCollection"] },
    { name: "instructions_state_trigger_idx", fields: ["state", "trigger"] },
  ],
};
