import type { BuiltinCollectionDefinition } from "../_types.ts";

export const AGENT_SESSIONS: BuiltinCollectionDefinition = {
  name: "agent_sessions",
  displayName: "Agent Sessions",
  family: "agents",
  aliases: ["session","sessions","agent_session","agent_sessions"],
  fields: [
    { name: "companyId", type: "relation", relation: { collectionName: "companies" } },
    { name: "agentId", type: "relation", relation: { collectionName: "agents" } },
    { name: "assignmentId", type: "relation", relation: { collectionName: "agent_assignments" } },
    { name: "externalActorId", type: "relation", relation: { collectionName: "actors" } },
    { name: "contactId", type: "relation", relation: { collectionName: "contacts" } },
    { name: "customerId", type: "text" },
    { name: "initiatorActorId", type: "relation", relation: { collectionName: "actors" } },
    { name: "status", type: "select", required: true, options: ["active","awaiting_input","complete","error","pending","stale","paused"] },
    { name: "initialSource", type: "select", options: ["comment","direct_chat","pull_request_comment","slack","workflow","intercom","zendesk","telegram","whatsapp","web_chat","mcp","form","email","scheduled","other"] },
    { name: "conversationKind", type: "select", options: ["internal_chat","support_conversation","workflow_trace","external_channel","delegation","mcp_api"] },
    { name: "supportThreadId", type: "relation", relation: { collectionName: "support_threads" } },
    { name: "context", type: "json" },
    { name: "summary", type: "text" },
    { name: "readAt", type: "date" },
    { name: "linkedIssueId", type: "relation", relation: { collectionName: "issues" } },
    { name: "linkedTaskId", type: "relation", relation: { collectionName: "tasks" } },
    { name: "source", type: "json" },
    { name: "links", type: "json" },
    { name: "metadata", type: "json" },
    { name: "archivedAt", type: "date" },
  ],
  indexes: [
    { name: "agent_sess_company_idx", fields: ["companyId"] },
    { name: "agent_sess_status_idx", fields: ["status"] },
    { name: "agent_sess_agent_idx", fields: ["agentId"] },
    { name: "agent_sess_assignment_idx", fields: ["assignmentId"] },
  ],
};
