import type { SessionStructuredEventKind } from "./types.ts";

export type SessionRenderDisclosureMode = "everyday" | "coding";
export type SessionRenderOutcome = "success" | "failed" | "stopped" | "truncated" | "denied" | "unknown_fallback";
export type SessionRenderState = "collapsed" | "active" | "expanded";

export interface SessionRenderFixture {
  id: string;
  eventKind: SessionStructuredEventKind;
  outcome: SessionRenderOutcome;
  summary: string;
}

export interface SessionRenderMatrixRow {
  eventKind: SessionStructuredEventKind;
  producer: string;
  payloadSchema: string;
  collapsed: string;
  active: string;
  expanded: string;
  everyday: string;
  coding: string;
  localizationKeys: readonly string[];
  maxPreviewChars: number;
  maxDetailBytes: number;
  expansionRoute: string;
  fixtures: readonly string[];
  outcomes: readonly SessionRenderOutcome[];
}

const EVENT_EXPANSION_ROUTE = "/v1/sessions/:sessionId/events?turnId=:turnId&eventKind=:eventKind";
const DEFAULT_PREVIEW_CHARS = 280;
const DEFAULT_DETAIL_BYTES = 64 * 1024;

function keys(eventKind: SessionStructuredEventKind): readonly string[] {
  return [
    `sessions.render.${eventKind}.collapsed`,
    `sessions.render.${eventKind}.active`,
    `sessions.render.${eventKind}.expanded`,
    `sessions.render.${eventKind}.everyday`,
    `sessions.render.${eventKind}.coding`,
    `sessions.render.${eventKind}.fallback`,
  ];
}

export const sessionRenderMatrix = {
  message: {
    eventKind: "message",
    producer: "sessions.adapter.codex",
    payloadSchema: "session_events.payload_json message role/content blocks",
    collapsed: "speaker label plus bounded message preview",
    active: "streaming message line with pending/complete/interrupted state",
    expanded: "full visible message blocks with capped raw payload details",
    everyday: "plain conversation text and compact attachment hints",
    coding: "conversation text, content blocks, source id, and payload inspector",
    localizationKeys: keys("message"),
    maxPreviewChars: DEFAULT_PREVIEW_CHARS,
    maxDetailBytes: DEFAULT_DETAIL_BYTES,
    expansionRoute: EVENT_EXPANSION_ROUTE,
    fixtures: ["message_user", "message_assistant_streaming", "message_model_changed"],
    outcomes: ["success", "stopped", "truncated", "unknown_fallback"],
  },
  tool_call: {
    eventKind: "tool_call",
    producer: "runtime.tool-router",
    payloadSchema: "tool call name/namespace/arguments/call id",
    collapsed: "tool name, short argument summary, and status badge",
    active: "running tool line with spinner and elapsed time",
    expanded: "arguments, call id, routing metadata, and capped raw payload",
    everyday: "human-readable action summary without raw argument noise",
    coding: "tool name, arguments, call id, namespace, and raw payload inspector",
    localizationKeys: keys("tool_call"),
    maxPreviewChars: DEFAULT_PREVIEW_CHARS,
    maxDetailBytes: DEFAULT_DETAIL_BYTES,
    expansionRoute: EVENT_EXPANSION_ROUTE,
    fixtures: ["shell_command_start", "computer_use_action", "browser_action"],
    outcomes: ["success", "stopped", "denied", "truncated", "unknown_fallback"],
  },
  tool_output: {
    eventKind: "tool_output",
    producer: "runtime.tool-router",
    payloadSchema: "tool result stdout/stderr/status/artifact refs",
    collapsed: "tool result status and bounded output preview",
    active: "streaming output tail with byte cap indicator",
    expanded: "stdout, stderr, artifact refs, exit status, and capped raw payload",
    everyday: "result summary with errors surfaced in plain language",
    coding: "stdout/stderr, exit code, command metadata, artifacts, and raw payload inspector",
    localizationKeys: keys("tool_output"),
    maxPreviewChars: DEFAULT_PREVIEW_CHARS,
    maxDetailBytes: DEFAULT_DETAIL_BYTES,
    expansionRoute: EVENT_EXPANSION_ROUTE,
    fixtures: ["shell_success", "shell_failure", "shell_timeout", "shell_truncated", "mcp_text", "mcp_resource", "mcp_empty", "mcp_error"],
    outcomes: ["success", "failed", "stopped", "truncated", "unknown_fallback"],
  },
  patch: {
    eventKind: "patch",
    producer: "runtime.patch-applier",
    payloadSchema: "file diff hunks, apply status, conflict metadata",
    collapsed: "file count, operation summary, and status badge",
    active: "patch operation in progress with file path preview",
    expanded: "bounded diff hunks, apply result, conflicts, and raw payload inspector",
    everyday: "changed files and outcome summary",
    coding: "diff hunks, file operations, conflicts, and raw payload inspector",
    localizationKeys: keys("patch"),
    maxPreviewChars: DEFAULT_PREVIEW_CHARS,
    maxDetailBytes: DEFAULT_DETAIL_BYTES,
    expansionRoute: EVENT_EXPANSION_ROUTE,
    fixtures: ["patch_add", "patch_edit", "patch_delete", "patch_rejected", "patch_conflict"],
    outcomes: ["success", "failed", "truncated", "unknown_fallback"],
  },
  lifecycle: {
    eventKind: "lifecycle",
    producer: "runtime.session-lifecycle",
    payloadSchema: "session start/stop/model change/reroute metadata",
    collapsed: "lifecycle milestone and status",
    active: "current lifecycle transition",
    expanded: "transition metadata, model/runtime changes, and raw payload inspector",
    everyday: "short status transition",
    coding: "runtime adapter, model, reroute reason, and raw payload inspector",
    localizationKeys: keys("lifecycle"),
    maxPreviewChars: DEFAULT_PREVIEW_CHARS,
    maxDetailBytes: DEFAULT_DETAIL_BYTES,
    expansionRoute: EVENT_EXPANSION_ROUTE,
    fixtures: ["model_changed", "model_reroute", "auto_review_interruption", "approval_approved"],
    outcomes: ["success", "stopped", "denied", "unknown_fallback"],
  },
  usage: {
    eventKind: "usage",
    producer: "runtime.usage-meter",
    payloadSchema: "token, billing, context, and quota counters",
    collapsed: "token/context usage summary",
    active: "usage update during active generation",
    expanded: "input/output/cache/context counters and raw payload inspector",
    everyday: "plain usage summary",
    coding: "raw counters, model ids, context windows, and payload inspector",
    localizationKeys: keys("usage"),
    maxPreviewChars: 180,
    maxDetailBytes: 16 * 1024,
    expansionRoute: EVENT_EXPANSION_ROUTE,
    fixtures: ["usage_tokens"],
    outcomes: ["success", "unknown_fallback"],
  },
  goal: {
    eventKind: "goal",
    producer: "runtime.goal-runner",
    payloadSchema: "goal status, plan items, budget, and continuation metadata",
    collapsed: "goal status and next plan item",
    active: "active plan step with progress state",
    expanded: "plan checklist, budget, evidence, and raw payload inspector",
    everyday: "progress checklist in plain language",
    coding: "goal ids, plan ids, budgets, evidence links, and raw payload inspector",
    localizationKeys: keys("goal"),
    maxPreviewChars: DEFAULT_PREVIEW_CHARS,
    maxDetailBytes: DEFAULT_DETAIL_BYTES,
    expansionRoute: EVENT_EXPANSION_ROUTE,
    fixtures: ["plan_update_checklist"],
    outcomes: ["success", "failed", "stopped", "unknown_fallback"],
  },
  search: {
    eventKind: "search",
    producer: "runtime.search",
    payloadSchema: "query, source, result count, facets, and result refs",
    collapsed: "query and bounded result summary",
    active: "search in progress with source label",
    expanded: "query, filters, result refs, snippets, and raw payload inspector",
    everyday: "search query and selected result summary",
    coding: "query, filters, source ids, result refs, and raw payload inspector",
    localizationKeys: keys("search"),
    maxPreviewChars: DEFAULT_PREVIEW_CHARS,
    maxDetailBytes: DEFAULT_DETAIL_BYTES,
    expansionRoute: EVENT_EXPANSION_ROUTE,
    fixtures: ["web_search"],
    outcomes: ["success", "failed", "truncated", "unknown_fallback"],
  },
  subagent: {
    eventKind: "subagent",
    producer: "runtime.subagent-orchestrator",
    payloadSchema: "spawn/send/wait/resume/close edge metadata",
    collapsed: "subagent action, target, and status",
    active: "subagent operation in progress",
    expanded: "spawn edges, messages, status, result refs, and raw payload inspector",
    everyday: "delegated work summary with status",
    coding: "subagent ids, edges, prompts, outputs, and raw payload inspector",
    localizationKeys: keys("subagent"),
    maxPreviewChars: DEFAULT_PREVIEW_CHARS,
    maxDetailBytes: DEFAULT_DETAIL_BYTES,
    expansionRoute: EVENT_EXPANSION_ROUTE,
    fixtures: ["subagent_spawn", "subagent_send", "subagent_wait", "subagent_resume", "subagent_close"],
    outcomes: ["success", "failed", "stopped", "truncated", "unknown_fallback"],
  },
  question: {
    eventKind: "question",
    producer: "runtime.approvals",
    payloadSchema: "question text, choices, default, and answer status",
    collapsed: "question prompt and answered/pending state",
    active: "pending user decision",
    expanded: "choices, selected answer, policy context, and raw payload inspector",
    everyday: "clear question and available choices",
    coding: "question schema, ids, policy context, choices, and raw payload inspector",
    localizationKeys: keys("question"),
    maxPreviewChars: DEFAULT_PREVIEW_CHARS,
    maxDetailBytes: 32 * 1024,
    expansionRoute: EVENT_EXPANSION_ROUTE,
    fixtures: ["user_question", "approval_denied"],
    outcomes: ["success", "denied", "stopped", "unknown_fallback"],
  },
  mcp: {
    eventKind: "mcp",
    producer: "runtime.mcp",
    payloadSchema: "server/tool/resource request and response metadata",
    collapsed: "MCP server/tool label and status",
    active: "MCP operation in progress",
    expanded: "server, tool, resource refs, result summary, and raw payload inspector",
    everyday: "external tool/resource summary",
    coding: "server ids, tool names, resource uris, payloads, and raw payload inspector",
    localizationKeys: keys("mcp"),
    maxPreviewChars: DEFAULT_PREVIEW_CHARS,
    maxDetailBytes: DEFAULT_DETAIL_BYTES,
    expansionRoute: EVENT_EXPANSION_ROUTE,
    fixtures: ["mcp_tool_call"],
    outcomes: ["success", "failed", "truncated", "unknown_fallback"],
  },
  compaction: {
    eventKind: "compaction",
    producer: "runtime.context-manager",
    payloadSchema: "context compaction source/range/summary metadata",
    collapsed: "compaction summary and affected range",
    active: "compaction in progress",
    expanded: "source range, retained summary, dropped detail metadata, and raw payload inspector",
    everyday: "context was summarized with retained outcome",
    coding: "source ids, token counts, retained summaries, and raw payload inspector",
    localizationKeys: keys("compaction"),
    maxPreviewChars: DEFAULT_PREVIEW_CHARS,
    maxDetailBytes: 32 * 1024,
    expansionRoute: EVENT_EXPANSION_ROUTE,
    fixtures: ["compaction"],
    outcomes: ["success", "failed", "unknown_fallback"],
  },
  rollback: {
    eventKind: "rollback",
    producer: "runtime.rollback",
    payloadSchema: "rollback target, affected files/state, and result metadata",
    collapsed: "rollback target and status",
    active: "rollback in progress",
    expanded: "target refs, affected state, result, and raw payload inspector",
    everyday: "restore action and outcome",
    coding: "target ids, file/state changes, conflicts, and raw payload inspector",
    localizationKeys: keys("rollback"),
    maxPreviewChars: DEFAULT_PREVIEW_CHARS,
    maxDetailBytes: DEFAULT_DETAIL_BYTES,
    expansionRoute: EVENT_EXPANSION_ROUTE,
    fixtures: ["rollback"],
    outcomes: ["success", "failed", "stopped", "unknown_fallback"],
  },
  unknown: {
    eventKind: "unknown",
    producer: "runtime.unknown",
    payloadSchema: "unknown event payload preserved as capped JSON",
    collapsed: "unknown event type with safe summary",
    active: "unknown event received",
    expanded: "capped raw payload, source id, event type, and diagnostics",
    everyday: "visible unsupported event notice",
    coding: "raw capped payload and source diagnostics",
    localizationKeys: keys("unknown"),
    maxPreviewChars: 180,
    maxDetailBytes: 16 * 1024,
    expansionRoute: EVENT_EXPANSION_ROUTE,
    fixtures: ["unknown_event"],
    outcomes: ["unknown_fallback", "truncated"],
  },
} as const satisfies Record<SessionStructuredEventKind, SessionRenderMatrixRow>;

export const sessionRenderMatrixRows = Object.values(sessionRenderMatrix);

export const requiredSessionRenderFixtureIds = [
  "shell_success",
  "shell_failure",
  "shell_timeout",
  "shell_truncated",
  "patch_add",
  "patch_edit",
  "patch_delete",
  "patch_rejected",
  "patch_conflict",
  "plan_update_checklist",
  "user_question",
  "web_search",
  "mcp_text",
  "mcp_resource",
  "mcp_empty",
  "mcp_error",
  "computer_use_action",
  "browser_action",
  "subagent_spawn",
  "subagent_send",
  "subagent_wait",
  "subagent_resume",
  "subagent_close",
  "model_changed",
  "model_reroute",
  "compaction",
  "rollback",
  "auto_review_interruption",
  "background_terminal",
  "approval_denied",
  "approval_approved",
] as const;

export const sessionRenderFixtures = [
  { id: "message_user", eventKind: "message", outcome: "success", summary: "user message preview" },
  { id: "message_assistant_streaming", eventKind: "message", outcome: "stopped", summary: "assistant stream interrupted" },
  { id: "message_model_changed", eventKind: "message", outcome: "success", summary: "assistant message after model change" },
  { id: "shell_command_start", eventKind: "tool_call", outcome: "success", summary: "shell command started" },
  { id: "computer_use_action", eventKind: "tool_call", outcome: "success", summary: "computer-use click action" },
  { id: "browser_action", eventKind: "tool_call", outcome: "success", summary: "browser navigation action" },
  { id: "shell_success", eventKind: "tool_output", outcome: "success", summary: "shell command succeeded" },
  { id: "shell_failure", eventKind: "tool_output", outcome: "failed", summary: "shell command failed" },
  { id: "shell_timeout", eventKind: "tool_output", outcome: "stopped", summary: "shell command timed out" },
  { id: "shell_truncated", eventKind: "tool_output", outcome: "truncated", summary: "shell output truncated" },
  { id: "background_terminal", eventKind: "tool_output", outcome: "success", summary: "background terminal output" },
  { id: "mcp_text", eventKind: "tool_output", outcome: "success", summary: "MCP text result" },
  { id: "mcp_resource", eventKind: "tool_output", outcome: "success", summary: "MCP resource result" },
  { id: "mcp_empty", eventKind: "tool_output", outcome: "success", summary: "MCP empty result" },
  { id: "mcp_error", eventKind: "tool_output", outcome: "failed", summary: "MCP error result" },
  { id: "patch_add", eventKind: "patch", outcome: "success", summary: "patch added file" },
  { id: "patch_edit", eventKind: "patch", outcome: "success", summary: "patch edited file" },
  { id: "patch_delete", eventKind: "patch", outcome: "success", summary: "patch deleted file" },
  { id: "patch_rejected", eventKind: "patch", outcome: "failed", summary: "patch rejected" },
  { id: "patch_conflict", eventKind: "patch", outcome: "failed", summary: "patch conflict" },
  { id: "model_changed", eventKind: "lifecycle", outcome: "success", summary: "model changed" },
  { id: "model_reroute", eventKind: "lifecycle", outcome: "success", summary: "model rerouted" },
  { id: "auto_review_interruption", eventKind: "lifecycle", outcome: "stopped", summary: "auto-review interrupted generation" },
  { id: "approval_approved", eventKind: "lifecycle", outcome: "success", summary: "approval granted" },
  { id: "usage_tokens", eventKind: "usage", outcome: "success", summary: "token usage" },
  { id: "plan_update_checklist", eventKind: "goal", outcome: "success", summary: "plan checklist update" },
  { id: "web_search", eventKind: "search", outcome: "success", summary: "web search result" },
  { id: "subagent_spawn", eventKind: "subagent", outcome: "success", summary: "subagent spawned" },
  { id: "subagent_send", eventKind: "subagent", outcome: "success", summary: "subagent message sent" },
  { id: "subagent_wait", eventKind: "subagent", outcome: "success", summary: "subagent wait" },
  { id: "subagent_resume", eventKind: "subagent", outcome: "success", summary: "subagent resumed" },
  { id: "subagent_close", eventKind: "subagent", outcome: "success", summary: "subagent closed" },
  { id: "user_question", eventKind: "question", outcome: "success", summary: "user question" },
  { id: "approval_denied", eventKind: "question", outcome: "denied", summary: "approval denied" },
  { id: "mcp_tool_call", eventKind: "mcp", outcome: "success", summary: "MCP tool call" },
  { id: "compaction", eventKind: "compaction", outcome: "success", summary: "context compaction" },
  { id: "rollback", eventKind: "rollback", outcome: "success", summary: "rollback applied" },
  { id: "unknown_event", eventKind: "unknown", outcome: "unknown_fallback", summary: "unknown event fallback" },
] as const satisfies readonly SessionRenderFixture[];

export function sessionRenderMatrixRowFor(eventKind: SessionStructuredEventKind): SessionRenderMatrixRow {
  return sessionRenderMatrix[eventKind];
}
