import { mountOpenClaw } from "./openclaw.js";
import { mountAiModels } from "./ai-models.js";
import { mountIntegrations } from "./integrations.js";
import { mountChat } from "./chat.js";
import { mountTasks } from "./tasks.js";
import { mountCliTerminal } from "./cli-terminal.js";
import { mountCRM } from "./crm.js";
import { mountHelpDesk } from "./helpdesk.js";
import { mountOrgChart } from "./org-chart.js";
import { mountSocialMedia } from "./social-media.js";
import { mountKnowledgeBase } from "./knowledge-base.js";
import { mountWorkflowBuilder } from "./workflow-builder.js";
import { mountCalendar } from "./calendar.js";
import { mountIosApp } from "./ios-app.js";
import { mountMacApp } from "./mac-app.js";
import { mountRelay } from "./relay.js";
import { mountDatabase } from "./database.js";
import { mountDeck } from "./deck.js";
import { mountSheet } from "./sheet.js";

document.addEventListener("DOMContentLoaded", () => {
  const oc = document.getElementById("demo-openclaw");
  const ai = document.getElementById("demo-ai");
  const ig = document.getElementById("demo-integrations");
  const ch = document.getElementById("demo-chat");
  const tk = document.getElementById("demo-tasks");
  const cli = document.getElementById("cli-terminal-body");
  if (oc) mountOpenClaw(oc);
  if (ai) mountAiModels(ai);
  if (ig) mountIntegrations(ig);
  if (ch) mountChat(ch);
  if (tk) mountTasks(tk);
  if (cli) mountCliTerminal(cli);
  const crm = document.getElementById("demo-crm");
  if (crm) mountCRM(crm);
  const hd = document.getElementById("demo-helpdesk");
  if (hd) mountHelpDesk(hd);
  const org = document.getElementById("demo-org");
  if (org) mountOrgChart(org);
  const sm = document.getElementById("demo-social");
  if (sm) mountSocialMedia(sm);
  const kb = document.getElementById("demo-kb");
  if (kb) mountKnowledgeBase(kb);
  const wf = document.getElementById("demo-workflows");
  if (wf) mountWorkflowBuilder(wf);
  const cal = document.getElementById("demo-calendar");
  if (cal) mountCalendar(cal);
  const ios = document.getElementById("demo-ios");
  if (ios) mountIosApp(ios);
  const mac = document.getElementById("demo-mac");
  if (mac) mountMacApp(mac);
  const relay = document.getElementById("demo-relay");
  if (relay) mountRelay(relay);
  const db = document.getElementById("demo-database");
  if (db) mountDatabase(db);
  const deck = document.getElementById("demo-deck");
  if (deck) mountDeck(deck);
  const sheet = document.getElementById("demo-sheet");
  if (sheet) mountSheet(sheet);
});
