import type { BuiltinCollectionDefinition } from "../_types.ts";

export const SHIPMENTS: BuiltinCollectionDefinition = {
  name: "shipments",
  displayName: "Shipments",
  family: "transport",
  aliases: ["shipment", "shipments", "freight-shipment", "freight-shipments"],
  catalog: {
    purpose: "Transport shipment center for order movement, carrier execution, origin/destination, tracking, cost, evidence, and gaps.",
    evidence: ["human_recognizable", "market_validated", "multi_domain_reuse", "agent_useful"],
    relationGuidance: "Link companyId, customerCompanyId, carrierId, purchaseOrderId, and warehouseId when known; shipment legs hold multi-stop execution details.",
    notes: "This is TMS execution data; warehouse stock movements, purchase orders, accounting, and personal travel transports remain separate records.",
  },
  fields: [
    { name: "title", type: "text", required: true, requiredReason: "identity", aliases: ["reference", "shipmentNumber"] },
    { name: "companyId", type: "relation", relation: { collectionName: "companies" } },
    { name: "customerCompanyId", type: "relation", relation: { collectionName: "companies" } },
    { name: "carrierId", type: "relation", relation: { collectionName: "carriers" } },
    { name: "purchaseOrderId", type: "relation", relation: { collectionName: "purchase_orders" } },
    { name: "warehouseId", type: "relation", relation: { collectionName: "warehouses" } },
    { name: "mode", type: "select", options: ["parcel", "ltl", "ftl", "ocean", "air", "rail", "courier", "multimodal", "other", "unknown"] },
    { name: "status", type: "select", options: ["draft", "planned", "tendered", "in_transit", "delivered", "exception", "cancelled", "unknown"] },
    { name: "trackingNumber", type: "text" },
    { name: "originAddress", type: "address" },
    { name: "destinationAddress", type: "address" },
    { name: "plannedShipAt", type: "date" },
    { name: "shippedAt", type: "date" },
    { name: "deliveredAt", type: "date" },
    { name: "costCents", type: "number", min: 0 },
    { name: "currency", type: "currency" },
    { name: "source", type: "json" },
    { name: "links", type: "json" },
    { name: "evidence", type: "json" },
    { name: "qualityGaps", type: "json" },
    { name: "metadata", type: "json" },
    { name: "archivedAt", type: "date" },
  ],
  indexes: [
    { name: "shipments_title_idx", fields: ["title"] },
    { name: "shipments_company_idx", fields: ["companyId"] },
    { name: "shipments_carrier_idx", fields: ["carrierId"] },
    { name: "shipments_purchase_order_idx", fields: ["purchaseOrderId"] },
    { name: "shipments_warehouse_idx", fields: ["warehouseId"] },
    { name: "shipments_status_idx", fields: ["status"] },
    { name: "shipments_tracking_idx", fields: ["trackingNumber"] },
  ],
};
