import type { WorkspaceSurfaceDescriptor, WorkspaceToolDescriptor } from "@clawjs/core";

export const TOOL_DESCRIPTORS: WorkspaceToolDescriptor[] = [
  { id: "areas.create", title: "Create area", description: "Create an area in the local workspace.", domain: "areas" },
  { id: "areas.update", title: "Update area", description: "Update area state or ownership.", domain: "areas" },
  { id: "areas.list", title: "List areas", description: "List areas in the local workspace.", domain: "areas" },
  { id: "areas.search", title: "Search areas", description: "Search areas by name or description.", domain: "areas" },
  { id: "tasks.create", title: "Create task", description: "Create a task in the local workspace.", domain: "tasks" },
  { id: "tasks.update", title: "Update task", description: "Update task fields, assignees, dates, or labels.", domain: "tasks" },
  { id: "tasks.list", title: "List tasks", description: "List tasks in the local workspace.", domain: "tasks" },
  { id: "tasks.search", title: "Search tasks", description: "Search tasks by keyword or hybrid search.", domain: "tasks" },
  { id: "tasks.complete", title: "Complete task", description: "Mark a task as done.", domain: "tasks" },
  { id: "goals.create", title: "Create goal", description: "Create a goal in the local workspace.", domain: "goals" },
  { id: "goals.update", title: "Update goal", description: "Update goal status, owner, or metrics.", domain: "goals" },
  { id: "goals.list", title: "List goals", description: "List goals in the local workspace.", domain: "goals" },
  { id: "goals.search", title: "Search goals", description: "Search goals by title, description, or metrics.", domain: "goals" },
  { id: "projects.create", title: "Create project", description: "Create a project in the local workspace.", domain: "projects" },
  { id: "projects.update", title: "Update project", description: "Update project state or ownership.", domain: "projects" },
  { id: "projects.list", title: "List projects", description: "List projects in the local workspace.", domain: "projects" },
  { id: "projects.search", title: "Search projects", description: "Search projects by name or description.", domain: "projects" },
  { id: "milestones.create", title: "Create milestone", description: "Create a milestone in the local workspace.", domain: "milestones" },
  { id: "milestones.update", title: "Update milestone", description: "Update milestone status or target date.", domain: "milestones" },
  { id: "milestones.list", title: "List milestones", description: "List milestones in the local workspace.", domain: "milestones" },
  { id: "milestones.search", title: "Search milestones", description: "Search milestones by title or description.", domain: "milestones" },
  { id: "activity.list", title: "List activity", description: "List productivity activity entries.", domain: "activity" },
  { id: "activity.search", title: "Search activity", description: "Search productivity activity entries.", domain: "activity" },
  { id: "blockers.create", title: "Create blocker", description: "Create an explicit blocker linked to work.", domain: "blockers" },
  { id: "blockers.update", title: "Update blocker", description: "Resolve or re-scope a blocker.", domain: "blockers" },
  { id: "blockers.list", title: "List blockers", description: "List blockers in the local workspace.", domain: "blockers" },
  { id: "artifacts.create", title: "Create artifact", description: "Attach evidence or output to work.", domain: "artifacts" },
  { id: "artifacts.update", title: "Update artifact", description: "Update stored evidence metadata.", domain: "artifacts" },
  { id: "artifacts.list", title: "List artifacts", description: "List captured work evidence.", domain: "artifacts" },
  { id: "decisions.create", title: "Create decision", description: "Record an operational decision.", domain: "decisions" },
  { id: "decisions.update", title: "Update decision", description: "Update decision state or rationale.", domain: "decisions" },
  { id: "decisions.list", title: "List decisions", description: "List recorded decisions.", domain: "decisions" },
  { id: "workSessions.create", title: "Start work session", description: "Start a focused work session.", domain: "work_sessions" },
  { id: "workSessions.update", title: "Update work session", description: "Update or close a work session.", domain: "work_sessions" },
  { id: "workSessions.list", title: "List work sessions", description: "List focused work sessions.", domain: "work_sessions" },
  { id: "assignments.create", title: "Create assignment", description: "Assign work to an agent.", domain: "assignments" },
  { id: "assignments.update", title: "Update assignment", description: "Accept, reject, or release an assignment.", domain: "assignments" },
  { id: "assignments.list", title: "List assignments", description: "List agent assignments.", domain: "assignments" },
  { id: "handoffs.create", title: "Create handoff", description: "Create a structured handoff between agents.", domain: "handoffs" },
  { id: "handoffs.update", title: "Update handoff", description: "Accept, return, or complete a handoff.", domain: "handoffs" },
  { id: "handoffs.list", title: "List handoffs", description: "List coordination handoffs.", domain: "handoffs" },
  { id: "approvals.create", title: "Create approval", description: "Open an approval gate for sensitive work.", domain: "approvals" },
  { id: "approvals.update", title: "Update approval", description: "Approve or reject a gated action.", domain: "approvals" },
  { id: "approvals.list", title: "List approvals", description: "List approval requests.", domain: "approvals" },
  { id: "capacity.create", title: "Create capacity snapshot", description: "Store an agent capacity baseline.", domain: "capacity" },
  { id: "capacity.update", title: "Update capacity snapshot", description: "Update a capacity baseline or override.", domain: "capacity" },
  { id: "capacity.list", title: "List capacity", description: "List team capacity snapshots.", domain: "capacity" },
  { id: "agents.create", title: "Create agent", description: "Create an agent roster entry.", domain: "agents" },
  { id: "agents.update", title: "Update agent", description: "Update agent status, autonomy, or policy.", domain: "agents" },
  { id: "agents.list", title: "List agents", description: "List agent roster entries.", domain: "agents" },
  { id: "releases.create", title: "Create release", description: "Create a release entry linked to work.", domain: "releases" },
  { id: "releases.update", title: "Update release", description: "Update release status or risk.", domain: "releases" },
  { id: "releases.list", title: "List releases", description: "List active and planned releases.", domain: "releases" },
  { id: "incidents.create", title: "Create incident", description: "Capture an operational incident.", domain: "incidents" },
  { id: "incidents.update", title: "Update incident", description: "Update incident state or severity.", domain: "incidents" },
  { id: "incidents.list", title: "List incidents", description: "List operational incidents.", domain: "incidents" },
  { id: "feedback.create", title: "Create feedback", description: "Capture external or internal feedback.", domain: "feedback" },
  { id: "feedback.update", title: "Update feedback", description: "Triage feedback and link follow-up work.", domain: "feedback" },
  { id: "feedback.list", title: "List feedback", description: "List feedback backlog items.", domain: "feedback" },
  { id: "checks.create", title: "Create check", description: "Create an operational check.", domain: "checks" },
  { id: "checks.update", title: "Update check", description: "Update check state or result.", domain: "checks" },
  { id: "checks.list", title: "List checks", description: "List operational checks.", domain: "checks" },
  { id: "reminders.create", title: "Create reminder", description: "Create a reminder in the local workspace.", domain: "reminders" },
  { id: "reminders.update", title: "Update reminder", description: "Update reminder timing or status.", domain: "reminders" },
  { id: "reminders.list", title: "List reminders", description: "List reminders in the local workspace.", domain: "reminders" },
  { id: "reminders.pause", title: "Pause reminder", description: "Pause an active reminder.", domain: "reminders" },
  { id: "reminders.resume", title: "Resume reminder", description: "Resume a paused reminder.", domain: "reminders" },
  { id: "deadlines.create", title: "Create deadline", description: "Create a deadline in the local workspace.", domain: "deadlines" },
  { id: "deadlines.update", title: "Update deadline", description: "Update deadline timing or status.", domain: "deadlines" },
  { id: "deadlines.list", title: "List deadlines", description: "List deadlines in the local workspace.", domain: "deadlines" },
  { id: "deadlines.pause", title: "Pause deadline", description: "Pause an active deadline.", domain: "deadlines" },
  { id: "deadlines.resume", title: "Resume deadline", description: "Resume a paused deadline.", domain: "deadlines" },
  { id: "notes.create", title: "Create note", description: "Create a note in the local workspace.", domain: "notes" },
  { id: "notes.update", title: "Update note", description: "Update note content or metadata.", domain: "notes" },
  { id: "notes.get", title: "Get note", description: "Read one note by id.", domain: "notes" },
  { id: "notes.search", title: "Search notes", description: "Search notes by keyword or hybrid search.", domain: "notes" },
  { id: "people.upsert", title: "Upsert person", description: "Create or update a contact/person record.", domain: "people" },
  { id: "people.get", title: "Get person", description: "Read one person by id.", domain: "people" },
  { id: "people.search", title: "Search people", description: "Search contacts and identities.", domain: "people" },
  { id: "inbox.list", title: "List inbox threads", description: "List local inbox threads.", domain: "inbox" },
  { id: "inbox.search", title: "Search inbox", description: "Search unified inbox threads.", domain: "inbox" },
  { id: "inbox.readThread", title: "Read thread", description: "Read one inbox thread and its messages.", domain: "inbox" },
  { id: "inbox.createDraft", title: "Create draft", description: "Create an outbound draft inside the inbox.", domain: "inbox" },
  { id: "inbox.routeReply", title: "Route reply", description: "Create an outbound reply for a thread.", domain: "inbox" },
  { id: "events.create", title: "Create event", description: "Create a calendar event with reminders.", domain: "events" },
  { id: "events.update", title: "Update event", description: "Update an existing event.", domain: "events" },
  { id: "events.list", title: "List events", description: "List events in the local workspace.", domain: "events" },
  { id: "events.search", title: "Search events", description: "Search events by title, description, or location.", domain: "events" },
  { id: "workspace.search.query", title: "Search workspace", description: "Search across tasks, notes, people, inbox, and events.", domain: "workspace" },
];

export const SURFACES: WorkspaceSurfaceDescriptor[] = [
  { id: "areas", title: "Areas", route: "/areas", icon: "layers", order: 8 },
  { id: "tasks", title: "Tasks", route: "/tasks", icon: "check-square", badgeId: "tasks_due_today", order: 10 },
  { id: "goals", title: "Goals", route: "/goals", icon: "target", order: 15 },
  { id: "projects", title: "Projects", route: "/projects", icon: "folder-kanban", order: 18 },
  { id: "milestones", title: "Milestones", route: "/milestones", icon: "flag", order: 19 },
  { id: "blockers", title: "Blockers", route: "/tasks", icon: "octagon-alert", badgeId: "blockers_active", order: 19 },
  { id: "decisions", title: "Decisions", route: "/tasks", icon: "git-branch-plus", badgeId: "decisions_pending", order: 19 },
  { id: "assignments", title: "Assignments", route: "/tasks", icon: "user-plus", badgeId: "assignments_active", order: 19 },
  { id: "handoffs", title: "Handoffs", route: "/tasks", icon: "repeat", badgeId: "handoffs_pending", order: 19 },
  { id: "approvals", title: "Approvals", route: "/tasks", icon: "shield-check", badgeId: "approvals_pending", order: 19 },
  { id: "capacity", title: "Capacity", route: "/tasks", icon: "gauge", badgeId: "capacity_overloaded", order: 19 },
  { id: "agents", title: "Agents", route: "/tasks", icon: "bot", badgeId: "agents_gated", order: 19 },
  { id: "releases", title: "Releases", route: "/tasks", icon: "rocket", badgeId: "releases_at_risk", order: 19 },
  { id: "incidents", title: "Incidents", route: "/tasks", icon: "siren", badgeId: "incidents_open", order: 19 },
  { id: "feedback", title: "Feedback", route: "/tasks", icon: "message-square", badgeId: "feedback_new", order: 19 },
  { id: "checks", title: "Checks", route: "/tasks", icon: "clipboard-check", badgeId: "checks_failing", order: 19 },
  { id: "notes", title: "Notes", route: "/notes", icon: "file-text", order: 20 },
  { id: "people", title: "People", route: "/people", icon: "users", order: 30 },
  { id: "inbox", title: "Inbox", route: "/inbox", icon: "inbox", badgeId: "inbox_unread", order: 40 },
  { id: "events", title: "Events", route: "/events", icon: "calendar", badgeId: "events_upcoming", order: 50 },
  { id: "reminders", title: "Reminders", route: "/reminders", icon: "bell", order: 55 },
  { id: "deadlines", title: "Deadlines", route: "/deadlines", icon: "alarm-clock", order: 58 },
];
