import type { BuiltinFamilyDefinition } from "../_types.ts";

import {
  CANONICAL_OPERATIONS,
  CONCEPTS,
  CONCEPT_MAPPINGS,
  DOMAIN_INTENTS,
  DOMAIN_PACKS,
  DOMAIN_PROFILES,
  DOMAIN_ROLES,
  DOMAIN_SYSTEMS,
  EVIDENCE_SOURCES,
  INSTRUMENTS,
  INSTRUMENT_ITEMS,
  INSTRUMENT_RESPONSES,
  PROVENANCE_EVENTS,
  QUALITY_GAPS,
  SEMANTIC_VIEWS,
  UNITS,
  VOCABULARIES,
} from "./foundation_collections.ts";

export const DATA_FOUNDATION_FAMILY: BuiltinFamilyDefinition = {
  name: "data_foundation",
  displayName: "Data Foundation",
  description: "Shared dense-data primitives for identities, roles, evidence, provenance, gaps, semantic views, intents, vocabularies, units, instruments, and responses.",
  collections: [
    DOMAIN_SYSTEMS,
    DOMAIN_PACKS,
    DOMAIN_ROLES,
    DOMAIN_PROFILES,
    EVIDENCE_SOURCES,
    PROVENANCE_EVENTS,
    QUALITY_GAPS,
    CANONICAL_OPERATIONS,
    SEMANTIC_VIEWS,
    DOMAIN_INTENTS,
    VOCABULARIES,
    CONCEPTS,
    CONCEPT_MAPPINGS,
    UNITS,
    INSTRUMENTS,
    INSTRUMENT_ITEMS,
    INSTRUMENT_RESPONSES,
  ],
};

export {
  CANONICAL_OPERATIONS,
  CONCEPTS,
  CONCEPT_MAPPINGS,
  DOMAIN_INTENTS,
  DOMAIN_PACKS,
  DOMAIN_PROFILES,
  DOMAIN_ROLES,
  DOMAIN_SYSTEMS,
  EVIDENCE_SOURCES,
  INSTRUMENTS,
  INSTRUMENT_ITEMS,
  INSTRUMENT_RESPONSES,
  PROVENANCE_EVENTS,
  QUALITY_GAPS,
  SEMANTIC_VIEWS,
  UNITS,
  VOCABULARIES,
};
