import type { EntityType } from "../types.ts";

type Definition = Omit<EntityType, "id" | "createdAt" | "version">;

export const canonicalTypes: Definition[] = [
  {
    name: "product",
    canonical: true,
    identityFields: ["vendor", "sku"],
    timeseriesFields: ["price", "currency", "stock", "rating", "review_count", "position_in_search"],
    uiHints: { icon: "shopping-bag", cardKind: "media", accentColor: "#ff9b6a" },
    schemaJson: {
      type: "object",
      required: ["title", "source_url"],
      properties: {
        title: { type: "string" },
        vendor: { type: "string" },
        brand: { type: "string" },
        sku: { type: "string" },
        canonical_url: { type: "string", format: "uri" },
        source_url: { type: "string", format: "uri" },
        price: { type: "number", timeseries: true },
        currency: { type: "string", timeseries: true },
        stock: { type: "string", timeseries: true },
        rating: { type: "number", timeseries: true },
        review_count: { type: "integer", timeseries: true },
        description: { type: "string" },
      },
    },
  },
  {
    name: "listing",
    canonical: true,
    identityFields: ["canonical_url"],
    timeseriesFields: ["price", "price_per_night", "availability", "rating", "review_count"],
    uiHints: { icon: "bed-double", cardKind: "media", accentColor: "#7aa8ff" },
    schemaJson: {
      type: "object",
      required: ["title", "canonical_url"],
      properties: {
        subtype: { type: "string", enum: ["hotel", "car", "realestate", "short_term_rental"] },
        title: { type: "string" },
        canonical_url: { type: "string", format: "uri" },
        source_url: { type: "string", format: "uri" },
        price: { type: "number", timeseries: true },
        price_per_night: { type: "number", timeseries: true },
        currency: { type: "string" },
        availability: { type: "string", timeseries: true },
        rating: { type: "number", timeseries: true },
        review_count: { type: "integer", timeseries: true },
        location: {
          type: "object",
          properties: {
            lat: { type: "number" },
            lon: { type: "number" },
            city: { type: "string" },
            country: { type: "string" },
          },
        },
      },
    },
  },
  {
    name: "article",
    canonical: true,
    identityFields: ["canonical_url"],
    timeseriesFields: ["view_count"],
    uiHints: { icon: "newspaper", cardKind: "text", accentColor: "#c4a26b" },
    schemaJson: {
      type: "object",
      required: ["title", "canonical_url"],
      properties: {
        title: { type: "string" },
        canonical_url: { type: "string", format: "uri" },
        source_url: { type: "string", format: "uri" },
        author_name: { type: "string" },
        publication: { type: "string" },
        published_at: { type: "string", format: "date-time" },
        summary: { type: "string" },
        content_text: { type: "string" },
        view_count: { type: "integer", timeseries: true },
      },
    },
  },
  {
    name: "post",
    canonical: true,
    identityFields: ["platform", "post_id"],
    timeseriesFields: ["likes", "replies", "reposts", "views", "bookmarks"],
    uiHints: { icon: "message-square", cardKind: "text", accentColor: "#a08bff" },
    schemaJson: {
      type: "object",
      required: ["platform", "post_id"],
      properties: {
        platform: { type: "string" },
        post_id: { type: "string" },
        source_url: { type: "string", format: "uri" },
        author_handle: { type: "string" },
        author_name: { type: "string" },
        content_text: { type: "string" },
        likes: { type: "integer", timeseries: true },
        replies: { type: "integer", timeseries: true },
        reposts: { type: "integer", timeseries: true },
        views: { type: "integer", timeseries: true },
        bookmarks: { type: "integer", timeseries: true },
        posted_at: { type: "string", format: "date-time" },
      },
    },
  },
  {
    name: "video",
    canonical: true,
    identityFields: ["platform", "video_id"],
    timeseriesFields: ["views", "likes", "comment_count"],
    uiHints: { icon: "play", cardKind: "media", accentColor: "#ff6f6f" },
    schemaJson: {
      type: "object",
      required: ["platform", "video_id"],
      properties: {
        platform: { type: "string" },
        video_id: { type: "string" },
        source_url: { type: "string", format: "uri" },
        channel_name: { type: "string" },
        title: { type: "string" },
        description: { type: "string" },
        duration_s: { type: "integer" },
        thumbnail_url: { type: "string" },
        views: { type: "integer", timeseries: true },
        likes: { type: "integer", timeseries: true },
        comment_count: { type: "integer", timeseries: true },
      },
    },
  },
  {
    name: "episode",
    canonical: true,
    identityFields: ["podcast_id", "episode_id"],
    timeseriesFields: ["downloads", "rating"],
    uiHints: { icon: "headphones", cardKind: "media", accentColor: "#b66cff" },
    schemaJson: {
      type: "object",
      required: ["podcast_id", "episode_id", "title"],
      properties: {
        podcast_id: { type: "string" },
        episode_id: { type: "string" },
        podcast_name: { type: "string" },
        title: { type: "string" },
        audio_url: { type: "string" },
        duration_s: { type: "integer" },
        published_at: { type: "string", format: "date-time" },
        show_notes: { type: "string" },
        downloads: { type: "integer", timeseries: true },
        rating: { type: "number", timeseries: true },
      },
    },
  },
  {
    name: "paper",
    canonical: true,
    identityFields: ["doi"],
    timeseriesFields: ["citations", "downloads"],
    uiHints: { icon: "file-text", cardKind: "text", accentColor: "#5fbf9a" },
    schemaJson: {
      type: "object",
      required: ["title"],
      properties: {
        doi: { type: "string" },
        arxiv_id: { type: "string" },
        title: { type: "string" },
        authors: { type: "array", items: { type: "string" } },
        venue: { type: "string" },
        published_at: { type: "string", format: "date-time" },
        abstract: { type: "string" },
        pdf_url: { type: "string" },
        citations: { type: "integer", timeseries: true },
        downloads: { type: "integer", timeseries: true },
      },
    },
  },
  {
    name: "profile",
    canonical: true,
    identityFields: ["platform", "handle"],
    timeseriesFields: ["followers", "following", "post_count"],
    uiHints: { icon: "user", cardKind: "media", accentColor: "#ffb56c" },
    schemaJson: {
      type: "object",
      required: ["platform", "handle"],
      properties: {
        platform: { type: "string" },
        handle: { type: "string" },
        name: { type: "string" },
        bio: { type: "string" },
        avatar_url: { type: "string" },
        followers: { type: "integer", timeseries: true },
        following: { type: "integer", timeseries: true },
        post_count: { type: "integer", timeseries: true },
      },
    },
  },
  {
    name: "place",
    canonical: true,
    identityFields: ["google_place_id"],
    timeseriesFields: ["rating", "review_count", "price_level"],
    uiHints: { icon: "map-pin", cardKind: "media", accentColor: "#ff8aa6" },
    schemaJson: {
      type: "object",
      required: ["name"],
      properties: {
        google_place_id: { type: "string" },
        name: { type: "string" },
        address: { type: "string" },
        lat: { type: "number" },
        lon: { type: "number" },
        cuisine: { type: "string" },
        rating: { type: "number", timeseries: true },
        review_count: { type: "integer", timeseries: true },
        price_level: { type: "integer", timeseries: true },
      },
    },
  },
  {
    name: "channel",
    canonical: true,
    identityFields: ["canonical_url"],
    timeseriesFields: ["subscribers", "post_frequency"],
    uiHints: { icon: "radio", cardKind: "text", accentColor: "#6cd0e0" },
    schemaJson: {
      type: "object",
      required: ["canonical_url", "title"],
      properties: {
        canonical_url: { type: "string", format: "uri" },
        title: { type: "string" },
        description: { type: "string" },
        language: { type: "string" },
        subscribers: { type: "integer", timeseries: true },
        post_frequency: { type: "number", timeseries: true },
      },
    },
  },
  {
    name: "doc",
    canonical: true,
    identityFields: ["canonical_url"],
    timeseriesFields: ["last_modified_at"],
    uiHints: { icon: "book-open", cardKind: "text", accentColor: "#8aa9d9" },
    schemaJson: {
      type: "object",
      required: ["canonical_url", "title"],
      properties: {
        canonical_url: { type: "string", format: "uri" },
        site: { type: "string" },
        title: { type: "string" },
        content_text: { type: "string" },
        last_modified_at: { type: "string", format: "date-time", timeseries: true },
      },
    },
  },
  {
    name: "repo",
    canonical: true,
    identityFields: ["host", "owner", "name"],
    timeseriesFields: ["stars", "forks", "open_issues"],
    uiHints: { icon: "github", cardKind: "text", accentColor: "#9aa3b3" },
    schemaJson: {
      type: "object",
      required: ["host", "owner", "name"],
      properties: {
        host: { type: "string" },
        owner: { type: "string" },
        name: { type: "string" },
        description: { type: "string" },
        primary_language: { type: "string" },
        license: { type: "string" },
        stars: { type: "integer", timeseries: true },
        forks: { type: "integer", timeseries: true },
        open_issues: { type: "integer", timeseries: true },
      },
    },
  },
  {
    name: "event",
    canonical: true,
    identityFields: ["canonical_url", "starts_at"],
    timeseriesFields: ["tickets_left", "price_min", "price_max"],
    uiHints: { icon: "calendar", cardKind: "media", accentColor: "#f08f6a" },
    schemaJson: {
      type: "object",
      required: ["title", "starts_at"],
      properties: {
        title: { type: "string" },
        canonical_url: { type: "string", format: "uri" },
        starts_at: { type: "string", format: "date-time" },
        ends_at: { type: "string", format: "date-time" },
        location: { type: "string" },
        description: { type: "string" },
        tickets_left: { type: "integer", timeseries: true },
        price_min: { type: "number", timeseries: true },
        price_max: { type: "number", timeseries: true },
      },
    },
  },
  {
    name: "job",
    canonical: true,
    identityFields: ["canonical_url"],
    timeseriesFields: ["applicants"],
    uiHints: { icon: "briefcase", cardKind: "text", accentColor: "#86b985" },
    schemaJson: {
      type: "object",
      required: ["canonical_url", "title"],
      properties: {
        canonical_url: { type: "string", format: "uri" },
        title: { type: "string" },
        company_name: { type: "string" },
        location: { type: "string" },
        remote_policy: { type: "string" },
        salary_min: { type: "number" },
        salary_max: { type: "number" },
        description: { type: "string" },
        applicants: { type: "integer", timeseries: true },
      },
    },
  },
  {
    name: "review",
    canonical: true,
    identityFields: ["target_entity_id", "author_profile_id", "posted_at"],
    timeseriesFields: ["helpful_count"],
    uiHints: { icon: "star", cardKind: "text", accentColor: "#ffce6f" },
    schemaJson: {
      type: "object",
      required: ["target_entity_id", "rating"],
      properties: {
        target_entity_id: { type: "string" },
        author_name: { type: "string" },
        rating: { type: "number" },
        title: { type: "string" },
        content_text: { type: "string" },
        helpful_count: { type: "integer", timeseries: true },
        posted_at: { type: "string", format: "date-time" },
      },
    },
  },
];

export function getCanonicalByName(name: string): Definition | null {
  return canonicalTypes.find((entry) => entry.name === name) ?? null;
}
